CREATE OR REPLACE FORCE VIEW "ANALESTA"."ANE_COMISIONES" AS 
  SELECT L.EMCODI EMPRESA, FI.CLIENTE_ID CLIENTE, C.RAZON_SOC NOMBRE_CLIENTE,
         C.PAIS, C.NOMBRE NOMBRE_PAIS,
         V.VENDEDOR, V.NOMBRE_VENDEDOR, 
         L.ASLOTE OT, DECODE(O.SITUACIO,'C',O.FEC_MODI) FEC_CIERRE_OT, 
         O.NUMEPEDI, P.FEC_ALTA FEC_ALTA_PEDIDO,
         
         (SELECT COUNT(*) FROM FIC_CABEOTTE OTT WHERE OTT.EMPRESA = O.EMPRESA AND OTT.NUMEPEDI = O.NUMEPEDI) TOTAL_PARTES,
       ANALESTA.P_ANE_MERMLAMI_PRAG.F_Numero_Parte(O.EMPRESA,O.NUMEPEDI,O.NUMEOTTE) IDENT_PARTE,
DECODE(
       (SELECT '5' COMPRUEBA
            FROM FV_ASVEFA02 F, 
                 (SELECT DISTINCT EMCODI, DICODI, ASCANA, CFNROF, CPNROP, ASLOTE FROM FV_ASVELO01 WHERE PROCED = 'F') L
            WHERE F.EMCODI = L.EMCODI
              AND F.DICODI = L.DICODI
              AND F.ASCANA = L.ASCANA
              AND F.CFNROF = L.CFNROF
              AND F.CPNROP = L.CPNROP
              AND L.EMCODI = O.EMPRESA
              --AND L.ASLOTE = TO_CHAR(O.NUMERO)
              AND L.ASLOTE = O.NUMERO
              AND L.CPNROP = O.NUMEPEDI
              AND (F.VATCOD = P_UTILIDAD.F_VALODEVA('TIARFIF4') OR 
                   (F.VATCOD = P_UTILIDAD.F_VALODEVA('TIARGCF4') AND 
                    EXISTS (SELECT 'X' FROM VALORES_LISTA LH
                            WHERE LH.CODIGO = 'GNR_ARTIHORA'
                              AND P_UTILIDAD.F_VALOCAMPO(LH.VALOR,'EMPRESA') = F.EMCODI 
                              AND P_UTILIDAD.F_VALOCAMPO(LH.VALOR,'TIP_ARTI') = F.VATCOD 
                              AND P_UTILIDAD.F_VALOCAMPO(LH.VALOR,'COD_ARTI') = F.ARCARF
                           )
                   )
                  )
              AND NVL(L.CFNROF,0) != 0
              AND F.PPTIPO NOT IN ('A','X','B','L','O')
              AND ROWNUM = 1),'5','FACTURADO A CLIENTE',
       DECODE((SELECT '4' COMPRUEBA
            FROM FV_ASVEAL02 A, 
                 (SELECT DISTINCT EMCODI, DICODI, ASCANA, ALNROP, CPNROP, ASLOTE FROM FV_ASVELO01 WHERE NVL(CFNROF,0) = 0) L
            WHERE A.EMCODI = L.EMCODI
              AND A.DICODI = L.DICODI
              AND A.ASCANA = L.ASCANA
              AND A.ALNROP = L.ALNROP
              AND A.CPNROP = L.CPNROP
              AND L.EMCODI = O.EMPRESA
              --AND L.ASLOTE = TO_CHAR(O.NUMERO)
              AND L.ASLOTE = O.NUMERO
              AND L.CPNROP = O.NUMEPEDI
              AND (A.VATCOD = P_UTILIDAD.F_VALODEVA('TIARFIF4') OR 
                   (A.VATCOD = P_UTILIDAD.F_VALODEVA('TIARGCF4') AND 
                    EXISTS (SELECT 'X' FROM VALORES_LISTA LH
                            WHERE LH.CODIGO = 'GNR_ARTIHORA'
                              AND P_UTILIDAD.F_VALOCAMPO(LH.VALOR,'EMPRESA') = A.EMCODI 
                              AND P_UTILIDAD.F_VALOCAMPO(LH.VALOR,'TIP_ARTI') = A.VATCOD 
                              AND P_UTILIDAD.F_VALOCAMPO(LH.VALOR,'COD_ARTI') = A.ARCARF
                           )
                   )
                  )
              AND ROWNUM = 1),'4','ALBARÁN EMITIDO PERO NO FACTURADO',
              DECODE(O.SITUACIO,'C','FINALIZADA',
              DECODE((SELECT '2' FROM PRD_PRMAEVEN E WHERE E.EMPRESA = O.EMPRESA AND E.NUMEOTRE = O.NUMERO AND ROWNUM = 1),'2','EN CURSO',
              DECODE((SELECT '2' FROM PRD_CAPAMAQU E WHERE E.EMPRESA = O.EMPRESA AND E.NUMEOTRE = O.NUMERO AND ROWNUM = 1),'2','EN CURSO',
              'NO INCIADO'))))) SITUACION,
         
         F.ARCARF ESPECIALIDAD, 
			SUBSTR(FI.MATBASE,1,2) LINEA, FI.MATBASE LFS, 
			F.VATCOD TIPO_ARTICULO,
         L.CFNDEF NUMEFACT, 
         FA.CFFALT FECHA_FACTURA,
         F.LFIMPO EUROS,
         CO.PORCCOMI PORCENTAJE_COMISION,
         (F.LFIMPO*CO.PORCCOMI)/100 EUROS_COMISION
  FROM FV_ASVEFA02 F, FV_ASVEFA01 FA, 
       (SELECT EMPRESA, NUMEPEDI, PORCCOMI FROM FIC_COMIPEDI WHERE LINECOMI = 1) CO,
       (SELECT DISTINCT EMCODI, DICODI, ASCANA, CFNROF, CFNDEF, CPNROP, ASLOTE, ALNROP FROM FV_ASVELO01 WHERE PROCED = 'F') L, 
       FIC_CABEOTRE O, FIC_HCABEPED P, HFICTEC FI,
       (SELECT C.EMPRESA, C.CLIENTE_ID, C.RAZON_SOC, C.PAIS, P.NOMBRE, M.CLDESC MERCADO FROM CLIENTES C, GNR_PAISES P, FV_ASMATA20 M WHERE C.PAIS = P.PAIS AND C.TIPOPCLI = M.CLCLAS) C,
       (SELECT CV.EMPRESA,CV. CLIENTE_ID, CV.VENDEDOR, V.NOMBRE NOMBRE_VENDEDOR FROM GNR_CLVENDED CV, GNR_VENDEDOR V WHERE CV.TIPO = V.TIPO AND CV.VENDEDOR = V.VENDEDOR AND CV.ACTIVA = 'S') V
  WHERE F.EMCODI = FA.EMCODI
     AND F.DICODI = FA.DICODI
     AND F.ASCANA = FA.ASCANA
     AND F.PPTIPO = FA.PPTIPO
     AND F.CFNROF = FA.CFNROF
	  --
     AND F.EMCODI = L.EMCODI
     AND F.DICODI = L.DICODI
     AND F.ASCANA = L.ASCANA
     AND F.CFNROF = L.CFNROF
     AND F.CPNROP = L.CPNROP
	  AND F.ALNROP = L.ALNROP
	  --NEW
	  AND F.VATCOD = O.TIP_ARTI--NEW
	  AND F.ARCARF = O.COD_ARTI--NEW
	  --
     AND L.EMCODI = O.EMPRESA
     AND L.ASLOTE = TO_CHAR(O.NUMERO)
     AND L.CPNROP = O.NUMEPEDI
	  --
     AND FI.EMPRESA = C.EMPRESA
     AND FI.CLIENTE_ID = C.CLIENTE_ID
	  --
     AND FI.EMPRESA = V.EMPRESA(+)
     AND FI.CLIENTE_ID = V.CLIENTE_ID(+)
	  --
     AND O.EMPRESA = P.EMPRESA
     AND O.NUMEPEDI = P.NUMEPEDI
	  --
     AND P.TIPOACCI = 'I'
     AND (F.VATCOD = P_Utilidad.F_ValoDeva('TIARFIF4') OR 
          (F.VATCOD = P_Utilidad.F_ValoDeva('TIARGCF4') AND 
           EXISTS (SELECT 'X' FROM VALORES_LISTA LH --Articulos tipo C de Horas
                   WHERE LH.CODIGO = 'GNR_ARTIHORA'
                     AND P_UTILIDAD.F_VALOCAMPO(LH.VALOR,'EMPRESA') = F.EMCODI 
                     AND P_UTILIDAD.F_VALOCAMPO(LH.VALOR,'TIP_ARTI') = F.VATCOD 
                     AND P_UTILIDAD.F_VALOCAMPO(LH.VALOR,'COD_ARTI') = F.ARCARF
                  )
          )
         )
     AND NVL(L.CFNROF,0) != 0
     --AND NOT EXISTS (SELECT 'X' FROM ANE_OBCOTRAZ T WHERE T.EMPRESA = L.EMCODI AND TO_CHAR(T.NUMERO_OT) = L.ASLOTE)
     AND F.PPTIPO NOT IN ('A','X','B','L','O') --A Abono Nacional, X Abono Exportacion, B Abono Mostrador, L Abono atipico Exp, O Abonos atipicos
	  --
     AND O.EMPRESA = FI.EMPRESA(+)
     AND O.TIP_ARTI = FI.TIP_ARTI(+)
     AND O.COD_ARTI = FI.PRODUCTO(+)
     AND NVL(O.MODI,0) = NVL(FI.MODI(+),0)
     AND NVL(O.REVI,0) = NVL(FI.REVI(+),0)
	  --
     AND O.EMPRESA = CO.EMPRESA(+)
     AND O.NUMEPEDI = CO.NUMEPEDI(+);
/