--------------------------------------------------------
--  DDL for View ANE_DISTRIB
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "ANALESTA"."ANE_DISTRIB" ("EMPRESA", "N_CLIENTE", "CLIENTE", "PAIS", "NOMBRE_PAIS", "N_OT", "FEC_CIERRE_OT", "PEDIDO", "FEC_ALTA_PEDIDO", "ALABARAN", "FECHA_ALBARAN", "TIPO_PRD", "ESPECIALIDAD", "LINEA", "LFS", "CODIGO_TRANSPORTE", "DESCRIPCION_TRANSPORTE", "N_TRANSPORTISTA", "NOMBRE_TRANSPORTISTA", "KILOS_BRUTOS", "FACTURA", "FECHA_FACTURA", "EUROS_FACTURA") AS 
  SELECT L.EMCODI EMPRESA, FI.CLIENTE_ID N_CLIENTE, C.RAZON_SOC CLIENTE,
         C.PAIS, C.NOMBRE NOMBRE_PAIS,
         L.ASLOTE N_OT, DECODE(O.SITUACIO,'C',O.FEC_MODI) FEC_CIERRE_OT, 
         O.NUMEPEDI PEDIDO, P.FEC_ALTA FEC_ALTA_PEDIDO,
         F.ALNROP ALABARAN, AL.ALFALT FECHA_ALBARAN, 
         F.VATCOD TIPO_PRD, F.ARCARF ESPECIALIDAD, SUBSTR(FI.MATBASE,1,2) LINEA, FI.MATBASE LFS,
         AL.TRACOD CODIGO_TRANSPORTE, T.TRADES DESCRIPCION_TRANSPORTE,
         AL.MTTRAN N_TRANSPORTISTA, TR.RAZOSO NOMBRE_TRANSPORTISTA,
         AL.ALPBRU KILOS_BRUTOS,
         L.CFNDEF FACTURA, 
         FA.CFFALT FECHA_FACTURA,
         F.LFIMPO EUROS_FACTURA
            FROM FV_ASVEFA02 F, FV_ASVEFA01 FA, FV_ASMATA50 T, GENERAL.GNR_TTISTAS TR,
                 (SELECT DISTINCT EMCODI, DICODI, ASCANA, CFNROF, CFNDEF, CPNROP, ASLOTE, ALNROP FROM FV_ASVELO01 WHERE PROCED = 'F') L, 
                 FIC_CABEOTRE O, FIC_HCABEPED P,
                 (SELECT HA.EMCODI, HA.ALNROP, HA.ALFALT, HA.TRACOD, HA.MTTRAN, HA.ALPBRU FROM FV_ASVEALH01 HA
                  UNION
                  SELECT AL.EMCODI, AL.ALNROP, AL.ALFALT, AL.TRACOD, AL.MTTRAN, AL.ALPBRU FROM FV_ASVEAL01 AL WHERE NOT EXISTS (SELECT 'X' FROM FV_ASVEALH01 HA WHERE HA.EMCODI = AL.EMCODI AND HA.DICODI = AL.DICODI AND HA.ASCANA = AL.ASCANA AND HA.PPTIPO = AL.PPTIPO AND HA.ALNROP = AL.ALNROP)) AL,
                 (SELECT F.EMPRESA, F.TIP_ARTI, F.PRODUCTO, F.MODI, F.REVI, F.ANCHO, F.LARGO, F.MATBASE, L.FCKG, L.DESCRIPCION, F.CLIENTE_ID FROM HFICTEC F, LFS L
                  WHERE F.EMPRESA = L.EMPRESA
                    AND F.MATBASE = L.COD_LFS
                  UNION
                  SELECT F.EMPRESA, F.TIP_ARTI, F.PRODUCTO, F.MODI, F.REVI, F.ANCHO, F.LARGO, F.MATBASE, L.FCKG, L.DESCRIPCION, F.CLIENTE_ID FROM FIC_SEGESTI F, LFS L
                  WHERE F.EMPRESA = L.EMPRESA
                    AND F.MATBASE = L.COD_LFS
                 ) FI,
                 (SELECT C.EMPRESA, C.CLIENTE_ID, C.RAZON_SOC, C.PAIS, P.NOMBRE, M.CLDESC MERCADO FROM CLIENTES C, GNR_PAISES P, FV_ASMATA20 M WHERE C.PAIS = P.PAIS AND C.TIPOPCLI = M.CLCLAS) C
            WHERE F.EMCODI = FA.EMCODI
              AND F.DICODI = FA.DICODI
              AND F.ASCANA = FA.ASCANA
              AND F.PPTIPO = FA.PPTIPO
              AND F.CFNROF = FA.CFNROF
				  --
              AND F.EMCODI = L.EMCODI
              AND F.DICODI = L.DICODI
              AND F.ASCANA = L.ASCANA
              AND F.CFNROF = L.CFNROF
              AND F.CPNROP = L.CPNROP
              AND F.ALNROP = L.ALNROP
              AND L.EMCODI = O.EMPRESA
              AND L.ASLOTE = TO_CHAR(O.NUMERO)
              AND L.CPNROP = O.NUMEPEDI
              AND FI.EMPRESA = C.EMPRESA
              AND FI.CLIENTE_ID = C.CLIENTE_ID
              AND O.EMPRESA = P.EMPRESA
              AND O.NUMEPEDI = P.NUMEPEDI
              AND P.TIPOACCI = 'I'
              AND L.EMCODI = AL.EMCODI(+)
              AND L.ALNROP = AL.ALNROP(+)
              AND (F.VATCOD = P_Utilidad.F_ValoDeva('TIARFIF4') OR 
                   (F.VATCOD = P_Utilidad.F_ValoDeva('TIARGCF4') AND 
                    EXISTS (SELECT 'X' FROM VALORES_LISTA LH --Articulos tipo C de Horas
                            WHERE LH.CODIGO = 'GNR_ARTIHORA'
                              AND P_UTILIDAD.F_VALOCAMPO(LH.VALOR,'EMPRESA') = F.EMCODI 
                              AND P_UTILIDAD.F_VALOCAMPO(LH.VALOR,'TIP_ARTI') = F.VATCOD 
                              AND P_UTILIDAD.F_VALOCAMPO(LH.VALOR,'COD_ARTI') = F.ARCARF
                           )
                   )
                  )
              AND NVL(L.CFNROF,0) != 0
              --AND NOT EXISTS (SELECT 'X' FROM ANE_OBCOTRAZ T WHERE T.EMPRESA = L.EMCODI AND TO_CHAR(T.NUMERO_OT) = L.ASLOTE)
              AND F.PPTIPO NOT IN ('A','X','B','L','O') --A Abono Nacional, X Abono Exportacion, B Abono Mostrador, L Abono atipico Exp, O Abonos atipicos
              AND O.EMPRESA = FI.EMPRESA(+)
              AND O.TIP_ARTI = FI.TIP_ARTI(+)
              AND O.COD_ARTI = FI.PRODUCTO(+)
              AND NVL(O.MODI,0) = NVL(FI.MODI(+),0)
              AND NVL(O.REVI,0) = NVL(FI.REVI(+),0)
              AND AL.TRACOD = T.TRACOD(+)
              AND AL.MTTRAN = TR.TRANSPOR(+);
