--------------------------------------------------------
--  DDL for View ANE_MERMA_PLANIFICACION
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "ANALESTA"."ANE_MERMA_PLANIFICACION"
  ("EMPRESA", "N_CLIENTE", "CLIENTE", "OT", "FEC_CIERRE_OT", "TIPO_PRD", "ESPECIALIDAD", "LINEA", "LFS", "N_CAPAS_TOTALES", "ANCHO_CLIENTE", "N_DE_CORTES", "N_DE_VECES", "ANCHO_DE_PRODUCCION", "MM_MERMA_PLANIF_IZQ_OPTIMA", "MM_MERMA_PLANIF_DCHA_OPTIMA", "ARP", "ORIGEN_MP", "TIPO_MP", "COD_MP", "LFS_MP", "ANCHO_MP", "PEDIDO_O_LOTE_INTERNO_MP", "FECHA_ORIGEN_MP", "PROV_MP", "UNIDAD_MP_ORIGEN", "PRECIO_UNITARIO_MP_M2_COMPRAS", "PRECIO_UNITARIO_MP_M2_ALGORIT", "PRECIO_UNITARIO_MP_M2", "LOTE_CONSUMIDO", "TRAZA_P_UNITARIO_MP_M2_ALGORIT", "ML_MAQ_MP", "MERMA_REAL_M2_MP", "EUROS_MERMA_REAL_MP", "MERMA_OPTIMA_M2_MP", "EUROS_OPTIMA_REAL_MP", "EXCLUIDA") 
  AS 
  SELECT M.EMPRESA, M.CLIENTE N_CLIENTE, M.NOMBRE_DEL_CLIENTE CLIENTE, M.OT, M.FEC_CIERRE_OT, M.TIPO_PRD, M.ESPECIALIDAD, M.LINEA, M.LFS, 
			(SELECT COUNT(DISTINCT LFS.COD_LFS) FROM FIC_LINEOTRE LO, ARTICULO A, LFS 
			 WHERE LO.EMPRESA = A.EMPRESA 
			   AND LO.TIP_ARES = A.TIP_ARTI
				AND LO.COD_ARES = A.COD_ARTI
				AND A.EMPRESA = LFS.EMPRESA
				AND A.COD_LFS = LFS.COD_LFS
			   AND LO.EMPRESA = M.EMPRESA 
				AND LO.NUMERO = M.OT) N_CAPAS_TOTALES,
       M.ANCHO_ESPECIALIDAD ANCHO_CLIENTE, 
		 M.N_DE_CORTES,
		 M.N_DE_VECES,
		 M.ANCHO_DE_PRODUCCION,
       /*CASE WHEN M.FASE IS NULL THEN ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material(M.EMPRESA, M.OT, (SELECT MAX(LO.FASE) FROM FIC_LINEOTRE LO
																							   WHERE LO.EMPRESA = M.EMPRESA 
																								  AND LO.NUMERO = M.OT
																								  AND ((INSTR(LO.COD_ARES,'IMPRESORA') != 0) OR
																								       (INSTR(LO.COD_ARES,'CORTADORA') != 0) OR
																										 (INSTR(LO.COD_ARES,'LAMINADORA') != 0) OR
																										 (INSTR(LO.COD_ARES,'LAQUEADORA') != 0))))
            ELSE ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material(M.EMPRESA, M.OT, M.FASE)
            END N_DE_CORTES,
                                                                               
		 CASE WHEN M.FASE IS NULL THEN ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material_Exp_OT(M.EMPRESA, M.OT, (SELECT MAX(LO.FASE) FROM FIC_LINEOTRE LO
																							   WHERE LO.EMPRESA = M.EMPRESA 
																								  AND LO.NUMERO = M.OT
																								  AND ((INSTR(LO.COD_ARES,'IMPRESORA') != 0) OR
																								       (INSTR(LO.COD_ARES,'CORTADORA') != 0) OR
																										 (INSTR(LO.COD_ARES,'LAMINADORA') != 0) OR
																										 (INSTR(LO.COD_ARES,'LAQUEADORA') != 0))))
            ELSE ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material_Exp_OT(M.EMPRESA, M.OT, M.FASE)
            END N_DE_VECES,

		 CASE WHEN M.FASE IS NULL THEN ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material_Exp_OT(M.EMPRESA, M.OT, (SELECT MAX(LO.FASE) FROM FIC_LINEOTRE LO
																							   WHERE LO.EMPRESA = M.EMPRESA 
																								  AND LO.NUMERO = M.OT
																								  AND ((INSTR(LO.COD_ARES,'IMPRESORA') != 0) OR
																								       (INSTR(LO.COD_ARES,'CORTADORA') != 0) OR
																										 (INSTR(LO.COD_ARES,'LAMINADORA') != 0) OR
																										 (INSTR(LO.COD_ARES,'LAQUEADORA') != 0)))) * M.ANCHO_ESPECIALIDAD
            ELSE ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material_Exp_OT(M.EMPRESA, M.OT, M.FASE) * M.ANCHO_ESPECIALIDAD
            END ANCHO_DE_PRODUCCION,*/

       P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_Mermas_Planificacion_Optima(M.EMPRESA, M.OT),'IZQUIER') MM_MERMA_PLANIF_IZQ_OPTIMA,
       P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_Mermas_Planificacion_Optima(M.EMPRESA, M.OT),'DERECHA') MM_MERMA_PLANIF_DCHA_OPTIMA,
       --
		 M.ARP,
		 /*CASE WHEN M.FASE IS NULL THEN (ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material_Exp_OT(M.EMPRESA, M.OT, (SELECT MAX(LO.FASE) FROM FIC_LINEOTRE LO
																							   WHERE LO.EMPRESA = M.EMPRESA 
																								  AND LO.NUMERO = M.OT
																								  AND ((INSTR(LO.COD_ARES,'IMPRESORA') != 0) OR
																								       (INSTR(LO.COD_ARES,'CORTADORA') != 0) OR
																										 (INSTR(LO.COD_ARES,'LAMINADORA') != 0) OR
																										 (INSTR(LO.COD_ARES,'LAQUEADORA') != 0)))) * M.ANCHO_ESPECIALIDAD) + NVL(TO_NUMBER(P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_Mermas_Planificacion_Optima(M.EMPRESA, M.OT),'IZQUIER')),0) + NVL(TO_NUMBER(P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_Mermas_Planificacion_Optima(M.EMPRESA, M.OT),'DERECHA')),0) --NVL(M.IZQUIERD,0) + NVL(M.DERECHA,0)
            ELSE (ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material_Exp_OT(M.EMPRESA, M.OT, M.FASE) * M.ANCHO_ESPECIALIDAD) + NVL(TO_NUMBER(P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_Mermas_Planificacion_Optima(M.EMPRESA, M.OT),'IZQUIER')),0) + NVL(TO_NUMBER(P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_Mermas_Planificacion_Optima(M.EMPRESA, M.OT),'DERECHA')),0) --NVL(M.IZQUIERD,0) + NVL(M.DERECHA,0)
            END ARP,*/

		 CASE WHEN TRIM(M.PEDIDO) IS NOT NULL THEN 'C'
          WHEN TRIM(M.PEDIDO_TM) IS NOT NULL THEN 'T'
          WHEN TRIM(M.FECHA_CIERRE_OT_SEMIELABORADO) IS NOT NULL THEN 'P'
          ELSE 'O' 
          END ORIGEN_MP,

		 M.TIPO TIPO_MP, M.COD_MP, M.LFS_MP,
--LFS_MP       
       M.ANCHO ANCHO_MP, 
		 
		 CASE WHEN TRIM(M.PEDIDO) IS NOT NULL THEN TO_CHAR(M.PEDIDO)
		      WHEN TRIM(M.PEDIDO_TM) IS NOT NULL THEN TO_CHAR(M.PEDIDO_TM)
		      WHEN TRIM(M.FECHA_CIERRE_OT_SEMIELABORADO) IS NOT NULL THEN M.LOTE
          ELSE NULL 
          END PEDIDO_O_LOTE_INTERNO_MP,
		 
		 CASE WHEN TRIM(M.PEDIDO) IS NOT NULL THEN M.FECHA_RECEPCION
          WHEN TRIM(M.PEDIDO_TM) IS NOT NULL THEN M.FECHRECE_TM
		      WHEN TRIM(M.FECHA_CIERRE_OT_SEMIELABORADO) IS NOT NULL THEN M.FECHA_CIERRE_OT_SEMIELABORADO
          ELSE M.FECHA_ENTRADA_ALMACEN 
          END FECHA_ORIGEN_MP,
		 
		 CASE WHEN TRIM(M.PEDIDO) IS NOT NULL THEN M.PROV
          WHEN TRIM(M.PEDIDO_TM) IS NOT NULL THEN M.PROVEEDO_TM
          WHEN TRIM(M.FECHA_CIERRE_OT_SEMIELABORADO) IS NOT NULL THEN 'EN'
          ELSE NULL
          END PROV_MP,
       
       CASE WHEN TRIM(M.PEDIDO) IS NOT NULL THEN M.UNIDAD_COMPRADA
            WHEN TRIM(M.FECHA_CIERRE_OT_SEMIELABORADO) IS NOT NULL THEN P_Utilidad.F_ValoDeva('TIPOUNML')
            ELSE P_Utilidad.F_ValoDeva('TIPOUNM2')
            END UNIDAD_MP_ORIGEN,
       
       M.PRECIO_COMPRA_CALCULADO PRECIO_UNITARIO_MP_M2_COMPRAS, 
       P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_PRECIO(M.EMPRESA,M.TIPO,M.COD_MP,M.FEC_MODI),'PRECIO') PRECIO_UNITARIO_MP_M2_ALGORIT, 
       DECODE(NVL(M.PRECIO_COMPRA_CALCULADO,0),0,P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_PRECIO(M.EMPRESA,M.TIPO,M.COD_MP,M.FEC_MODI),'PRECIO'),M.PRECIO_COMPRA_CALCULADO) PRECIO_UNITARIO_MP_M2,
       
       M.LOTE LOTE_CONSUMIDO,
		 
       P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_PRECIO(M.EMPRESA,M.TIPO,M.COD_MP,M.FEC_MODI),'TRAZA') TRAZA_P_UNITARIO_MP_M2_ALGORIT,
       
       SUM(M.CANTIDAD_CONSUMIDA) ML_MAQ_MP,
		 SUM(M.MERMA_REAL_M2_MP) MERMA_REAL_M2_MP,
		 SUM(EUROS_MERMA_REAL_MP) EUROS_MERMA_REAL_MP,
		 SUM(MERMA_OPTIMA_M2_MP) MERMA_OPTIMA_M2_MP,
		 SUM(EUROS_OPTIMA_REAL_MP) EUROS_OPTIMA_REAL_MP,
       
       /*CASE WHEN M.FASE IS NULL THEN (SUM(M.CANTIDAD_CONSUMIDA) *((M.ANCHO - (ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material_Exp_OT(M.EMPRESA, M.OT, 
                                                                        (SELECT MAX(LO.FASE) FROM FIC_LINEOTRE LO
																							   WHERE LO.EMPRESA = M.EMPRESA 
																								  AND LO.NUMERO = M.OT
																								  AND ((INSTR(LO.COD_ARES,'IMPRESORA') != 0) OR
																								       (INSTR(LO.COD_ARES,'CORTADORA') != 0) OR
																										 (INSTR(LO.COD_ARES,'LAMINADORA') != 0) OR
																										 (INSTR(LO.COD_ARES,'LAQUEADORA') != 0)))) * M.ANCHO_ESPECIALIDAD)) / 1000))--ANCHO PRODUCCION
            ELSE (SUM(M.CANTIDAD_CONSUMIDA) *((M.ANCHO - (ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material_Exp_OT(M.EMPRESA, M.OT, M.FASE) * M.ANCHO_ESPECIALIDAD)) / 1000))--ANCHO PRODUCCION
            END MERMA_REAL_M2_MP,

       CASE WHEN M.FASE IS NULL THEN (SUM(M.CANTIDAD_CONSUMIDA) *((M.ANCHO - (ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material_Exp_OT(M.EMPRESA, M.OT, 
                                                                        (SELECT MAX(LO.FASE) FROM FIC_LINEOTRE LO
																							   WHERE LO.EMPRESA = M.EMPRESA 
																								  AND LO.NUMERO = M.OT
																								  AND ((INSTR(LO.COD_ARES,'IMPRESORA') != 0) OR
																								       (INSTR(LO.COD_ARES,'CORTADORA') != 0) OR
																										 (INSTR(LO.COD_ARES,'LAMINADORA') != 0) OR
																										 (INSTR(LO.COD_ARES,'LAQUEADORA') != 0)))) * M.ANCHO_ESPECIALIDAD)) / 1000) * --ANCHO PRODUCCION
       DECODE(NVL(M.PRECIO_COMPRA_CALCULADO,0),0,P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_PRECIO(M.EMPRESA,M.TIPO,M.COD_MP,M.FEC_MODI),'PRECIO'),M.PRECIO_COMPRA_CALCULADO))
            ELSE (SUM(M.CANTIDAD_CONSUMIDA) *((M.ANCHO - (ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material_Exp_OT(M.EMPRESA, M.OT, M.FASE) * M.ANCHO_ESPECIALIDAD)) / 1000) * --ANCHO PRODUCCION
       DECODE(NVL(M.PRECIO_COMPRA_CALCULADO,0),0,P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_PRECIO(M.EMPRESA,M.TIPO,M.COD_MP,M.FEC_MODI),'PRECIO'),M.PRECIO_COMPRA_CALCULADO))
            END EUROS_MERMA_REAL_MP,

       
       CASE WHEN M.FASE IS NULL THEN (SUM(M.CANTIDAD_CONSUMIDA) *(((ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material_Exp_OT(M.EMPRESA, M.OT, (SELECT MAX(LO.FASE) FROM FIC_LINEOTRE LO
																							   WHERE LO.EMPRESA = M.EMPRESA 
																								  AND LO.NUMERO = M.OT
																								  AND ((INSTR(LO.COD_ARES,'IMPRESORA') != 0) OR
																								       (INSTR(LO.COD_ARES,'CORTADORA') != 0) OR
																										 (INSTR(LO.COD_ARES,'LAMINADORA') != 0) OR
																										 (INSTR(LO.COD_ARES,'LAQUEADORA') != 0)))) * M.ANCHO_ESPECIALIDAD) + NVL(TO_NUMBER(P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_Mermas_Planificacion_Optima(M.EMPRESA, M.OT),'IZQUIER')),0) + NVL(TO_NUMBER(P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_Mermas_Planificacion_Optima(M.EMPRESA, M.OT),'DERECHA')),0) - --NVL(M.IZQUIERD,0) + NVL(M.DERECHA,0) - --ARP
                                    (ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material_Exp_OT(M.EMPRESA, M.OT, 
                                                                        (SELECT MAX(LO.FASE) FROM FIC_LINEOTRE LO
																							   WHERE LO.EMPRESA = M.EMPRESA 
																								  AND LO.NUMERO = M.OT
																								  AND ((INSTR(LO.COD_ARES,'IMPRESORA') != 0) OR
																								       (INSTR(LO.COD_ARES,'CORTADORA') != 0) OR
																										 (INSTR(LO.COD_ARES,'LAMINADORA') != 0) OR
																										 (INSTR(LO.COD_ARES,'LAQUEADORA') != 0)))) * M.ANCHO_ESPECIALIDAD)) / 1000))--ANCHO PRODUCCION
            ELSE (SUM(M.CANTIDAD_CONSUMIDA) *(((ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material_Exp_OT(M.EMPRESA, M.OT, M.FASE) * M.ANCHO_ESPECIALIDAD) + NVL(TO_NUMBER(P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_Mermas_Planificacion_Optima(M.EMPRESA, M.OT),'IZQUIER')),0) + NVL(TO_NUMBER(P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_Mermas_Planificacion_Optima(M.EMPRESA, M.OT),'DERECHA')),0) - --NVL(M.IZQUIERD,0) + NVL(M.DERECHA,0) - --ARP
                                    (ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material_Exp_OT(M.EMPRESA, M.OT, M.FASE) * M.ANCHO_ESPECIALIDAD)) / 1000))--ANCHO PRODUCCION
            END MERMA_OPTIMA_M2_MP,

       CASE WHEN M.FASE IS NULL THEN (SUM(M.CANTIDAD_CONSUMIDA) *(((ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material_Exp_OT(M.EMPRESA, M.OT, (SELECT MAX(LO.FASE) FROM FIC_LINEOTRE LO
																							   WHERE LO.EMPRESA = M.EMPRESA 
																								  AND LO.NUMERO = M.OT
																								  AND ((INSTR(LO.COD_ARES,'IMPRESORA') != 0) OR
																								       (INSTR(LO.COD_ARES,'CORTADORA') != 0) OR
																										 (INSTR(LO.COD_ARES,'LAMINADORA') != 0) OR
																										 (INSTR(LO.COD_ARES,'LAQUEADORA') != 0)))) * M.ANCHO_ESPECIALIDAD) + NVL(TO_NUMBER(P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_Mermas_Planificacion_Optima(M.EMPRESA, M.OT),'IZQUIER')),0) + NVL(TO_NUMBER(P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_Mermas_Planificacion_Optima(M.EMPRESA, M.OT),'DERECHA')),0) - --NVL(M.IZQUIERD,0) + NVL(M.DERECHA,0) - --ARP
                                    (ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material_Exp_OT(M.EMPRESA, M.OT, 
                                                                        (SELECT MAX(LO.FASE) FROM FIC_LINEOTRE LO
																							   WHERE LO.EMPRESA = M.EMPRESA 
																								  AND LO.NUMERO = M.OT
																								  AND ((INSTR(LO.COD_ARES,'IMPRESORA') != 0) OR
																								       (INSTR(LO.COD_ARES,'CORTADORA') != 0) OR
																										 (INSTR(LO.COD_ARES,'LAMINADORA') != 0) OR
																										 (INSTR(LO.COD_ARES,'LAQUEADORA') != 0)))) * M.ANCHO_ESPECIALIDAD)) / 1000) * --ANCHO PRODUCCION
       DECODE(NVL(M.PRECIO_COMPRA_CALCULADO,0),0,P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_PRECIO(M.EMPRESA,M.TIPO,M.COD_MP,M.FEC_MODI),'PRECIO'),M.PRECIO_COMPRA_CALCULADO))
            ELSE (SUM(M.CANTIDAD_CONSUMIDA) *(((ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material_Exp_OT(M.EMPRESA, M.OT, M.FASE) * M.ANCHO_ESPECIALIDAD) + NVL(TO_NUMBER(P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_Mermas_Planificacion_Optima(M.EMPRESA, M.OT),'IZQUIER')),0) + NVL(TO_NUMBER(P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_Mermas_Planificacion_Optima(M.EMPRESA, M.OT),'DERECHA')),0) - --NVL(M.IZQUIERD,0) + NVL(M.DERECHA,0) - --ARP
                                    (ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material_Exp_OT(M.EMPRESA, M.OT, M.FASE) * M.ANCHO_ESPECIALIDAD)) / 1000) * --ANCHO PRODUCCION
       DECODE(NVL(M.PRECIO_COMPRA_CALCULADO,0),0,P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_PRECIO(M.EMPRESA,M.TIPO,M.COD_MP,M.FEC_MODI),'PRECIO'),M.PRECIO_COMPRA_CALCULADO))
            END EUROS_OPTIMA_REAL_MP,*/

       ANALESTA.P_ANE_MERMLAMI_PRAG.F_Verifica_Ot(M.EMPRESA, M.OT, M.NUMEPEDI) EXCLUIDA
FROM (
SELECT O.EMPRESA, AO.CLIENASOC CLIENTE, C.RAZON_SOC NOMBRE_DEL_CLIENTE, O.NUMERO OT, M.TIP_ARTI TIPO, M.COD_ARTI COD_MP, A.ANCHO,
       (SELECT C.PCNROP FROM FV_ASCOAL02 C WHERE C.EMCODI = M.EMPRESA AND C.VATCOD = M.TIP_ARTI AND C.ARCARF = M.COD_ARTI AND C.ASLOTE = M.LOTE AND (C.VATCOD != P_UTILIDAD.F_VALODEVA('TIARMPF4') OR (C.VATCOD = P_UTILIDAD.F_VALODEVA('TIARMPF4') AND C.VNACOD IN ('1','43','16','46'))) AND ROWNUM = 1) PEDIDO,
       (SELECT C.NUMEPECO FROM FIC_ENMAMATE C WHERE C.EMPRESA = M.EMPRESA AND C.TIP_ARTI = M.TIP_ARTI AND C.COD_ARTI = M.COD_ARTI AND C.LOTE = M.LOTE AND ROWNUM = 1) PEDIDO_TM,
       (SELECT C.FECHRECE FROM FIC_ENMAMATE C WHERE C.EMPRESA = M.EMPRESA AND C.TIP_ARTI = M.TIP_ARTI AND C.COD_ARTI = M.COD_ARTI AND C.LOTE = M.LOTE AND ROWNUM = 1) FECHRECE_TM,
       (SELECT C.PROVEEDO FROM FIC_ENMAMATE C WHERE C.EMPRESA = M.EMPRESA AND C.TIP_ARTI = M.TIP_ARTI AND C.COD_ARTI = M.COD_ARTI AND C.LOTE = M.LOTE AND ROWNUM = 1) PROVEEDO_TM,
		 
		 (SELECT MIN(H.AHFMOV) AHFMOV FROM FV_ASALHI01 H WHERE H.EMCODI = M.EMPRESA AND H.VATCOD = M.TIP_ARTI AND H.ARCARF = M.COD_ARTI AND H.ASLOTE = M.LOTE AND (H.VATCOD != P_UTILIDAD.F_VALODEVA('TIARMPF4') OR (H.VATCOD = P_UTILIDAD.F_VALODEVA('TIARMPF4') AND H.VNACOD IN ('1','43','16','46'))) AND H.AHTIMO = 'E') FECHA_ENTRADA_ALMACEN,
		 
       (SELECT C.MPCPRO FROM FV_ASCOAL02 C WHERE C.EMCODI = M.EMPRESA AND C.VATCOD = M.TIP_ARTI AND C.ARCARF = M.COD_ARTI AND C.ASLOTE = M.LOTE AND (C.VATCOD != P_UTILIDAD.F_VALODEVA('TIARMPF4') OR (C.VATCOD = P_UTILIDAD.F_VALODEVA('TIARMPF4') AND C.VNACOD IN ('1','43','16','46'))) AND ROWNUM = 1) PROV,
		 /*
       (SELECT C.ALUNST FROM FV_ASCOAL02 C WHERE C.EMCODI = M.EMPRESA AND C.VATCOD = M.TIP_ARTI AND C.ARCARF = M.COD_ARTI AND C.ASLOTE = M.LOTE AND (C.VATCOD != P_UTILIDAD.F_VALODEVA('TIARMPF4') OR (C.VATCOD = P_UTILIDAD.F_VALODEVA('TIARMPF4') AND C.VNACOD IN ('1','43','16','46'))) AND ROWNUM = 1) UNIDAD_STOCK_EN_COMPRA,*/
		 
       (SELECT C.ALUNCO FROM FV_ASCOAL02 C WHERE C.EMCODI = M.EMPRESA AND C.VATCOD = M.TIP_ARTI AND C.ARCARF = M.COD_ARTI AND C.ASLOTE = M.LOTE AND (C.VATCOD != P_UTILIDAD.F_VALODEVA('TIARMPF4') OR (C.VATCOD = P_UTILIDAD.F_VALODEVA('TIARMPF4') AND C.VNACOD IN ('1','43','16','46'))) AND ROWNUM = 1) UNIDAD_COMPRADA,
		 
       M.LOTE,
		 
       (SELECT CA.ACFENT FROM FV_ASCOAL02 C, FV_ASCOAL01 CA 
        WHERE C.EMCODI = M.EMPRESA AND C.VATCOD = M.TIP_ARTI AND C.ARCARF = M.COD_ARTI AND C.ASLOTE = M.LOTE 
          AND CA.EMCODI = C.EMCODI AND CA.DICODI = C.DICODI AND CA.ACANYA = C.ACANYA AND CA.ACNROA = C.ACNROA AND CA.TIPDOC IS NULL
          AND (C.VATCOD != P_UTILIDAD.F_VALODEVA('TIARMPF4') OR (C.VATCOD = P_UTILIDAD.F_VALODEVA('TIARMPF4') AND C.VNACOD IN ('1','43','16','46')))
          AND ROWNUM = 1) FECHA_RECEPCION, 
			 
       DECODE(M.TIP_ARTI,P_UTILIDAD.F_VALODEVA('TIARSEF4'),(SELECT OS.FEC_MODI FROM FIC_CABEOTRE OS WHERE OS.EMPRESA = M.EMPRESA AND TO_CHAR(OS.NUMERO) = M.LOTE AND OS.TIP_ARTI = M.TIP_ARTI AND OS.COD_ARTI = M.COD_ARTI AND OS.SITUACIO = 'C')) FECHA_CIERRE_OT_SEMIELABORADO,
		 /*
       (SELECT C.ALCANT FROM FV_ASCOAL02 C WHERE C.EMCODI = M.EMPRESA AND C.VATCOD = M.TIP_ARTI AND C.ARCARF = M.COD_ARTI AND C.ASLOTE = M.LOTE AND (C.VATCOD != P_UTILIDAD.F_VALODEVA('TIARMPF4') OR (C.VATCOD = P_UTILIDAD.F_VALODEVA('TIARMPF4') AND C.VNACOD IN ('1','43','16','46'))) AND ROWNUM = 1) CANTIDAD_COMPRA,
       (SELECT C.ALCAEQ FROM FV_ASCOAL02 C WHERE C.EMCODI = M.EMPRESA AND C.VATCOD = M.TIP_ARTI AND C.ARCARF = M.COD_ARTI AND C.ASLOTE = M.LOTE AND (C.VATCOD != P_UTILIDAD.F_VALODEVA('TIARMPF4') OR (C.VATCOD = P_UTILIDAD.F_VALODEVA('TIARMPF4') AND C.VNACOD IN ('1','43','16','46'))) AND ROWNUM = 1) CANTIDAD_EQUIVALENTE,*/
		 /*
       (SELECT C.ALPREU FROM FV_ASCOAL02 C WHERE C.EMCODI = M.EMPRESA AND C.VATCOD = M.TIP_ARTI AND C.ARCARF = M.COD_ARTI AND C.ASLOTE = M.LOTE AND (C.VATCOD != P_UTILIDAD.F_VALODEVA('TIARMPF4') OR (C.VATCOD = P_UTILIDAD.F_VALODEVA('TIARMPF4') AND C.VNACOD IN ('1','43','16','46'))) AND ROWNUM = 1) PRECIO_COMPRA,
       (SELECT C.DIVISA FROM FV_ASCOAL02 C WHERE C.EMCODI = M.EMPRESA AND C.VATCOD = M.TIP_ARTI AND C.ARCARF = M.COD_ARTI AND C.ASLOTE = M.LOTE AND (C.VATCOD != P_UTILIDAD.F_VALODEVA('TIARMPF4') OR (C.VATCOD = P_UTILIDAD.F_VALODEVA('TIARMPF4') AND C.VNACOD IN ('1','43','16','46'))) AND ROWNUM = 1) DIVISA,*/
       (
         SELECT DECODE(C.ALUNST,P_Utilidad.F_ValoDeva('TIPOUNM2'),DECODE(C.ALUPRE,0,DECODE(C.ALCANT, 0, 0,((C.ALPREU * D.CAMBIO) * C.ALCAEQ) / C.ALCANT),
                                                                  DECODE(C.ALCANT, 0, 0,(((C.ALPREU * D.CAMBIO) * C.ALCAEQ) / C.ALCANT) / C.ALUPRE) 
                      ))ALPREU  
         FROM FV_ASCOAL02 C, GNR_DICOTIZA D, FV_ASCOAL01 CA
            WHERE CA.EMCODI = C.EMCODI
              AND CA.DICODI = C.DICODI
              AND CA.ACANYA = C.ACANYA
              AND CA.ACNROA = C.ACNROA
              AND CA.TIPDOC IS NULL
              AND C.DIVISA = D.DIVISA
              AND D.DIVISAMA = P_UTILIDAD.F_VALODEVA('DIVIEURO')
              AND TRUNC(C.ACFENT) BETWEEN TRUNC(DESDFECH) AND TRUNC(HASTFECH)
              AND (C.VATCOD != P_UTILIDAD.F_VALODEVA('TIARMPF4') OR (C.VATCOD = P_UTILIDAD.F_VALODEVA('TIARMPF4') AND C.VNACOD IN ('1','43','16','46')))
              AND C.EMCODI = M.EMPRESA
              AND C.VATCOD = M.TIP_ARTI
              AND C.ARCARF = M.COD_ARTI
              AND C.ASLOTE = M.LOTE
              AND ROWNUM = 1) PRECIO_COMPRA_CALCULADO,
      M.CANTCONS CANTIDAD_CONSUMIDA, A.FCKG, O.FEC_MODI, 
		DECODE(O.SITUACIO,'C',O.FEC_MODI) FEC_CIERRE_OT, O.TIP_ARTI TIPO_PRD, O.COD_ARTI ESPECIALIDAD, SUBSTR(AO.COD_LFS,1,2) LINEA, AO.COD_LFS LFS, AO.ANCHO ANCHO_ESPECIALIDAD, O.NUMEPEDI, 
      --MP.IZQUIERD, MP.DERECHA, 
      A.COD_LFS LFS_MP, MP.FASE, 
      MP.FASEBUMP,
		
---------------------------------------------------------------------------------------------------
       CASE WHEN MP.FASE IS NULL THEN ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material(O.EMPRESA, O.NUMERO, (SELECT MAX(LO.FASE) FROM FIC_LINEOTRE LO
																							   WHERE LO.EMPRESA = O.EMPRESA 
																								  AND LO.NUMERO = O.NUMERO
																								  AND ((INSTR(LO.COD_ARES,'IMPRESORA') != 0) OR
																								       (INSTR(LO.COD_ARES,'CORTADORA') != 0) OR
																										 (INSTR(LO.COD_ARES,'LAMINADORA') != 0) OR
																										 (INSTR(LO.COD_ARES,'LAQUEADORA') != 0))))
            ELSE ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material(O.EMPRESA, O.NUMERO, MP.FASE)
            END N_DE_CORTES,
                                                                               
		 CASE WHEN MP.FASE IS NULL THEN ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material_Exp_OT(O.EMPRESA, O.NUMERO, (SELECT MAX(LO.FASE) FROM FIC_LINEOTRE LO
																							   WHERE LO.EMPRESA = O.EMPRESA 
																								  AND LO.NUMERO = O.NUMERO
																								  AND ((INSTR(LO.COD_ARES,'IMPRESORA') != 0) OR
																								       (INSTR(LO.COD_ARES,'CORTADORA') != 0) OR
																										 (INSTR(LO.COD_ARES,'LAMINADORA') != 0) OR
																										 (INSTR(LO.COD_ARES,'LAQUEADORA') != 0))))
            ELSE ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material_Exp_OT(O.EMPRESA, O.NUMERO, MP.FASE)
            END N_DE_VECES,

		 CASE WHEN MP.FASE IS NULL THEN ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material_Exp_OT(O.EMPRESA, O.NUMERO, (SELECT MAX(LO.FASE) FROM FIC_LINEOTRE LO
																							   WHERE LO.EMPRESA = O.EMPRESA 
																								  AND LO.NUMERO = O.NUMERO
																								  AND ((INSTR(LO.COD_ARES,'IMPRESORA') != 0) OR
																								       (INSTR(LO.COD_ARES,'CORTADORA') != 0) OR
																										 (INSTR(LO.COD_ARES,'LAMINADORA') != 0) OR
																										 (INSTR(LO.COD_ARES,'LAQUEADORA') != 0)))) * AO.ANCHO
            ELSE ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material_Exp_OT(O.EMPRESA, O.NUMERO, MP.FASE) * AO.ANCHO
            END ANCHO_DE_PRODUCCION,
		 CASE WHEN MP.FASE IS NULL THEN (ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material_Exp_OT(O.EMPRESA, O.NUMERO, (SELECT MAX(LO.FASE) FROM FIC_LINEOTRE LO
																							   WHERE LO.EMPRESA = O.EMPRESA 
																								  AND LO.NUMERO = O.NUMERO
																								  AND ((INSTR(LO.COD_ARES,'IMPRESORA') != 0) OR
																								       (INSTR(LO.COD_ARES,'CORTADORA') != 0) OR
																										 (INSTR(LO.COD_ARES,'LAMINADORA') != 0) OR
																										 (INSTR(LO.COD_ARES,'LAQUEADORA') != 0)))) * AO.ANCHO) + NVL(TO_NUMBER(P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_Mermas_Planificacion_Optima(O.EMPRESA, O.NUMERO),'IZQUIER')),0) + NVL(TO_NUMBER(P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_Mermas_Planificacion_Optima(O.EMPRESA, O.NUMERO),'DERECHA')),0) --NVL(M.IZQUIERD,0) + NVL(M.DERECHA,0)
            ELSE (ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material_Exp_OT(O.EMPRESA, O.NUMERO, MP.FASE) * AO.ANCHO) + NVL(TO_NUMBER(P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_Mermas_Planificacion_Optima(O.EMPRESA, O.NUMERO),'IZQUIER')),0) + NVL(TO_NUMBER(P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_Mermas_Planificacion_Optima(O.EMPRESA, O.NUMERO),'DERECHA')),0) --NVL(M.IZQUIERD,0) + NVL(M.DERECHA,0)
            END ARP,
------------
       CASE WHEN MP.FASE IS NULL THEN (/*SUM(*/M.CANTCONS/*)*/ *((A.ANCHO - (ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material_Exp_OT(O.EMPRESA, O.NUMERO, 
                                                                        (SELECT MAX(LO.FASE) FROM FIC_LINEOTRE LO
																							   WHERE LO.EMPRESA = O.EMPRESA 
																								  AND LO.NUMERO = O.NUMERO
																								  AND ((INSTR(LO.COD_ARES,'IMPRESORA') != 0) OR
																								       (INSTR(LO.COD_ARES,'CORTADORA') != 0) OR
																										 (INSTR(LO.COD_ARES,'LAMINADORA') != 0) OR
																										 (INSTR(LO.COD_ARES,'LAQUEADORA') != 0)))) * AO.ANCHO)) / 1000))--ANCHO PRODUCCION
            ELSE (/*SUM(*/M.CANTCONS/*)*/ *((A.ANCHO - (ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material_Exp_OT(O.EMPRESA, O.NUMERO, MP.FASE) * AO.ANCHO)) / 1000))--ANCHO PRODUCCION
            END MERMA_REAL_M2_MP,

       CASE WHEN MP.FASE IS NULL THEN (/*SUM(*/M.CANTCONS/*)*/ *((A.ANCHO - (ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material_Exp_OT(O.EMPRESA, O.NUMERO, 
                                                                        (SELECT MAX(LO.FASE) FROM FIC_LINEOTRE LO
																							   WHERE LO.EMPRESA = O.EMPRESA 
																								  AND LO.NUMERO = O.NUMERO
																								  AND ((INSTR(LO.COD_ARES,'IMPRESORA') != 0) OR
																								       (INSTR(LO.COD_ARES,'CORTADORA') != 0) OR
																										 (INSTR(LO.COD_ARES,'LAMINADORA') != 0) OR
																										 (INSTR(LO.COD_ARES,'LAQUEADORA') != 0)))) * AO.ANCHO)) / 1000) * --ANCHO PRODUCCION
       DECODE(NVL(
					  (SELECT DECODE(C.ALUNST,P_Utilidad.F_ValoDeva('TIPOUNM2'),DECODE(C.ALUPRE,0,DECODE(C.ALCANT, 0, 0,((C.ALPREU * D.CAMBIO) * C.ALCAEQ) / C.ALCANT),
																									DECODE(C.ALCANT, 0, 0,(((C.ALPREU * D.CAMBIO) * C.ALCAEQ) / C.ALCANT) / C.ALUPRE) 
										 ))ALPREU  
						FROM FV_ASCOAL02 C, GNR_DICOTIZA D, FV_ASCOAL01 CA
							WHERE CA.EMCODI = C.EMCODI
							  AND CA.DICODI = C.DICODI
							  AND CA.ACANYA = C.ACANYA
							  AND CA.ACNROA = C.ACNROA
							  AND CA.TIPDOC IS NULL
							  AND C.DIVISA = D.DIVISA
							  AND D.DIVISAMA = P_UTILIDAD.F_VALODEVA('DIVIEURO')
							  AND TRUNC(C.ACFENT) BETWEEN TRUNC(DESDFECH) AND TRUNC(HASTFECH)
							  AND (C.VATCOD != P_UTILIDAD.F_VALODEVA('TIARMPF4') OR (C.VATCOD = P_UTILIDAD.F_VALODEVA('TIARMPF4') AND C.VNACOD IN ('1','43','16','46')))
							  AND C.EMCODI = M.EMPRESA
							  AND C.VATCOD = M.TIP_ARTI
							  AND C.ARCARF = M.COD_ARTI
							  AND C.ASLOTE = M.LOTE
							  AND ROWNUM = 1)--M.PRECIO_COMPRA_CALCULADO
				  ,0),0,P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_PRECIO(M.EMPRESA,M.TIP_ARTI,M.COD_ARTI,O.FEC_MODI),'PRECIO'),
				  (SELECT DECODE(C.ALUNST,P_Utilidad.F_ValoDeva('TIPOUNM2'),DECODE(C.ALUPRE,0,DECODE(C.ALCANT, 0, 0,((C.ALPREU * D.CAMBIO) * C.ALCAEQ) / C.ALCANT),
																									DECODE(C.ALCANT, 0, 0,(((C.ALPREU * D.CAMBIO) * C.ALCAEQ) / C.ALCANT) / C.ALUPRE) 
										 ))ALPREU  
						FROM FV_ASCOAL02 C, GNR_DICOTIZA D, FV_ASCOAL01 CA
							WHERE CA.EMCODI = C.EMCODI
							  AND CA.DICODI = C.DICODI
							  AND CA.ACANYA = C.ACANYA
							  AND CA.ACNROA = C.ACNROA
							  AND CA.TIPDOC IS NULL
							  AND C.DIVISA = D.DIVISA
							  AND D.DIVISAMA = P_UTILIDAD.F_VALODEVA('DIVIEURO')
							  AND TRUNC(C.ACFENT) BETWEEN TRUNC(DESDFECH) AND TRUNC(HASTFECH)
							  AND (C.VATCOD != P_UTILIDAD.F_VALODEVA('TIARMPF4') OR (C.VATCOD = P_UTILIDAD.F_VALODEVA('TIARMPF4') AND C.VNACOD IN ('1','43','16','46')))
							  AND C.EMCODI = M.EMPRESA
							  AND C.VATCOD = M.TIP_ARTI
							  AND C.ARCARF = M.COD_ARTI
							  AND C.ASLOTE = M.LOTE
							  AND ROWNUM = 1)--M.PRECIO_COMPRA_CALCULADO
				  ))
            ELSE (/*SUM(*/M.CANTCONS/*)*/ *((A.ANCHO - (ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material_Exp_OT(O.EMPRESA, O.NUMERO, MP.FASE) * AO.ANCHO)) / 1000) * --ANCHO PRODUCCION
       DECODE(NVL(
		            (SELECT DECODE(C.ALUNST,P_Utilidad.F_ValoDeva('TIPOUNM2'),DECODE(C.ALUPRE,0,DECODE(C.ALCANT, 0, 0,((C.ALPREU * D.CAMBIO) * C.ALCAEQ) / C.ALCANT),
																									DECODE(C.ALCANT, 0, 0,(((C.ALPREU * D.CAMBIO) * C.ALCAEQ) / C.ALCANT) / C.ALUPRE) 
										 ))ALPREU  
						FROM FV_ASCOAL02 C, GNR_DICOTIZA D, FV_ASCOAL01 CA
							WHERE CA.EMCODI = C.EMCODI
							  AND CA.DICODI = C.DICODI
							  AND CA.ACANYA = C.ACANYA
							  AND CA.ACNROA = C.ACNROA
							  AND CA.TIPDOC IS NULL
							  AND C.DIVISA = D.DIVISA
							  AND D.DIVISAMA = P_UTILIDAD.F_VALODEVA('DIVIEURO')
							  AND TRUNC(C.ACFENT) BETWEEN TRUNC(DESDFECH) AND TRUNC(HASTFECH)
							  AND (C.VATCOD != P_UTILIDAD.F_VALODEVA('TIARMPF4') OR (C.VATCOD = P_UTILIDAD.F_VALODEVA('TIARMPF4') AND C.VNACOD IN ('1','43','16','46')))
							  AND C.EMCODI = M.EMPRESA
							  AND C.VATCOD = M.TIP_ARTI
							  AND C.ARCARF = M.COD_ARTI
							  AND C.ASLOTE = M.LOTE
							  AND ROWNUM = 1)--M.PRECIO_COMPRA_CALCULADO
				 ,0),0,P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_PRECIO(M.EMPRESA,M.TIP_ARTI,M.COD_ARTI,O.FEC_MODI),'PRECIO'),
				 (SELECT DECODE(C.ALUNST,P_Utilidad.F_ValoDeva('TIPOUNM2'),DECODE(C.ALUPRE,0,DECODE(C.ALCANT, 0, 0,((C.ALPREU * D.CAMBIO) * C.ALCAEQ) / C.ALCANT),
																									DECODE(C.ALCANT, 0, 0,(((C.ALPREU * D.CAMBIO) * C.ALCAEQ) / C.ALCANT) / C.ALUPRE) 
										 ))ALPREU  
						FROM FV_ASCOAL02 C, GNR_DICOTIZA D, FV_ASCOAL01 CA
							WHERE CA.EMCODI = C.EMCODI
							  AND CA.DICODI = C.DICODI
							  AND CA.ACANYA = C.ACANYA
							  AND CA.ACNROA = C.ACNROA
							  AND CA.TIPDOC IS NULL
							  AND C.DIVISA = D.DIVISA
							  AND D.DIVISAMA = P_UTILIDAD.F_VALODEVA('DIVIEURO')
							  AND TRUNC(C.ACFENT) BETWEEN TRUNC(DESDFECH) AND TRUNC(HASTFECH)
							  AND (C.VATCOD != P_UTILIDAD.F_VALODEVA('TIARMPF4') OR (C.VATCOD = P_UTILIDAD.F_VALODEVA('TIARMPF4') AND C.VNACOD IN ('1','43','16','46')))
							  AND C.EMCODI = M.EMPRESA
							  AND C.VATCOD = M.TIP_ARTI
							  AND C.ARCARF = M.COD_ARTI
							  AND C.ASLOTE = M.LOTE
							  AND ROWNUM = 1)--M.PRECIO_COMPRA_CALCULADO
				 ))
            END EUROS_MERMA_REAL_MP,

       
       CASE WHEN MP.FASE IS NULL THEN (/*SUM(*/M.CANTCONS/*)*/ *(((ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material_Exp_OT(O.EMPRESA, O.NUMERO, (SELECT MAX(LO.FASE) FROM FIC_LINEOTRE LO
																							   WHERE LO.EMPRESA = O.EMPRESA 
																								  AND LO.NUMERO = O.NUMERO
																								  AND ((INSTR(LO.COD_ARES,'IMPRESORA') != 0) OR
																								       (INSTR(LO.COD_ARES,'CORTADORA') != 0) OR
																										 (INSTR(LO.COD_ARES,'LAMINADORA') != 0) OR
																										 (INSTR(LO.COD_ARES,'LAQUEADORA') != 0)))) * AO.ANCHO) + NVL(TO_NUMBER(P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_Mermas_Planificacion_Optima(O.EMPRESA, O.NUMERO),'IZQUIER')),0) + NVL(TO_NUMBER(P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_Mermas_Planificacion_Optima(O.EMPRESA, O.NUMERO),'DERECHA')),0) - --NVL(M.IZQUIERD,0) + NVL(M.DERECHA,0) - --ARP
                                    (ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material_Exp_OT(O.EMPRESA, O.NUMERO, 
                                                                        (SELECT MAX(LO.FASE) FROM FIC_LINEOTRE LO
																							   WHERE LO.EMPRESA = O.EMPRESA 
																								  AND LO.NUMERO = O.NUMERO
																								  AND ((INSTR(LO.COD_ARES,'IMPRESORA') != 0) OR
																								       (INSTR(LO.COD_ARES,'CORTADORA') != 0) OR
																										 (INSTR(LO.COD_ARES,'LAMINADORA') != 0) OR
																										 (INSTR(LO.COD_ARES,'LAQUEADORA') != 0)))) * AO.ANCHO)) / 1000))--ANCHO PRODUCCION
            ELSE (/*SUM(*/M.CANTCONS/*)*/ *(((ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material_Exp_OT(O.EMPRESA, O.NUMERO, MP.FASE) * AO.ANCHO) + NVL(TO_NUMBER(P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_Mermas_Planificacion_Optima(O.EMPRESA, O.NUMERO),'IZQUIER')),0) + NVL(TO_NUMBER(P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_Mermas_Planificacion_Optima(O.EMPRESA, O.NUMERO),'DERECHA')),0) - --NVL(M.IZQUIERD,0) + NVL(M.DERECHA,0) - --ARP
                                    (ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material_Exp_OT(O.EMPRESA, O.NUMERO, MP.FASE) * AO.ANCHO)) / 1000))--ANCHO PRODUCCION
            END MERMA_OPTIMA_M2_MP,

       CASE WHEN MP.FASE IS NULL THEN (/*SUM(*/M.CANTCONS/*)*/ *(((ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material_Exp_OT(O.EMPRESA, O.NUMERO, (SELECT MAX(LO.FASE) FROM FIC_LINEOTRE LO
																							   WHERE LO.EMPRESA = O.EMPRESA 
																								  AND LO.NUMERO = O.NUMERO
																								  AND ((INSTR(LO.COD_ARES,'IMPRESORA') != 0) OR
																								       (INSTR(LO.COD_ARES,'CORTADORA') != 0) OR
																										 (INSTR(LO.COD_ARES,'LAMINADORA') != 0) OR
																										 (INSTR(LO.COD_ARES,'LAQUEADORA') != 0)))) * AO.ANCHO) + NVL(TO_NUMBER(P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_Mermas_Planificacion_Optima(O.EMPRESA, O.NUMERO),'IZQUIER')),0) + NVL(TO_NUMBER(P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_Mermas_Planificacion_Optima(O.EMPRESA, O.NUMERO),'DERECHA')),0) - --NVL(M.IZQUIERD,0) + NVL(M.DERECHA,0) - --ARP
                                    (ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material_Exp_OT(O.EMPRESA, O.NUMERO, 
                                                                        (SELECT MAX(LO.FASE) FROM FIC_LINEOTRE LO
																							   WHERE LO.EMPRESA = O.EMPRESA 
																								  AND LO.NUMERO = O.NUMERO
																								  AND ((INSTR(LO.COD_ARES,'IMPRESORA') != 0) OR
																								       (INSTR(LO.COD_ARES,'CORTADORA') != 0) OR
																										 (INSTR(LO.COD_ARES,'LAMINADORA') != 0) OR
																										 (INSTR(LO.COD_ARES,'LAQUEADORA') != 0)))) * AO.ANCHO)) / 1000) * --ANCHO PRODUCCION
       DECODE(NVL(
		            (SELECT DECODE(C.ALUNST,P_Utilidad.F_ValoDeva('TIPOUNM2'),DECODE(C.ALUPRE,0,DECODE(C.ALCANT, 0, 0,((C.ALPREU * D.CAMBIO) * C.ALCAEQ) / C.ALCANT),
																									DECODE(C.ALCANT, 0, 0,(((C.ALPREU * D.CAMBIO) * C.ALCAEQ) / C.ALCANT) / C.ALUPRE) 
										 ))ALPREU  
						FROM FV_ASCOAL02 C, GNR_DICOTIZA D, FV_ASCOAL01 CA
							WHERE CA.EMCODI = C.EMCODI
							  AND CA.DICODI = C.DICODI
							  AND CA.ACANYA = C.ACANYA
							  AND CA.ACNROA = C.ACNROA
							  AND CA.TIPDOC IS NULL
							  AND C.DIVISA = D.DIVISA
							  AND D.DIVISAMA = P_UTILIDAD.F_VALODEVA('DIVIEURO')
							  AND TRUNC(C.ACFENT) BETWEEN TRUNC(DESDFECH) AND TRUNC(HASTFECH)
							  AND (C.VATCOD != P_UTILIDAD.F_VALODEVA('TIARMPF4') OR (C.VATCOD = P_UTILIDAD.F_VALODEVA('TIARMPF4') AND C.VNACOD IN ('1','43','16','46')))
							  AND C.EMCODI = M.EMPRESA
							  AND C.VATCOD = M.TIP_ARTI
							  AND C.ARCARF = M.COD_ARTI
							  AND C.ASLOTE = M.LOTE
							  AND ROWNUM = 1)--M.PRECIO_COMPRA_CALCULADO
				,0),0,P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_PRECIO(M.EMPRESA,M.TIP_ARTI,M.COD_ARTI,O.FEC_MODI),'PRECIO'),
				(SELECT DECODE(C.ALUNST,P_Utilidad.F_ValoDeva('TIPOUNM2'),DECODE(C.ALUPRE,0,DECODE(C.ALCANT, 0, 0,((C.ALPREU * D.CAMBIO) * C.ALCAEQ) / C.ALCANT),
																									DECODE(C.ALCANT, 0, 0,(((C.ALPREU * D.CAMBIO) * C.ALCAEQ) / C.ALCANT) / C.ALUPRE) 
										 ))ALPREU  
						FROM FV_ASCOAL02 C, GNR_DICOTIZA D, FV_ASCOAL01 CA
							WHERE CA.EMCODI = C.EMCODI
							  AND CA.DICODI = C.DICODI
							  AND CA.ACANYA = C.ACANYA
							  AND CA.ACNROA = C.ACNROA
							  AND CA.TIPDOC IS NULL
							  AND C.DIVISA = D.DIVISA
							  AND D.DIVISAMA = P_UTILIDAD.F_VALODEVA('DIVIEURO')
							  AND TRUNC(C.ACFENT) BETWEEN TRUNC(DESDFECH) AND TRUNC(HASTFECH)
							  AND (C.VATCOD != P_UTILIDAD.F_VALODEVA('TIARMPF4') OR (C.VATCOD = P_UTILIDAD.F_VALODEVA('TIARMPF4') AND C.VNACOD IN ('1','43','16','46')))
							  AND C.EMCODI = M.EMPRESA
							  AND C.VATCOD = M.TIP_ARTI
							  AND C.ARCARF = M.COD_ARTI
							  AND C.ASLOTE = M.LOTE
							  AND ROWNUM = 1)--M.PRECIO_COMPRA_CALCULADO
				))
            ELSE (/*SUM(*/M.CANTCONS/*)*/ *(((ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material_Exp_OT(O.EMPRESA, O.NUMERO, MP.FASE) * AO.ANCHO) + NVL(TO_NUMBER(P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_Mermas_Planificacion_Optima(O.EMPRESA, O.NUMERO),'IZQUIER')),0) + NVL(TO_NUMBER(P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_Mermas_Planificacion_Optima(O.EMPRESA, O.NUMERO),'DERECHA')),0) - --NVL(M.IZQUIERD,0) + NVL(M.DERECHA,0) - --ARP
                                    (ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material_Exp_OT(O.EMPRESA, O.NUMERO, MP.FASE) * AO.ANCHO)) / 1000) * --ANCHO PRODUCCION
       DECODE(NVL(
		            (SELECT DECODE(C.ALUNST,P_Utilidad.F_ValoDeva('TIPOUNM2'),DECODE(C.ALUPRE,0,DECODE(C.ALCANT, 0, 0,((C.ALPREU * D.CAMBIO) * C.ALCAEQ) / C.ALCANT),
																									DECODE(C.ALCANT, 0, 0,(((C.ALPREU * D.CAMBIO) * C.ALCAEQ) / C.ALCANT) / C.ALUPRE) 
										 ))ALPREU  
						FROM FV_ASCOAL02 C, GNR_DICOTIZA D, FV_ASCOAL01 CA
							WHERE CA.EMCODI = C.EMCODI
							  AND CA.DICODI = C.DICODI
							  AND CA.ACANYA = C.ACANYA
							  AND CA.ACNROA = C.ACNROA
							  AND CA.TIPDOC IS NULL
							  AND C.DIVISA = D.DIVISA
							  AND D.DIVISAMA = P_UTILIDAD.F_VALODEVA('DIVIEURO')
							  AND TRUNC(C.ACFENT) BETWEEN TRUNC(DESDFECH) AND TRUNC(HASTFECH)
							  AND (C.VATCOD != P_UTILIDAD.F_VALODEVA('TIARMPF4') OR (C.VATCOD = P_UTILIDAD.F_VALODEVA('TIARMPF4') AND C.VNACOD IN ('1','43','16','46')))
							  AND C.EMCODI = M.EMPRESA
							  AND C.VATCOD = M.TIP_ARTI
							  AND C.ARCARF = M.COD_ARTI
							  AND C.ASLOTE = M.LOTE
							  AND ROWNUM = 1)--M.PRECIO_COMPRA_CALCULADO
				 ,0),0,P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_PRECIO(M.EMPRESA,M.TIP_ARTI,M.COD_ARTI,O.FEC_MODI),'PRECIO'),
				 (SELECT DECODE(C.ALUNST,P_Utilidad.F_ValoDeva('TIPOUNM2'),DECODE(C.ALUPRE,0,DECODE(C.ALCANT, 0, 0,((C.ALPREU * D.CAMBIO) * C.ALCAEQ) / C.ALCANT),
																									DECODE(C.ALCANT, 0, 0,(((C.ALPREU * D.CAMBIO) * C.ALCAEQ) / C.ALCANT) / C.ALUPRE) 
										 ))ALPREU  
						FROM FV_ASCOAL02 C, GNR_DICOTIZA D, FV_ASCOAL01 CA
							WHERE CA.EMCODI = C.EMCODI
							  AND CA.DICODI = C.DICODI
							  AND CA.ACANYA = C.ACANYA
							  AND CA.ACNROA = C.ACNROA
							  AND CA.TIPDOC IS NULL
							  AND C.DIVISA = D.DIVISA
							  AND D.DIVISAMA = P_UTILIDAD.F_VALODEVA('DIVIEURO')
							  AND TRUNC(C.ACFENT) BETWEEN TRUNC(DESDFECH) AND TRUNC(HASTFECH)
							  AND (C.VATCOD != P_UTILIDAD.F_VALODEVA('TIARMPF4') OR (C.VATCOD = P_UTILIDAD.F_VALODEVA('TIARMPF4') AND C.VNACOD IN ('1','43','16','46')))
							  AND C.EMCODI = M.EMPRESA
							  AND C.VATCOD = M.TIP_ARTI
							  AND C.ARCARF = M.COD_ARTI
							  AND C.ASLOTE = M.LOTE
							  AND ROWNUM = 1)--M.PRECIO_COMPRA_CALCULADO
				 ))
            END EUROS_OPTIMA_REAL_MP
FROM FIC_CABEOTRE O, PRD_MAPAMAQU M, 
     --ARTICULO A, LFS L, 
     (SELECT A.EMPRESA, A.TIP_ARTI, A.COD_ARTI, A.COD_LFS, A.ANCHO, L.FCKG FROM  ARTICULO A, LFS L 
      WHERE A.EMPRESA = L.EMPRESA
        AND A.COD_LFS = L.COD_LFS) A,
     CLIENTES C, ARTICULO AO, LFS LO,
     (SELECT MA.EMPRESA, MA.NUMEOTRE, MA.CONTADOR, DECODE(INSTR(MA.MAQUCODI,'CORTADORA'),0,NULL,L.FASE) FASE, L.FASE FASEBUMP--, MIN(MP.IZQUIERD) IZQUIERD, MIN(MP.DERECHA) DERECHA 
      FROM --PRD_MAQUMPLA MP, 
           (SELECT MR.EMPRESA, MR.NUMEOTRE, MR.CONTADOR, MR.FASESEQU, MR.MAQUTIPO, MR.MAQUCODI, MR.ESTADO FROM PRD_MAQURUTA MR
            WHERE NOT EXISTS (SELECT 'X' FROM PRD_HCABEOTR OTC WHERE OTC.EMPRESA = MR.EMPRESA AND OTC.NUMEOTRE = MR.NUMEOTRE)
            UNION
            SELECT MR.EMPRESA, MR.NUMEOTRE, MR.CONTADOR, MR.FASESEQU, MR.MAQUTIPO, MR.MAQUCODI, MR.ESTADO FROM PRD_HMAQURUT MR) MA, 
           FIC_LINEOTRE L
         WHERE /*MP.EMPRESA = MA.EMPRESA
           AND MP.MAQUTIPO = MA.MAQUTIPO
           AND MP.MAQUCODI = MA.MAQUCODI
           AND */L.EMPRESA = MA.EMPRESA
           AND L.NUMERO = MA.NUMEOTRE
           AND L.TIP_ARES = P_UTILIDAD.F_VALODEVA('TIPORECU')
           AND (L.COD_ARES NOT LIKE 'CORTADORA%' OR --Si es diferente de Cortadora 
                (                                   --o
                 L.COD_ARES LIKE 'CORTADORA%' AND NOT EXISTS (SELECT 'X'
                                                              FROM VALORES_LISTA V
                                                              WHERE V.CODIGO = 'FIC_TIPIRECU'
                                                                AND INSTR(L.COD_ARES,P_UTILIDAD.F_VALOCAMPO(V.VALOR,'RECURSO')) != 0
                                                                AND P_UTILIDAD.F_VALOCAMPO(V.VALOR,'CODIGO') = L.TIPIRECU
                                                                AND P_UTILIDAD.F_VALOCAMPO(V.VALOR,'PRE-CORTE') = 'S')--L.FASE = L.FASESIGU --Si es cortadora pero no es pre-corte
                )
               )
           AND MA.FASESEQU = (L.FASE * 100) + L.SECUENCI
           --AND TIPO = 'E'
      --GROUP BY MA.EMPRESA, MA.NUMEOTRE, MA.CONTADOR, DECODE(INSTR(MA.MAQUCODI,'CORTADORA'),0,NULL,L.FASE)
      ) MP
WHERE O.EMPRESA = M.EMPRESA
  AND O.NUMERO = M.NUMEOTRE
  AND O.EMPRESA = AO.EMPRESA
  AND O.TIP_ARTI = AO.TIP_ARTI
  AND O.COD_ARTI = AO.COD_ARTI
  AND AO.EMPRESA = LO.EMPRESA
  AND AO.COD_LFS = LO.COD_LFS
  AND M.EMPRESA = A.EMPRESA(+)
  AND M.TIP_ARTI = A.TIP_ARTI(+)
  AND M.COD_ARTI = A.COD_ARTI(+)
  AND AO.EMPRESA = C.EMPRESA(+)
  AND AO.CLIENASOC = C.CLIENTE_ID(+)
  AND (M.TIP_ARTI IN (P_UTILIDAD.F_VALODEVA('TIARMPF4'),P_UTILIDAD.F_VALODEVA('TIARSEF4'),P_UTILIDAD.F_VALODEVA('TIARFIF4')) OR (M.TIP_ARTI = P_UTILIDAD.F_VALODEVA('TIARCOSC') AND M.NUMEOTRE != M.LOTE AND M.LOTE IS NOT NULL))
  --AND M.TIP_ARTI IN (P_UTILIDAD.F_VALODEVA('TIARMPF4'),P_UTILIDAD.F_VALODEVA('TIARSEF4'))
  --AND A.EMPRESA = L.EMPRESA
  --AND A.COD_LFS = L.COD_LFS
  AND M.EMPRESA = MP.EMPRESA(+)
  AND M.NUMEOTRE = MP.NUMEOTRE(+)
  AND M.CONTADOR = MP.CONTADOR(+)
  --AND O.EMPRESA = '10' AND O.NUMERO = 2016005919
  --AND O.EMPRESA = '05' AND O.NUMERO = 2016000059
  --AND O.EMPRESA IN ('10','05') AND O.FEC_MODI >= TO_DATE('01-01-2016','DD-MM-YYYY') --AND O.NUMERO = 2016006695
  ) M
GROUP BY M.EMPRESA, M.CLIENTE, M.NOMBRE_DEL_CLIENTE, M.OT, M.FEC_CIERRE_OT, M.TIPO_PRD, M.ESPECIALIDAD, M.LINEA, M.LFS, 
         M.ANCHO_ESPECIALIDAD,
			M.PEDIDO, M.PEDIDO_TM, M.PROVEEDO_TM, M.FECHRECE_TM,
      M.FECHA_CIERRE_OT_SEMIELABORADO, 
			M.TIPO, M.COD_MP, M.ANCHO, M.LFS_MP,
			M.LOTE,
			M.FECHA_RECEPCION, M.FECHA_ENTRADA_ALMACEN,
			M.PROV, M.UNIDAD_COMPRADA, M.PRECIO_COMPRA_CALCULADO, M.FEC_MODI,
			M.FCKG, M.NUMEPEDI, 
         --M.IZQUIERD, M.DERECHA, 
         --M.FASE;--,
         --M.FASEBUMP;
			M.N_DE_CORTES,
		   M.N_DE_VECES,
		   M.ANCHO_DE_PRODUCCION,
			ARP;
