CREATE OR REPLACE VIEW ANALESTA.ANE_ANNO_MES_PROCESAR AS         
         SELECT CMOP.ANNO,
                DECODE(MIN(CMOP.COMPDICI)||MIN(DEPA.COMPDICI),'SS','12',DECODE(MIN(CMOP.COMPNOVI)||MIN(DEPA.COMPNOVI),'SS','11',DECODE(MIN(CMOP.COMPOCTU)||MIN(DEPA.COMPOCTU),'SS','10',DECODE(MIN(CMOP.COMPSEPT)||MIN(DEPA.COMPSEPT),'SS','09',DECODE(MIN(CMOP.COMPAGOS)||MIN(DEPA.COMPAGOS),'SS','08',DECODE(MIN(CMOP.COMPJULI)||MIN(DEPA.COMPJULI),'SS','07',
                DECODE(MIN(CMOP.COMPJUNI)||MIN(DEPA.COMPJUNI),'SS','06',DECODE(MIN(CMOP.COMPMAYO)||MIN(DEPA.COMPMAYO),'SS','05',DECODE(MIN(CMOP.COMPABRI)||MIN(DEPA.COMPABRI),'SS','04',DECODE(MIN(CMOP.COMPMARZ)||MIN(DEPA.COMPMARZ),'SS','03',DECODE(MIN(CMOP.COMPFEBR)||MIN(DEPA.COMPFEBR),'SS','02',DECODE(MIN(CMOP.COMPENER)||MIN(DEPA.COMPENER),'SS','01')))))))))))) ULTIMO_MES_CARGADO
         FROM PRD_ANNOANCO CMOP, ANE_CODEANNO DEPA, VALORES_LISTA LVE 
         WHERE LVE.CODIGO = 'GNR_EMPRACGR'
           AND LVE.VALOR = DEPA.EMPRESA
           AND CMOP.EMPRESA = DEPA.EMPRESA
           AND CMOP.ANNO = DEPA.ANNO
           AND NOT EXISTS (SELECT 'X' FROM PRD_ANNOANCO CMOP2, VALORES_LISTA LVE2 WHERE LVE2.CODIGO = 'GNR_EMPRACGR' AND LVE2.VALOR = CMOP2.EMPRESA AND CMOP2.ANNO = CMOP.ANNO AND CMOP.ANNOCOMP = 'N')
           AND NOT EXISTS (SELECT 'X' FROM ANE_CODEANNO DEPA2, VALORES_LISTA LVE2 WHERE LVE2.CODIGO = 'GNR_EMPRACGR' AND LVE2.VALOR = DEPA2.EMPRESA AND DEPA2.ANNO = DEPA.ANNO AND DEPA.ANNOCOMP = 'N')
        GROUP BY CMOP.ANNO;