CREATE OR REPLACE VIEW ANALESTA.ANE_TINTAS AS
SELECT O.EMPRESA,
       A.CLIENASOC N_CLIENTE,
       C.RAZON_SOC CLIENTE,
       O.NUMERO OT,
       O.FEC_MODI FECHA_DE_LA_OT,
		 DECODE(O.SITUACIO,'C',O.FEC_MODI,NULL)FECHA_CIERRE_DE_LA_OT,
		 O.NUMEPEDI N_PEDIDO,
       O.TIP_ARTI TIPO_PRD,
       O.COD_ARTI ESPECIALIDAD,
       SUBSTR(A.COD_LFS,1,2) LINEA,
       A.COD_LFS LFS,
		 DECODE((SELECT 'X' FROM PRD_HIREOTRF OTC WHERE OTC.EMPRESA = O.EMPRESA AND OTC.NUMEOTRE = O.NUMERO AND ROWNUM = 1),NULL,
		 (SELECT COUNT (*) NUMERO
			FROM PRD_RECUOTRF RU, 
				  PRD_HICOOTRE HC
			WHERE RU.EMPRESA = HC.EMPRESA
			  AND RU.NUMEOTRE = HC.NUMEOTRE
			  AND RU.RECUCODI = HC.POSICION||'-'||HC.COLOR
			  AND RU.EMPRESA = T.EMPRESA
			  AND RU.NUMEOTRE = T.NUMEOTRE
			  AND RU.CONTADOR = T.CONTADOR
			  AND RU.RECUTIPO = 'J'),
		 (SELECT COUNT (*)
			FROM PRD_HIREOTRF RU, 
				  PRD_HICOHOTR HC
			WHERE RU.EMPRESA = HC.EMPRESA
			  AND RU.NUMEOTRE = HC.NUMEOTRE
			  AND RU.RECUCODI = HC.POSICION||'-'||HC.COLOR
			  AND RU.EMPRESA = T.EMPRESA
			  AND RU.NUMEOTRE = T.NUMEOTRE
			  AND RU.CONTADOR = T.CONTADOR
			  AND RU.RECUTIPO = 'J')) N_TINTEROS,
   EC.ML_PASADOS_MAQUINA,
	DECODE(O.TIP_ARTI,P_UTILIDAD.F_VALODEVA('TIARPROI'),(SELECT PI.ANCHO FROM FIC_HPIGESTI PI WHERE PI.EMPRESA = O.EMPRESA AND PI.NUMEPEDI = O.NUMEPEDI),A.ANCHO) ANCHO_CLIENTE,
	CASE WHEN EC.FASE IS NULL THEN ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material(O.EMPRESA, O.NUMERO, (SELECT MAX(LO.FASE) FROM FIC_LINEOTRE LO
																							   WHERE LO.EMPRESA = O.EMPRESA 
																								  AND LO.NUMERO = O.NUMERO
																								  AND ((INSTR(LO.COD_ARES,'IMPRESORA') != 0) OR
																								       (INSTR(LO.COD_ARES,'CORTADORA') != 0) OR
																										 (INSTR(LO.COD_ARES,'LAMINADORA') != 0) OR
																										 (INSTR(LO.COD_ARES,'LAQUEADORA') != 0))))
            ELSE ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material(O.EMPRESA, O.NUMERO, EC.FASE)
            END N_DE_CORTES,
	 CASE WHEN EC.FASE IS NULL THEN ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material_Exp_OT(O.EMPRESA, O.NUMERO, (SELECT MAX(LO.FASE) FROM FIC_LINEOTRE LO
																							WHERE LO.EMPRESA = O.EMPRESA 
																								  AND LO.NUMERO = O.NUMERO
																							  AND ((INSTR(LO.COD_ARES,'IMPRESORA') != 0) OR
																									 (INSTR(LO.COD_ARES,'CORTADORA') != 0) OR
																									 (INSTR(LO.COD_ARES,'LAMINADORA') != 0) OR
																									 (INSTR(LO.COD_ARES,'LAQUEADORA') != 0)))) * A.ANCHO
			ELSE ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material_Exp_OT(O.EMPRESA, O.NUMERO, EC.FASE) * A.ANCHO
			END ANCHO_DE_PRODUCCION,
   EC.ML_PASADOS_MAQUINA * (DECODE(O.TIP_ARTI,P_UTILIDAD.F_VALODEVA('TIARPROI'),(SELECT PI.ANCHO FROM FIC_HPIGESTI PI WHERE PI.EMPRESA = O.EMPRESA AND PI.NUMEPEDI = O.NUMEPEDI),A.ANCHO)/1000) M2_PASADOS_MAQUINA,
   T.CONTADOR, T.RECUCODI, T.MATECODE, T.COLOR, T.PANTONE, T.TIPO_IMPRE, T.ANILOX, T.SUPEARIM, 
	((EC.ML_PASADOS_MAQUINA * (DECODE(O.TIP_ARTI,P_UTILIDAD.F_VALODEVA('TIARPROI'),(SELECT PI.ANCHO FROM FIC_HPIGESTI PI WHERE PI.EMPRESA = O.EMPRESA AND PI.NUMEPEDI = O.NUMEPEDI),A.ANCHO)/1000) * NVL(T.SUPEARIM,0)) / 100) SUP_M2_MAQ_TINTA,
	T.POSICION,
   DA.FLEXO_HUECO, DA.ANILOX_APOCM3M2, DA.ANILOX_PORCAPOR, 
	((DA.ANILOX_APOCM3M2 * NVL(DA.ANILOX_PORCAPOR,0)) / 100) APOCM3M2_TIN,
	((EC.ML_PASADOS_MAQUINA * (DECODE(O.TIP_ARTI,P_UTILIDAD.F_VALODEVA('TIARPROI'),(SELECT PI.ANCHO FROM FIC_HPIGESTI PI WHERE PI.EMPRESA = O.EMPRESA AND PI.NUMEPEDI = O.NUMEPEDI),A.ANCHO)/1000) * NVL(T.SUPEARIM,0)) / 100) * ((DA.ANILOX_APOCM3M2 * NVL(DA.ANILOX_PORCAPOR,0)) / 100) VOLUMCM3_TIN,
	DECODE(INSTR(T.COLOR,'BLANCO'),0,
	       DECODE(DA.FLEXO_HUECO,'FLEXO',(SELECT VALOR FROM ANALESTA.ANE_PESO_ESPECIFICO_TINTA WHERE TINTA = 'RESTO' AND TIPO_IMPRESION = 'FLEXO'),'HUECO',(SELECT VALOR FROM ANALESTA.ANE_PESO_ESPECIFICO_TINTA WHERE TINTA = 'RESTO' AND TIPO_IMPRESION = 'HUECO'),0),
			 DECODE(DA.FLEXO_HUECO,'FLEXO',(SELECT VALOR FROM ANALESTA.ANE_PESO_ESPECIFICO_TINTA WHERE TINTA = 'BLANCO' AND TIPO_IMPRESION = 'FLEXO'),'HUECO',(SELECT VALOR FROM ANALESTA.ANE_PESO_ESPECIFICO_TINTA WHERE TINTA = 'BLANCO' AND TIPO_IMPRESION = 'HUECO'),0)
			) PEESTINT_TIN,
	(DECODE(INSTR(T.COLOR,'BLANCO'),0,
	       DECODE(DA.FLEXO_HUECO,'FLEXO',(SELECT VALOR FROM ANALESTA.ANE_PESO_ESPECIFICO_TINTA WHERE TINTA = 'RESTO' AND TIPO_IMPRESION = 'FLEXO'),'HUECO',(SELECT VALOR FROM ANALESTA.ANE_PESO_ESPECIFICO_TINTA WHERE TINTA = 'RESTO' AND TIPO_IMPRESION = 'HUECO'),0),
			 DECODE(DA.FLEXO_HUECO,'FLEXO',(SELECT VALOR FROM ANALESTA.ANE_PESO_ESPECIFICO_TINTA WHERE TINTA = 'BLANCO' AND TIPO_IMPRESION = 'FLEXO'),'HUECO',(SELECT VALOR FROM ANALESTA.ANE_PESO_ESPECIFICO_TINTA WHERE TINTA = 'BLANCO' AND TIPO_IMPRESION = 'HUECO'),0)
			) * ((EC.ML_PASADOS_MAQUINA * (DECODE(O.TIP_ARTI,P_UTILIDAD.F_VALODEVA('TIARPROI'),(SELECT PI.ANCHO FROM FIC_HPIGESTI PI WHERE PI.EMPRESA = O.EMPRESA AND PI.NUMEPEDI = O.NUMEPEDI),A.ANCHO)/1000) * NVL(T.SUPEARIM,0)) / 100) * ((DA.ANILOX_APOCM3M2 * NVL(DA.ANILOX_PORCAPOR,0)) / 100)) / 1000 CONSTEKG_TIN,
	P_UTILIDAD.F_VALOCAMPO(
	ANALESTA.P_ANE_MERMLAMI_PRAG.F_Precio_Tintas(O.EMPRESA,T.MATECODE,O.FEC_MODI,
	                                             (DECODE(INSTR(T.COLOR,'BLANCO'),0,
																 DECODE(DA.FLEXO_HUECO,'FLEXO',(SELECT VALOR FROM ANALESTA.ANE_PESO_ESPECIFICO_TINTA WHERE TINTA = 'RESTO' AND TIPO_IMPRESION = 'FLEXO'),'HUECO',(SELECT VALOR FROM ANALESTA.ANE_PESO_ESPECIFICO_TINTA WHERE TINTA = 'RESTO' AND TIPO_IMPRESION = 'HUECO'),0),
																 DECODE(DA.FLEXO_HUECO,'FLEXO',(SELECT VALOR FROM ANALESTA.ANE_PESO_ESPECIFICO_TINTA WHERE TINTA = 'BLANCO' AND TIPO_IMPRESION = 'FLEXO'),'HUECO',(SELECT VALOR FROM ANALESTA.ANE_PESO_ESPECIFICO_TINTA WHERE TINTA = 'BLANCO' AND TIPO_IMPRESION = 'HUECO'),0)
																) * ((EC.ML_PASADOS_MAQUINA * (DECODE(O.TIP_ARTI,P_UTILIDAD.F_VALODEVA('TIARPROI'),(SELECT PI.ANCHO FROM FIC_HPIGESTI PI WHERE PI.EMPRESA = O.EMPRESA AND PI.NUMEPEDI = O.NUMEPEDI),A.ANCHO)/1000) * NVL(T.SUPEARIM,0)) / 100) * ((DA.ANILOX_APOCM3M2 * NVL(DA.ANILOX_PORCAPOR,0)) / 100)) / 1000),'PRECIO') PRECIO_UNITARIO_KG_TINTA,
	P_UTILIDAD.F_VALOCAMPO(
	ANALESTA.P_ANE_MERMLAMI_PRAG.F_Precio_Tintas(O.EMPRESA,T.MATECODE,O.FEC_MODI,
	                                             (DECODE(INSTR(T.COLOR,'BLANCO'),0,
																 DECODE(DA.FLEXO_HUECO,'FLEXO',(SELECT VALOR FROM ANALESTA.ANE_PESO_ESPECIFICO_TINTA WHERE TINTA = 'RESTO' AND TIPO_IMPRESION = 'FLEXO'),'HUECO',(SELECT VALOR FROM ANALESTA.ANE_PESO_ESPECIFICO_TINTA WHERE TINTA = 'RESTO' AND TIPO_IMPRESION = 'HUECO'),0),
																 DECODE(DA.FLEXO_HUECO,'FLEXO',(SELECT VALOR FROM ANALESTA.ANE_PESO_ESPECIFICO_TINTA WHERE TINTA = 'BLANCO' AND TIPO_IMPRESION = 'FLEXO'),'HUECO',(SELECT VALOR FROM ANALESTA.ANE_PESO_ESPECIFICO_TINTA WHERE TINTA = 'BLANCO' AND TIPO_IMPRESION = 'HUECO'),0)
																) * ((EC.ML_PASADOS_MAQUINA * (DECODE(O.TIP_ARTI,P_UTILIDAD.F_VALODEVA('TIARPROI'),(SELECT PI.ANCHO FROM FIC_HPIGESTI PI WHERE PI.EMPRESA = O.EMPRESA AND PI.NUMEPEDI = O.NUMEPEDI),A.ANCHO)/1000) * NVL(T.SUPEARIM,0)) / 100) * ((DA.ANILOX_APOCM3M2 * NVL(DA.ANILOX_PORCAPOR,0)) / 100)) / 1000),'EUROS') COSTE_EUR_TINTA
FROM FIC_CABEOTRE O, ARTICULO A, CLIENTES C,
     (SELECT RU.EMPRESA, RU.NUMEOTRE, RU.CONTADOR, RU.RECUCODI, RU.MATECODE, HC.COLOR, HC.PANTONE, HC.TIPO_IMPRE, HC.ANILOX, HC.SUPEARIM, HC.POSICION
		FROM PRD_RECUOTRF RU, 
			  PRD_HICOOTRE HC
		WHERE NOT EXISTS (SELECT 'X' FROM PRD_HIREOTRF OTC WHERE OTC.EMPRESA = RU.EMPRESA AND OTC.NUMEOTRE = RU.NUMEOTRE AND ROWNUM = 1)
		  AND RU.EMPRESA = HC.EMPRESA
		  AND RU.NUMEOTRE = HC.NUMEOTRE
		  AND RU.RECUCODI = HC.POSICION||'-'||HC.COLOR
		  AND RU.RECUTIPO = 'J'
		UNION
		SELECT RU.EMPRESA, RU.NUMEOTRE, RU.CONTADOR, RU.RECUCODI, RU.MATECODE, HC.COLOR, HC.PANTONE, HC.TIPO_IMPRE, HC.ANILOX, HC.SUPEARIM, HC.POSICION
		FROM PRD_HIREOTRF RU, 
			  PRD_HICOHOTR HC
		WHERE RU.EMPRESA = HC.EMPRESA
		  AND RU.NUMEOTRE = HC.NUMEOTRE
		  AND RU.RECUCODI = HC.POSICION||'-'||HC.COLOR
		  AND RU.RECUTIPO = 'J') T,
     (SELECT EC.EMPRESA, EC.NUMEOTRE, EC.CONTADOR,  DECODE(INSTR(EC.MAQUCODI,'CORTADORA'),0,NULL,L.FASE) FASE,
	          SUM(CANTPROD) ML_PASADOS_MAQUINA 
	   FROM PRD_PASAMAQU EC, FIC_LINEOTRE L,
		     (SELECT MR.EMPRESA, MR.NUMEOTRE, MR.CONTADOR, MR.FASESEQU, MR.MAQUTIPO, MR.MAQUCODI, MR.ESTADO FROM PRD_MAQURUTA MR
            WHERE NOT EXISTS (SELECT 'X' FROM PRD_HCABEOTR OTC WHERE OTC.EMPRESA = MR.EMPRESA AND OTC.NUMEOTRE = MR.NUMEOTRE)
            UNION
            SELECT MR.EMPRESA, MR.NUMEOTRE, MR.CONTADOR, MR.FASESEQU, MR.MAQUTIPO, MR.MAQUCODI, MR.ESTADO FROM PRD_HMAQURUT MR) MA
		WHERE EC.EMPRESA = MA.EMPRESA
		  AND EC.NUMEOTRE = MA.NUMEOTRE
		  AND EC.CONTADOR = MA.CONTADOR
		  AND L.EMPRESA = MA.EMPRESA
		  AND L.NUMERO = MA.NUMEOTRE
		  AND L.TIP_ARES = P_UTILIDAD.F_VALODEVA('TIPORECU')
		  AND (L.COD_ARES NOT LIKE 'CORTADORA%' OR --Si es diferente de Cortadora 
				 (                                   --o
				  L.COD_ARES LIKE 'CORTADORA%' AND NOT EXISTS (SELECT 'X'
																			  FROM VALORES_LISTA V
																			  WHERE V.CODIGO = 'FIC_TIPIRECU'
																				 AND INSTR(L.COD_ARES,P_UTILIDAD.F_VALOCAMPO(V.VALOR,'RECURSO')) != 0
																				 AND P_UTILIDAD.F_VALOCAMPO(V.VALOR,'CODIGO') = L.TIPIRECU
																				 AND P_UTILIDAD.F_VALOCAMPO(V.VALOR,'PRE-CORTE') = 'S')--L.FASE = L.FASESIGU --Si es cortadora pero no es pre-corte
				 )
				)
		  AND MA.FASESEQU = (L.FASE * 100) + L.SECUENCI
		GROUP BY EC.EMPRESA, EC.NUMEOTRE, EC.CONTADOR, DECODE(INSTR(EC.MAQUCODI,'CORTADORA'),0,NULL,L.FASE)) EC,
   (SELECT P_UTILIDAD.F_ValoCampo (VL.VALOR,'VALOR') TIPO_IMPRE, DA.CODIGO ANILOX, DA.TIPOIMPR FLEXO_HUECO, DA.APOCM3M2 ANILOX_APOCM3M2, DA.PORCAPOR ANILOX_PORCAPOR
	 FROM PRI_DEFIANIL DA, VALORES_LISTA VL
	 WHERE VL.CODIGO = 'FIC_TIPOIMPR'
	   AND DA.TIPOIMPR = P_UTILIDAD.F_ValoCampo (VALOR,'TIPOIMPR')) DA
WHERE O.EMPRESA = A.EMPRESA
  AND O.TIP_ARTI = A.TIP_ARTI
  AND O.COD_ARTI = A.COD_ARTI
  AND A.EMPRESA = C.EMPRESA(+)
  AND A.CLIENASOC = C.CLIENTE_ID(+)
  AND O.EMPRESA = T.EMPRESA
  AND O.NUMERO = T.NUMEOTRE
  AND T.EMPRESA = EC.EMPRESA
  AND T.NUMEOTRE = EC.NUMEOTRE
  AND T.CONTADOR = EC.CONTADOR
  AND T.TIPO_IMPRE = DA.TIPO_IMPRE(+)
  AND T.ANILOX = DA.ANILOX(+)
  --AND O.NUMERO LIKE '2016%'
  ;
  /
SELECT * FROM ANALESTA.ANE_PESO_ESPECIFICO_TINTA;