CREATE OR REPLACE VIEW ANALESTA.ANE_ANNOS_CARGADOS_SISTEMA AS         
         SELECT CMOP.EMPRESA,CMOP.ANNO,
                DECODE(CMOP.COMPDICI||DEPA.COMPDICI,'SS','12',DECODE(CMOP.COMPNOVI||DEPA.COMPNOVI,'SS','11',DECODE(CMOP.COMPOCTU||DEPA.COMPOCTU,'SS','10',DECODE(CMOP.COMPSEPT||DEPA.COMPSEPT,'SS','09',DECODE(CMOP.COMPAGOS||DEPA.COMPAGOS,'SS','08',DECODE(CMOP.COMPJULI||DEPA.COMPJULI,'SS','07',
                DECODE(CMOP.COMPJUNI||DEPA.COMPJUNI,'SS','06',DECODE(CMOP.COMPMAYO||DEPA.COMPMAYO,'SS','05',DECODE(CMOP.COMPABRI||DEPA.COMPABRI,'SS','04',DECODE(CMOP.COMPMARZ||DEPA.COMPMARZ,'SS','03',DECODE(CMOP.COMPFEBR||DEPA.COMPFEBR,'SS','02',DECODE(CMOP.COMPENER||DEPA.COMPENER,'SS','01')))))))))))) ULTIMO_MES_CARGADO,
                DECODE(CMOP.COMPDICI,'S','12',DECODE(CMOP.COMPNOVI,'S','11',DECODE(CMOP.COMPOCTU,'S','10',DECODE(CMOP.COMPSEPT,'S','09',DECODE(CMOP.COMPAGOS,'S','08',DECODE(CMOP.COMPJULI,'S','07',
                DECODE(CMOP.COMPJUNI,'S','06',DECODE(CMOP.COMPMAYO,'S','05',DECODE(CMOP.COMPABRI,'S','04',DECODE(CMOP.COMPMARZ,'S','03',DECODE(CMOP.COMPFEBR,'S','02',DECODE(CMOP.COMPENER,'S','01')))))))))))) ULTIMO_MES_CARGADO_RRHH,
                DECODE(DEPA.COMPDICI,'S','12',DECODE(DEPA.COMPNOVI,'S','11',DECODE(DEPA.COMPOCTU,'S','10',DECODE(DEPA.COMPSEPT,'S','09',DECODE(DEPA.COMPAGOS,'S','08',DECODE(DEPA.COMPJULI,'S','07',
                DECODE(DEPA.COMPJUNI,'S','06',DECODE(DEPA.COMPMAYO,'S','05',DECODE(DEPA.COMPABRI,'S','04',DECODE(DEPA.COMPMARZ,'S','03',DECODE(DEPA.COMPFEBR,'S','02',DECODE(DEPA.COMPENER,'S','01')))))))))))) ULTIMO_MES_CARGADO_FINANCIERO,
                CMOP.COMPENER MES_DE_ENER_CARGADO_FINANCIERO, CMOP.COMPFEBR MES_DE_FEBR_CARGADO_FINANCIERO, 
                CMOP.COMPMARZ MES_DE_MARZ_CARGADO_FINANCIERO, CMOP.COMPABRI MES_DE_ABRI_CARGADO_FINANCIERO, 
                CMOP.COMPMAYO MES_DE_MAYO_CARGADO_FINANCIERO, CMOP.COMPJUNI MES_DE_JUNI_CARGADO_FINANCIERO, 
                CMOP.COMPJULI MES_DE_JULI_CARGADO_FINANCIERO, CMOP.COMPAGOS MES_DE_AGOS_CARGADO_FINANCIERO, 
                CMOP.COMPSEPT MES_DE_SEPT_CARGADO_FINANCIERO, CMOP.COMPOCTU MES_DE_OCTU_CARGADO_FINANCIERO, 
                CMOP.COMPNOVI MES_DE_NOVI_CARGADO_FINANCIERO, CMOP.COMPDICI MES_DE_DICI_CARGADO_FINANCIERO,
                DEPA.COMPENER MES_DE_ENER_CARGADO_RRHH, DEPA.COMPFEBR MES_DE_FEBR_CARGADO_RRHH, 
                DEPA.COMPMARZ MES_DE_MARZ_CARGADO_RRHH, DEPA.COMPABRI MES_DE_ABRI_CARGADO_RRHH, 
                DEPA.COMPMAYO MES_DE_MAYO_CARGADO_RRHH, DEPA.COMPJUNI MES_DE_JUNI_CARGADO_RRHH, 
                DEPA.COMPJULI MES_DE_JULI_CARGADO_RRHH, DEPA.COMPAGOS MES_DE_AGOS_CARGADO_RRHH, 
                DEPA.COMPSEPT MES_DE_SEPT_CARGADO_RRHH, DEPA.COMPOCTU MES_DE_OCTU_CARGADO_RRHH, 
                DEPA.COMPNOVI MES_DE_NOVI_CARGADO_RRHH, DEPA.COMPDICI MES_DE_DICI_CARGADO_RRHH,
                CMOP.ANNOCOMP ANNOCOMP_CARGADO_FINANCIERO,
                DEPA.ANNOCOMP ANNOCOMP_CARGADO_RRHH
         FROM PRD_ANNOANCO CMOP, ANE_CODEANNO DEPA
         WHERE CMOP.EMPRESA = DEPA.EMPRESA
           AND CMOP.ANNO = DEPA.ANNO;