CREATE OR REPLACE VIEW "ANALESTA"."ANE_MER_CONFIG_MERMAQ_SISTEMA" AS 
SELECT MC.EMPRESA, MC.MAQUTIPO, MC.MAQUCODI, MC.CARACTER, MC.DESCRIPC, MC.VALOR,
       CA.CAPTACION
FROM PRD_MAQUCARA MC, ANALESTA.ANE_MER_CONFIG_MERMAS_SISTEMA CA
WHERE INSTR(MC.MAQUCODI,CA.MAQUINA) != 0
  AND MC.CARACTER = CA.CARACTERISTICA;