CREATE OR REPLACE VIEW "ANALESTA"."ANE_ARTICULOS" AS
  SELECT A.EMPRESA, A.TIP_ARTI, A.COD_ARTI, A.DESCRIPCION,
       A.COD_LFS, A.ANCHO, A.UNIDVTAS, A.UNIDCOMP, A.UNIDSTOC, A.UNIDPROD, A.PCMPCOMP
FROM ARTICULO A
WHERE EXISTS (SELECT 'X' FROM VALORES_LISTA LVE WHERE LVE.CODIGO = 'GNR_EMPRACGR' AND LVE.VALOR = A.EMPRESA);
