--MIMP, MLAM, MLAQ. MCOR. MMON, NUCA, TIMP, TLAM, TLAQ, TCOR, TMON
--TIMP_CM, TLAM_CM, TLAQ_CM, TCOR_CM, PMON_CM, COSE_IMP, COSE_LAM, COSE_LAQ, COSE_COR, COSE_MON, MIMP_CM, MLAM_CM, MLAQ_CM, MCOR_CM
  CREATE OR REPLACE VIEW "ANALESTA"."ANE_ORDENES_DE_TRABAJO_P3" AS 
  SELECT O.EMPRESA, O.NUMERO NUMERO_OT, O.ANNO ANNO_OT, O.SITUACIO, O.FEC_MODI FECHA_MODIFICACION_OT, TO_CHAR(O.FEC_MODI,'YYYY') ANNO_MODIFICACION_OT, TO_CHAR(O.FEC_MODI,'MM') MES_MODIFICACION_OT,
         CL.CLIENTE_ID, CL.RAZON_SOC, CL.VENDEDOR, CL.TIPO_VENDEDOR, CL.DESCRIPCION_VENEDEDOR, CL.VENCIMIENTO_FX,
         O.TIP_ARTI TIP_ARTI_OT, O.COD_ARTI COD_ARTI_OT, A.DESCRIPCION DESCRIPCION_ARTICULO_OT, O.MODI MODIFICACION, O.REVI REVISION, DECODE(O.TIP_ARTI,P_Utilidad.F_ValoDeva('TIARFIF4'), DECODE(SUBSTR(O.COD_ARTI,3,1), P_Utilidad.F_ValoDeva('TIPOPROY'), 'ANONIMO', 'IMPRESO')) TIPO_ARTICULO,
         P_GNR_AGRUESTR.F_ASIGNA_AGRUESTR(O.EMPRESA, SUBSTR(O.COD_ARTI,4,4),O.TIP_ARTI, O.COD_ARTI) AGRUPACION_ESTRATEGICA,
         O.NUMEPEDI PEDIDO_OT, O.LINEPEDI LINEA_PEDIDO_OT, NVL(LP.TIPOPEDI,'NE') TIPO_DE_PEDIDO, P.REFEENPM REFERENCIA_PEDIDO_MATRIZ_OT, 
         P.DIREENVI CODIGO_DIRECCION_ENVIO, P.PAIS CODIGO_PAIS_DIREC_ENVIO_PEDIDO, P.NOMBRE PAIS_DIREC_ENVIO_PEDIDO, CL.PAIS CODIGO_PAIS_CLIENTE, CL.DESCRIPCION_PAIS PAIS_CLIENTE, 
         DECODE(P.PAIS, NULL,CL.PAIS,P.PAIS) CODIGO_PAIS_ENTREGA, DECODE(P.NOMBRE, NULL,CL.DESCRIPCION_PAIS,P.NOMBRE) PAIS_ENTREGA, DECODE(DECODE(P.PAIS, NULL,CL.PAIS,P.PAIS),NULL,'N',P_Utilidad.F_ValoDeva('PAISESPA'),'N','E') TIPO_PEDIDO,
         O.CANTCERR CANTIDAD_CERRADA_OT, O.UNIDAD UNIDAD_CERRADA_OT, 
         DECODE(O.UNIDAD,P_Utilidad.F_ValoDeva('TIPOUNML'),1,DECODE(NVL(FI.ANCHO,0),0,0,DECODE(O.UNIDAD,P_Utilidad.F_ValoDeva('TIPOUNKG'),FI.FCKG * (1000 / FI.ANCHO),
                                                                                                         P_Utilidad.F_ValoDeva('TIPOUNM2'),(1000 / FI.ANCHO),
                                                                                                         P_Utilidad.F_ValoDeva('TIPOUNUN'),(1000 / FI.ANCHO) * ((FI.ANCHO * FI.LARGO) / 1000000)))) FACTOR_ML_CIERRE_OT_FX, 
         O.CANTCERR * 
         DECODE(O.UNIDAD,P_Utilidad.F_ValoDeva('TIPOUNML'),1,DECODE(NVL(FI.ANCHO,0),0,0,DECODE(O.UNIDAD,P_Utilidad.F_ValoDeva('TIPOUNKG'),FI.FCKG * (1000 / FI.ANCHO),
                                                                                                         P_Utilidad.F_ValoDeva('TIPOUNM2'),(1000 / FI.ANCHO),
                                                                                                         P_Utilidad.F_ValoDeva('TIPOUNUN'),(1000 / FI.ANCHO) * ((FI.ANCHO * FI.LARGO) / 1000000))))
         CANTIDAD_CERRADA_OT_ML,
         DECODE(O.UNIDAD,P_Utilidad.F_ValoDeva('TIPOUNM2'),1,P_Utilidad.F_ValoDeva('TIPOUNKG'),FI.FCKG,
                                                               P_Utilidad.F_ValoDeva('TIPOUNML'),(FI.ANCHO / 1000),
                                                               P_Utilidad.F_ValoDeva('TIPOUNUN'),(FI.ANCHO * FI.LARGO) / 1000000) FACTOR_M2_CIERRE_OT_FX,
         O.CANTCERR *
         DECODE(O.UNIDAD,P_Utilidad.F_ValoDeva('TIPOUNM2'),1,P_Utilidad.F_ValoDeva('TIPOUNKG'),FI.FCKG,
                                                               P_Utilidad.F_ValoDeva('TIPOUNML'),(FI.ANCHO / 1000),
                                                               P_Utilidad.F_ValoDeva('TIPOUNUN'),(FI.ANCHO * FI.LARGO) / 1000000)
         CANTIDAD_CERRADA_OT_M2,
         O.NUMEOTTE NUMERO_OTT, O.ANNOOTTE ANNO_OTT,
         NVL(MPC.VALOR,'N') MATERIAL_PROPIEDAD_CLIENTE,
         FI.ANCHO, FI.LARGO, FI.MATBASE, FI.DESCRIPCION DESCRIPCION_MATBASE, SUBSTR(FI.MATBASE,1,2) LINEA, LIN.DESCRIPCION DESCRIPCION_LINEA,
                DECODE(NVL(TIMP_CM.MINUTOS,0),0,NULL,COSE_IMP.COSTE_SECCION_PRODUCTIVA) COSTE_SECCION_PRODUCTIVA_IMP, 
                DECODE(NVL(TIMP_CM.MINUTOS,0),0,NULL,COSE_IMP.HORAS_SECCION_PRODUCTIVA) HORAS_SECCION_PRODUCTIVA_IMP, 
                DECODE(NVL(TIMP_CM.MINUTOS,0),0,NULL,COSE_IMP.COSTE_HORA_FX) COSTE_HORA_IMP_FX,
                MIMP_CM.CANTPROD CANTPROD_IMPRESORA_CAL_COS_MAQ, TIMP_CM.MINUTOS MINUTOS_IMPRESORA_CAT_2_3, 
                DECODE(NVL(TIMP_CM.MINUTOS,0),0,NULL,COSE_IMP.COSTE_HORA_FX*(TIMP_CM.MINUTOS/60)) COSTE_TOTAL_IMP_FX,
                --
                DECODE(NVL(TLAM_CM.MINUTOS,0),0,NULL,COSE_LAM.COSTE_SECCION_PRODUCTIVA) COSTE_SECCION_PRODUCTIVA_LAM, 
                DECODE(NVL(TLAM_CM.MINUTOS,0),0,NULL,COSE_LAM.HORAS_SECCION_PRODUCTIVA) HORAS_SECCION_PRODUCTIVA_LAM, 
                DECODE(NVL(TLAM_CM.MINUTOS,0),0,NULL,COSE_LAM.COSTE_HORA_FX) COSTE_HORALAM_FX, 
                MLAM_CM.CANTPROD CANTPROD_LAMINADOR_CAL_COS_MAQ, TLAM_CM.MINUTOS MINUTOS_LAMINADORA_CAT_2_3, 
                DECODE(NVL(TLAM_CM.MINUTOS,0),0,NULL,COSE_LAM.COSTE_HORA_FX*(TLAM_CM.MINUTOS/60)) COSTE_TOTAL_LAM_FX,
                --
                DECODE(NVL(TLAQ_CM.MINUTOS,0),0,NULL,COSE_LAQ.COSTE_SECCION_PRODUCTIVA) COSTE_SECCION_PRODUCTIVA_LAQ, 
                DECODE(NVL(TLAQ_CM.MINUTOS,0),0,NULL,COSE_LAQ.HORAS_SECCION_PRODUCTIVA) HORAS_SECCION_PRODUCTIVA_LAQ, 
                DECODE(NVL(TLAQ_CM.MINUTOS,0),0,NULL,COSE_LAQ.COSTE_HORA_FX) COSTE_HORA_LAQ_FX, 
                MLAQ_CM.CANTPROD CANTPROD_LAQUEADOR_CAL_COS_MAQ, TLAQ_CM.MINUTOS MINUTOS_LAQUEADORA_CAT_2_3,
                DECODE(NVL(TLAQ_CM.MINUTOS,0),0,NULL,COSE_LAQ.COSTE_HORA_FX*(TLAQ_CM.MINUTOS/60)) COSTE_TOTAL_LAQ_FX,
                --
                DECODE(NVL(TCOR_CM.MINUTOS,0),0,NULL,COSE_COR.COSTE_SECCION_PRODUCTIVA) COSTE_SECCION_PRODUCTIVA_COR, 
                DECODE(NVL(TCOR_CM.MINUTOS,0),0,NULL,COSE_COR.HORAS_SECCION_PRODUCTIVA) HORAS_SECCION_PRODUCTIVA_COR, 
                DECODE(NVL(TCOR_CM.MINUTOS,0),0,NULL,COSE_COR.COSTE_HORA_FX) COSTE_HORA_COR_FX, 
                MCOR_CM.CANTPROD CANTPROD_CORTADORA_CAL_COS_MAQ, TCOR_CM.MINUTOS MINUTOS_CORTADORA_CAT_2_3, 
                DECODE(NVL(TCOR_CM.MINUTOS,0),0,NULL,COSE_COR.COSTE_HORA_FX*(TCOR_CM.MINUTOS/60)) COSTE_TOTAL_COR_FX,
                --
                PMON_CM.PARTICIPACION PARTICIPACION_MONTAJE,
                --
                DECODE(NVL(PMON_CM.PARTICIPACION,'X'),'X',NULL,COSE_MON.COSTE_SECCION_PRODUCTIVA) COSTE_SECCION_PRODUCTIVA_MON, 
                DECODE(NVL(PMON_CM.PARTICIPACION,'X'),'X',NULL,COSE_MON.NUMERO_OTS_IMPRESAS) NUMERO_OTS_IMPRESAS_MON, 
                DECODE(NVL(PMON_CM.PARTICIPACION,'X'),'X',NULL,COSE_MON.COSTE_HORA_FX) COSTE_TOTAL_MON_FX
         FROM FIC_CABEOTRE O, ARTICULO A, ANALESTA.ANE_CLIENTES CL, GNR_LINEAS LIN,
              ANALESTA.ANE_COS_SECC_PROD_ANNO_MES_CET COSE_IMP,
              ANALESTA.ANE_COS_SECC_PROD_ANNO_MES_CET COSE_COR,
              ANALESTA.ANE_COS_SECC_PROD_ANNO_MES_CET COSE_LAM,
              ANALESTA.ANE_COS_SECC_PROD_ANNO_MES_CET COSE_LAQ,
              ANALESTA.ANE_COS_SECC_PROD_ANNO_MES_CET COSE_MON,
              (SELECT F.EMPRESA, F.NUMEOTRE, TO_CHAR(SUM(F.MINUFINA-F.MINUINIC)) MINUTOS
               FROM PRD_PRMAEVEN F, PRD_EVENTOS E
               WHERE F.EMPRESA = E.EMPRESA
                 AND F.EVENTIPO = E.EVENTIPO
                 AND F.EVENCODI = E.EVENCODI
                 AND INSTR(E.EVENCATE,'.') != 0
                 AND SUBSTR(E.EVENCATE,1,INSTR(E.EVENCATE,'.') -1) IN ('2','3')
                 AND F.MINUFINA IS NOT NULL
                 AND F.MAQUCODI LIKE 'IMPRESORA%'
               GROUP BY F.EMPRESA, F.NUMEOTRE) TIMP_CM,
               --
              (SELECT F.EMPRESA, F.NUMEOTRE, TO_CHAR(SUM(F.MINUFINA-F.MINUINIC)) MINUTOS
               FROM PRD_PRMAEVEN F, PRD_EVENTOS E
               WHERE F.EMPRESA = E.EMPRESA
                 AND F.EVENTIPO = E.EVENTIPO
                 AND F.EVENCODI = E.EVENCODI
                 AND INSTR(E.EVENCATE,'.') != 0
                 AND SUBSTR(E.EVENCATE,1,INSTR(E.EVENCATE,'.') -1) IN ('2','3')
                 AND F.MINUFINA IS NOT NULL
                 AND F.MAQUCODI LIKE 'CORTADORA%'
               GROUP BY F.EMPRESA, F.NUMEOTRE) TCOR_CM,
               --
              (SELECT F.EMPRESA, F.NUMEOTRE, TO_CHAR(SUM(F.MINUFINA-F.MINUINIC)) MINUTOS
               FROM PRD_PRMAEVEN F, PRD_EVENTOS E
               WHERE F.EMPRESA = E.EMPRESA
                 AND F.EVENTIPO = E.EVENTIPO
                 AND F.EVENCODI = E.EVENCODI
                 AND INSTR(E.EVENCATE,'.') != 0
                 AND SUBSTR(E.EVENCATE,1,INSTR(E.EVENCATE,'.') -1) IN ('2','3')
                 AND F.MINUFINA IS NOT NULL
                 AND F.MAQUCODI LIKE 'LAMINADORA%'
               GROUP BY F.EMPRESA, F.NUMEOTRE) TLAM_CM,
               --
              (SELECT F.EMPRESA, F.NUMEOTRE, TO_CHAR(SUM(F.MINUFINA-F.MINUINIC)) MINUTOS
               FROM PRD_PRMAEVEN F, PRD_EVENTOS E
               WHERE F.EMPRESA = E.EMPRESA
                 AND F.EVENTIPO = E.EVENTIPO
                 AND F.EVENCODI = E.EVENCODI
                 AND INSTR(E.EVENCATE,'.') != 0
                 AND SUBSTR(E.EVENCATE,1,INSTR(E.EVENCATE,'.') -1) IN ('2','3')
                 AND F.MINUFINA IS NOT NULL
                 AND F.MAQUCODI LIKE 'LAQUEADORA%'
               GROUP BY F.EMPRESA, F.NUMEOTRE) TLAQ_CM,
               --
              (SELECT DISTINCT EMPRESA, NUMEOTRE, 'PARTICIPACION' PARTICIPACION
               FROM PRD_PRMAEVEN
               WHERE TRIM(SUBSTR(MAQUCODI,1,INSTR(MAQUCODI,' '))) = 'IMPRESORA' AND EVENTIPO = P_UTILIDAD.F_VALODEVA('TIEVMAQU')) PMON_CM,

              (SELECT EMPRESA, NUMEOTRE, SUM(CANTPROD) CANTPROD
               FROM PRD_PASAMAQU
               WHERE MAQUCODI LIKE 'IMPRESORA%'
               GROUP BY EMPRESA, NUMEOTRE, TRIM(SUBSTR(MAQUCODI,1,INSTR(MAQUCODI,' ')))) MIMP_CM,
              (SELECT EMPRESA, NUMEOTRE, SUM(CANTPROD) CANTPROD
               FROM PRD_PASAMAQU
               WHERE MAQUCODI LIKE 'CORTADORA%'
               GROUP BY EMPRESA, NUMEOTRE, TRIM(SUBSTR(MAQUCODI,1,INSTR(MAQUCODI,' ')))) MCOR_CM,
              (SELECT EMPRESA, NUMEOTRE, SUM(CANTPROD) CANTPROD
               FROM PRD_PASAMAQU
               WHERE MAQUCODI LIKE 'LAMINADORA%'
               GROUP BY EMPRESA, NUMEOTRE, TRIM(SUBSTR(MAQUCODI,1,INSTR(MAQUCODI,' ')))) MLAM_CM,
              (SELECT EMPRESA, NUMEOTRE, SUM(CANTPROD) CANTPROD
               FROM PRD_PASAMAQU
               WHERE MAQUCODI LIKE 'LAQUEADORA%'
               GROUP BY EMPRESA, NUMEOTRE, TRIM(SUBSTR(MAQUCODI,1,INSTR(MAQUCODI,' ')))) MLAQ_CM,
            
              (
               SELECT F.EMPRESA, F.TIP_ARTI, F.PRODUCTO, F.MODI, F.REVI, F.ANCHO, F.LARGO, F.MATBASE, L.FCKG, L.DESCRIPCION FROM HFICTEC F, LFS L
               WHERE F.EMPRESA = L.EMPRESA
                 AND F.MATBASE = L.COD_LFS
               UNION
               SELECT F.EMPRESA, F.TIP_ARTI, F.PRODUCTO, F.MODI, F.REVI, F.ANCHO, F.LARGO, F.MATBASE, L.FCKG, L.DESCRIPCION FROM FIC_SEGESTI F, LFS L
               WHERE F.EMPRESA = L.EMPRESA
                 AND F.MATBASE = L.COD_LFS
              ) FI,
              (SELECT CP.EMPRESA, CP.NUMEPEDI, NULL REFEENPM, CP.DIREENVI, DE.PAIS, DE.NOMBRE
               FROM FIC_CABEPEDI CP, 
                    (SELECT DE.EMPRESA, DE.CLIENTE_ID, DE.LINEA, DE.PAIS, PA.NOMBRE FROM GNR_CLDIRENV DE, GNR_PAISES PA
                     WHERE DE.PAIS = PA.PAIS(+)) DE
               WHERE CP.EMPRESA = DE.EMPRESA(+)
                 AND CP.CLIENTE_ID = DE.CLIENTE_ID(+)
                 AND CP.DIREENVI = DE.LINEA(+)
               UNION
               SELECT CP.EMPRESA, CP.NUMEPEDI, NULL REFEENPM, CP.DIREENVI, DE.PAIS, DE.NOMBRE
               FROM FIC_HICAPEVE CP, 
                    (SELECT DE.EMPRESA, DE.CLIENTE_ID, DE.LINEA, DE.PAIS, PA.NOMBRE FROM GNR_CLDIRENV DE, GNR_PAISES PA
                     WHERE DE.PAIS = PA.PAIS(+)) DE
               WHERE CP.EMPRESA = DE.EMPRESA(+)
                 AND CP.CLIENTE_ID = DE.CLIENTE_ID(+)
                 AND CP.DIREENVI = DE.LINEA(+)
               UNION
               SELECT CP.EMPRESA, CP.NUMEPEDI, CP.REFEENPM, NULL DIREENVI, NULL PAIS, NULL NOMBRE FROM FIC_CABEPEMA CP) P,
              (SELECT EMPRESA, NUMERO, ANNO, VALOR FROM FIC_LICHOBOT
               WHERE CODIGO = P_Utilidad.F_ValoDeva('COOTPEPC')) MPC,
              (SELECT EMPRESA, NUMEPEDI, LINEPEDI, TIPOPEDI FROM FIC_LINEPEDI
               UNION 
               SELECT EMPRESA, NUMEPEDI, LINEPEDI, TIPOPEDI FROM FIC_HILIPEVE
               UNION
               SELECT EMPRESA, NUMEPEDI, LINEPEDI, TIPOPEDI FROM FIC_LINEPEMA) LP
         WHERE O.EMPRESA = A.EMPRESA
           AND O.TIP_ARTI = A.TIP_ARTI
           AND O.COD_ARTI = A.COD_ARTI
           AND O.EMPRESA = P.EMPRESA(+)
           AND O.NUMEPEDI = P.NUMEPEDI(+)
           AND O.EMPRESA = MPC.EMPRESA(+)
           AND O.NUMERO = MPC.NUMERO(+)
           AND O.ANNO = MPC.ANNO(+)
           AND O.EMPRESA = LP.EMPRESA(+)
           AND O.NUMEPEDI = LP.NUMEPEDI(+)
           AND O.LINEPEDI = LP.LINEPEDI(+)
           AND A.EMPRESA = CL.EMPRESA(+)
           AND A.CLIENASOC = CL.CLIENTE_ID(+)
           AND O.EMPRESA = FI.EMPRESA(+)
           AND O.TIP_ARTI = FI.TIP_ARTI(+)
           AND O.COD_ARTI = FI.PRODUCTO(+)
           AND NVL(O.MODI,0) = NVL(FI.MODI(+),0)
           AND NVL(O.REVI,0) = NVL(FI.REVI(+),0)
           AND SUBSTR(FI.MATBASE,1,2) = LIN.LINEA

           AND O.EMPRESA = TIMP_CM.EMPRESA(+)
           AND O.NUMERO = TIMP_CM.NUMEOTRE(+)
           AND O.EMPRESA = TLAM_CM.EMPRESA(+)
           AND O.NUMERO = TLAM_CM.NUMEOTRE(+)
           AND O.EMPRESA = TLAQ_CM.EMPRESA(+)
           AND O.NUMERO = TLAQ_CM.NUMEOTRE(+)
           AND O.EMPRESA = TCOR_CM.EMPRESA(+)
           AND O.NUMERO = TCOR_CM.NUMEOTRE(+)

           AND O.EMPRESA = PMON_CM.EMPRESA(+)
           AND O.NUMERO = PMON_CM.NUMEOTRE(+)

           AND O.EMPRESA = MIMP_CM.EMPRESA(+)
           AND O.NUMERO = MIMP_CM.NUMEOTRE(+)
           AND O.EMPRESA = MLAM_CM.EMPRESA(+)
           AND O.NUMERO = MLAM_CM.NUMEOTRE(+)
           AND O.EMPRESA = MLAQ_CM.EMPRESA(+)
           AND O.NUMERO = MLAQ_CM.NUMEOTRE(+)
           AND O.EMPRESA = MCOR_CM.EMPRESA(+)
           AND O.NUMERO = MCOR_CM.NUMEOTRE(+)

           AND TO_CHAR(O.FEC_MODI,'YYYY') = COSE_IMP.ANNO(+)
           AND COSE_IMP.DESCRIPCION_SECCION(+) = 'IMPRESORA'
           AND TO_CHAR(O.FEC_MODI,'YYYY') = COSE_COR.ANNO(+)
           AND COSE_COR.DESCRIPCION_SECCION(+) = 'CORTADORA'
           AND TO_CHAR(O.FEC_MODI,'YYYY') = COSE_LAM.ANNO(+)
           AND COSE_LAM.DESCRIPCION_SECCION(+) = 'LAMINADORA'
           AND TO_CHAR(O.FEC_MODI,'YYYY') = COSE_LAQ.ANNO(+)
           AND COSE_LAQ.DESCRIPCION_SECCION(+) = 'LAQUEADORA'
           AND TO_CHAR(O.FEC_MODI,'YYYY') = COSE_MON.ANNO(+)
           AND COSE_MON.DESCRIPCION_SECCION(+) = 'MONTAJE';