CREATE OR REPLACE VIEW ANALESTA.ANE_MOP AS
  SELECT O.EMPRESA, F.CLIENTE_ID N_CLIENTE, C.RAZON_SOC CLIENTE, O.NUMERO OT, DECODE(O.SITUACIO,'C',O.FEC_MODI) FECHA_CIERRE_OT, O.NUMEPEDI N_PEDIDO,
         DECODE(O.TIP_ARTI,P_UTILIDAD.F_VALODEVA('TIARFIF4'),DECODE(SUBSTR(O.COD_ARTI,3,1),P_UTILIDAD.F_VALODEVA('TIPOPROY'),'ANONIMA','IMPRESA')) IMPRESA_ANONIMA,
         O.COD_ARTI ESPECIALIDAD, SUBSTR(F.MATBASE,1,2) LINEA, F.MATBASE LFS, O.TIP_ARTI TIPO_PRODUCTO,
         DECODE((SELECT 'X' FROM PRD_HCABEOTR OTC WHERE OTC.EMPRESA = O.EMPRESA AND OTC.NUMEOTRE = O.NUMERO),NULL,
                 (SELECT COUNT(*) FASES FROM PRD_MAQURUTA MR
                  WHERE NOT EXISTS (SELECT 'X' FROM PRD_HCABEOTR OTC WHERE OTC.EMPRESA = MR.EMPRESA AND OTC.NUMEOTRE = MR.NUMEOTRE)
                    AND MR.EMPRESA = O.EMPRESA
                    AND MR.NUMEOTRE = O.NUMERO
                    AND MR.MAQUCODI != P_UTILIDAD.F_VALODEVA('MAQUALMA')),
                 (SELECT COUNT(*) FASES FROM PRD_HMAQURUT MR
                  WHERE MR.EMPRESA = O.EMPRESA
                    AND MR.NUMEOTRE = O.NUMERO
                    AND MR.MAQUCODI != P_UTILIDAD.F_VALODEVA('MAQUALMA'))
                 ) CANTIDAD_DE_FASES,
         MA.CONTADOR IDENTIFICACION_DEL_N_DE_FASE,
         DECODE(INSTR(MA.MAQUCODI,'CORTADORA'),1,'Sección Cortadoras',DECODE(INSTR(MA.MAQUCODI,'IMPRESORA'),1,'Sección Impresoras',DECODE(INSTR(MA.MAQUCODI,'LAMINADORA'),1,'Sección Laminadoras',DECODE(INSTR(MA.MAQUCODI,'LAQUEADORA'),1,'Sección Laqueadoras')))) SECCION_PRODUCTIVA,
         MA.MAQUCODI MAQUINA,
         SUM(E.MINUFINA-MINUINIC)/60 HORAS_PRODUCCION_MAQUINA
  FROM FIC_CABEOTRE O, 
       CLIENTES C,
       HFICTEC F,
       (SELECT MR.EMPRESA, MR.NUMEOTRE, MR.FASESEQU, MR.MAQUTIPO, MR.MAQUCODI, MR.CONTADOR FROM PRD_MAQURUTA MR
        WHERE NOT EXISTS (SELECT 'X' FROM PRD_HCABEOTR OTC WHERE OTC.EMPRESA = MR.EMPRESA AND OTC.NUMEOTRE = MR.NUMEOTRE)
        UNION
        SELECT MR.EMPRESA, MR.NUMEOTRE, MR.FASESEQU, MR.MAQUTIPO, MR.MAQUCODI, MR.CONTADOR FROM PRD_HMAQURUT MR) MA,
       PRD_PRMAEVEN E, PRD_PRMAEVCO EC
  WHERE O.EMPRESA = F.EMPRESA
    AND O.TIP_ARTI = F.TIP_ARTI
    AND O.COD_ARTI = F.PRODUCTO
    AND O.MODI = F.MODI
    AND O.REVI = F.REVI
    AND F.EMPRESA = C.EMPRESA
    AND F.CLIENTE_ID = C.CLIENTE_ID
    AND O.EMPRESA = MA.EMPRESA
    AND O.NUMERO = MA.NUMEOTRE
    AND E.EMPRESA = EC.EMPRESA
    AND E.MAQUTIPO = EC.MAQUTIPO
    AND E.NUMEOTRE = EC.NUMEOTRE
    AND E.MAQUCODI = EC.MAQUCODI
    AND E.EVENCODI = EC.EVENCODI
    AND E.EVENTIPO = EC.EVENTIPO
    AND E.CONTADOR = EC.CONTADOR
    AND E.MINUFINA IS NOT NULL
    AND EC.EMPRESA = MA.EMPRESA
    AND EC.NUMEOTRE = MA.NUMEOTRE
    AND EC.CONTMAQU = MA.CONTADOR
    
    --AND O.NUMEPEDI LIKE '2016%'
  GROUP BY O.EMPRESA, F.CLIENTE_ID, C.RAZON_SOC, O.NUMERO, DECODE(O.SITUACIO,'C',O.FEC_MODI), O.NUMEPEDI,
           DECODE(O.TIP_ARTI,P_UTILIDAD.F_VALODEVA('TIARFIF4'),DECODE(SUBSTR(O.COD_ARTI,3,1),P_UTILIDAD.F_VALODEVA('TIPOPROY'),'ANONIMA','IMPRESA')),
           O.COD_ARTI, SUBSTR(F.MATBASE,1,2), F.MATBASE, O.TIP_ARTI,
         MA.CONTADOR,
         DECODE(INSTR(MA.MAQUCODI,'CORTADORA'),1,'Sección Cortadoras',DECODE(INSTR(MA.MAQUCODI,'IMPRESORA'),1,'Sección Impresoras',DECODE(INSTR(MA.MAQUCODI,'LAMINADORA'),1,'Sección Laminadoras',DECODE(INSTR(MA.MAQUCODI,'LAQUEADORA'),1,'Sección Laqueadoras')))),
         MA.MAQUCODI
    ORDER BY O.EMPRESA, O.NUMERO, MA.CONTADOR;
/
    
SELECT * FROM PRD_PRMAEVEN E, PRD_PRMAEVCO EC
WHERE E.EMPRESA = EC.EMPRESA
  AND E.MAQUTIPO = EC.MAQUTIPO
  AND E.NUMEOTRE = EC.NUMEOTRE
  AND E.MAQUCODI = EC.MAQUCODI
  AND E.EVENCODI = EC.EVENCODI
  AND E.EVENTIPO = EC.EVENTIPO
  AND E.CONTADOR = EC.CONTADOR
  AND E.MINUFINA IS NOT NULL;

SELECT DISTINCT MAQUCODI FROM PRD_HMAQURUT;

SELECT * FROM DM_LISTPROD.DM_LP_HE_DATOS_DE_PRODUCCION WHERE ID_ORDEN_TRABAJO LIKE '10_2016%';