--EX, ABO, OABO, PRE, PCFI, OPCI
--MIMP, MLAM, MLAQ. MCOR. MMON, NUCA, TIMP, TLAM, TLAQ, TCOR, TMON
  CREATE OR REPLACE VIEW "ANALESTA"."ANE_ORDENES_DE_TRABAJO_P2" AS 
  SELECT O.EMPRESA, O.NUMERO NUMERO_OT, O.ANNO ANNO_OT, O.SITUACIO, O.FEC_MODI FECHA_MODIFICACION_OT, TO_CHAR(O.FEC_MODI,'YYYY') ANNO_MODIFICACION_OT, TO_CHAR(O.FEC_MODI,'MM') MES_MODIFICACION_OT,
         CL.CLIENTE_ID, CL.RAZON_SOC, CL.VENDEDOR, CL.TIPO_VENDEDOR, CL.DESCRIPCION_VENEDEDOR, CL.VENCIMIENTO_FX,
         O.TIP_ARTI TIP_ARTI_OT, O.COD_ARTI COD_ARTI_OT, A.DESCRIPCION DESCRIPCION_ARTICULO_OT, O.MODI MODIFICACION, O.REVI REVISION, DECODE(O.TIP_ARTI,P_Utilidad.F_ValoDeva('TIARFIF4'), DECODE(SUBSTR(O.COD_ARTI,3,1), P_Utilidad.F_ValoDeva('TIPOPROY'), 'ANONIMO', 'IMPRESO')) TIPO_ARTICULO,
         P_GNR_AGRUESTR.F_ASIGNA_AGRUESTR(O.EMPRESA, SUBSTR(O.COD_ARTI,4,4),O.TIP_ARTI, O.COD_ARTI) AGRUPACION_ESTRATEGICA,
         O.NUMEPEDI PEDIDO_OT, O.LINEPEDI LINEA_PEDIDO_OT, NVL(LP.TIPOPEDI,'NE') TIPO_DE_PEDIDO, P.REFEENPM REFERENCIA_PEDIDO_MATRIZ_OT, 
         P.DIREENVI CODIGO_DIRECCION_ENVIO, P.PAIS CODIGO_PAIS_DIREC_ENVIO_PEDIDO, P.NOMBRE PAIS_DIREC_ENVIO_PEDIDO, CL.PAIS CODIGO_PAIS_CLIENTE, CL.DESCRIPCION_PAIS PAIS_CLIENTE, 
         DECODE(P.PAIS, NULL,CL.PAIS,P.PAIS) CODIGO_PAIS_ENTREGA, DECODE(P.NOMBRE, NULL,CL.DESCRIPCION_PAIS,P.NOMBRE) PAIS_ENTREGA, DECODE(DECODE(P.PAIS, NULL,CL.PAIS,P.PAIS),NULL,'N',P_Utilidad.F_ValoDeva('PAISESPA'),'N','E') TIPO_PEDIDO,
         O.CANTCERR CANTIDAD_CERRADA_OT, O.UNIDAD UNIDAD_CERRADA_OT, 
         DECODE(O.UNIDAD,P_Utilidad.F_ValoDeva('TIPOUNML'),1,DECODE(NVL(FI.ANCHO,0),0,0,DECODE(O.UNIDAD,P_Utilidad.F_ValoDeva('TIPOUNKG'),FI.FCKG * (1000 / FI.ANCHO),
                                                                                                         P_Utilidad.F_ValoDeva('TIPOUNM2'),(1000 / FI.ANCHO),
                                                                                                         P_Utilidad.F_ValoDeva('TIPOUNUN'),(1000 / FI.ANCHO) * ((FI.ANCHO * FI.LARGO) / 1000000)))) FACTOR_ML_CIERRE_OT_FX, 
         O.CANTCERR * 
         DECODE(O.UNIDAD,P_Utilidad.F_ValoDeva('TIPOUNML'),1,DECODE(NVL(FI.ANCHO,0),0,0,DECODE(O.UNIDAD,P_Utilidad.F_ValoDeva('TIPOUNKG'),FI.FCKG * (1000 / FI.ANCHO),
                                                                                                         P_Utilidad.F_ValoDeva('TIPOUNM2'),(1000 / FI.ANCHO),
                                                                                                         P_Utilidad.F_ValoDeva('TIPOUNUN'),(1000 / FI.ANCHO) * ((FI.ANCHO * FI.LARGO) / 1000000))))
         CANTIDAD_CERRADA_OT_ML,
         DECODE(O.UNIDAD,P_Utilidad.F_ValoDeva('TIPOUNM2'),1,P_Utilidad.F_ValoDeva('TIPOUNKG'),FI.FCKG,
                                                               P_Utilidad.F_ValoDeva('TIPOUNML'),(FI.ANCHO / 1000),
                                                               P_Utilidad.F_ValoDeva('TIPOUNUN'),(FI.ANCHO * FI.LARGO) / 1000000) FACTOR_M2_CIERRE_OT_FX,
         O.CANTCERR *
         DECODE(O.UNIDAD,P_Utilidad.F_ValoDeva('TIPOUNM2'),1,P_Utilidad.F_ValoDeva('TIPOUNKG'),FI.FCKG,
                                                               P_Utilidad.F_ValoDeva('TIPOUNML'),(FI.ANCHO / 1000),
                                                               P_Utilidad.F_ValoDeva('TIPOUNUN'),(FI.ANCHO * FI.LARGO) / 1000000)
         CANTIDAD_CERRADA_OT_M2,
         O.NUMEOTTE NUMERO_OTT, O.ANNOOTTE ANNO_OTT,
         NVL(MPC.VALOR,'N') MATERIAL_PROPIEDAD_CLIENTE,
         FI.ANCHO, FI.LARGO, FI.MATBASE, FI.DESCRIPCION DESCRIPCION_MATBASE, SUBSTR(FI.MATBASE,1,2) LINEA, LIN.DESCRIPCION DESCRIPCION_LINEA,
-------------------------- 
--Vista 2
                MIMP.CANTPROD CANTPROD_IMPRESORA_CAL_VEL, TIMP.MINUTOS MINUTOS_IMPRESORA_CAT3, DECODE(NVL(TIMP.MINUTOS,0),0,NULL,MIMP.CANTPROD/TIMP.MINUTOS) VELOCIDAD_IMPRESORA_FX,
                MLAM.CANTPROD CANTPROD_LAMINADORA_CAL_VEL, TLAM.MINUTOS MINUTOS_LAMINADORA_CAT3, DECODE(NVL(TLAM.MINUTOS,0),0,NULL,MLAM.CANTPROD/TLAM.MINUTOS) VELOCIDAD_LAMINADORA_FX, 
                MLAQ.CANTPROD CANTPROD_LAQUEADORA_CAL_VEL, TLAQ.MINUTOS MINUTOS_LAQUEADORA_CAT3, DECODE(NVL(TLAQ.MINUTOS,0),0,NULL,MLAQ.CANTPROD/TLAQ.MINUTOS) VELOCIDAD_LAQUEADORA_FX, 
                MCOR.CANTPROD CANTPROD_CORTADORA_CAL_VEL, TCOR.MINUTOS MINUTOS_CORTADORA_CAT3, DECODE(NVL(TCOR.MINUTOS,0),0,NULL,MCOR.CANTPROD/TCOR.MINUTOS) VELOCIDAD_CORTADORA_FX,
                MMON.CANTPROD CANTPROD_MONTAJE_CAL_VEL, TMON.MINUTOS MINUTOS_MONTAJE_CAT3, 
                NVL(NUCA.NUMERO_CAPAS,0) + 1 NUMERO_CAPAS--,
-- Fin Vista 2
         FROM FIC_CABEOTRE O, ARTICULO A, ANALESTA.ANE_CLIENTES CL, GNR_LINEAS LIN,
--Vista 2
              (SELECT EMPRESA, NUMERO, COUNT(*) NUMERO_CAPAS
               FROM FIC_LINEOTRE  
                  WHERE COD_ARES LIKE ('LAMINADORA%')
               GROUP BY EMPRESA, NUMERO) NUCA,
--              
              (SELECT F.EMPRESA, F.NUMEOTRE, 
                      SUM(F.MINUFINA-F.MINUINIC) MINUTOS
               FROM PRD_PRMAEVEN F, PRD_EVENTOS E
                  WHERE F.EMPRESA = E.EMPRESA
                    AND F.EVENTIPO = E.EVENTIPO
                    AND F.EVENCODI = E.EVENCODI
                    AND INSTR(E.EVENCATE,'.') != 0
                    AND SUBSTR(E.EVENCATE,1,INSTR(E.EVENCATE,'.') -1) = '3'
                    AND F.MINUFINA IS NOT NULL
                    AND F.MAQUCODI LIKE 'IMPRESORA%'
               GROUP BY F.EMPRESA, F.NUMEOTRE) TIMP,
              (SELECT F.EMPRESA, F.NUMEOTRE, 
                      SUM(F.MINUFINA-F.MINUINIC) MINUTOS
               FROM PRD_PRMAEVEN F, PRD_EVENTOS E
                  WHERE F.EMPRESA = E.EMPRESA
                    AND F.EVENTIPO = E.EVENTIPO
                    AND F.EVENCODI = E.EVENCODI
                    AND INSTR(E.EVENCATE,'.') != 0
                    AND SUBSTR(E.EVENCATE,1,INSTR(E.EVENCATE,'.') -1) = '3'
                    AND F.MINUFINA IS NOT NULL
                    AND F.MAQUCODI LIKE 'LAMINADORA%'
               GROUP BY F.EMPRESA, F.NUMEOTRE) TLAM,
              (SELECT F.EMPRESA, F.NUMEOTRE, 
                      SUM(F.MINUFINA-F.MINUINIC) MINUTOS
               FROM PRD_PRMAEVEN F, PRD_EVENTOS E
                  WHERE F.EMPRESA = E.EMPRESA
                    AND F.EVENTIPO = E.EVENTIPO
                    AND F.EVENCODI = E.EVENCODI
                    AND INSTR(E.EVENCATE,'.') != 0
                    AND SUBSTR(E.EVENCATE,1,INSTR(E.EVENCATE,'.') -1) = '3'
                    AND F.MINUFINA IS NOT NULL
                    AND F.MAQUCODI LIKE 'LAQUEADORA%'
               GROUP BY F.EMPRESA, F.NUMEOTRE) TLAQ,
              (SELECT F.EMPRESA, F.NUMEOTRE, 
                      SUM(F.MINUFINA-F.MINUINIC) MINUTOS
               FROM PRD_PRMAEVEN F, PRD_EVENTOS E
                  WHERE F.EMPRESA = E.EMPRESA
                    AND F.EVENTIPO = E.EVENTIPO
                    AND F.EVENCODI = E.EVENCODI
                    AND INSTR(E.EVENCATE,'.') != 0
                    AND SUBSTR(E.EVENCATE,1,INSTR(E.EVENCATE,'.') -1) = '3'
                    AND F.MINUFINA IS NOT NULL
                    AND F.MAQUCODI LIKE 'MONTAJE%'
               GROUP BY F.EMPRESA, F.NUMEOTRE) TMON,
              (SELECT F.EMPRESA, F.NUMEOTRE, 
                      SUM(F.MINUFINA-F.MINUINIC) MINUTOS
               FROM PRD_PRMAEVEN F, PRD_EVENTOS E
                  WHERE F.EMPRESA = E.EMPRESA
                    AND F.EVENTIPO = E.EVENTIPO
                    AND F.EVENCODI = E.EVENCODI
                    AND INSTR(E.EVENCATE,'.') != 0
                    AND SUBSTR(E.EVENCATE,1,INSTR(E.EVENCATE,'.') -1) = '3'
                    AND F.MINUFINA IS NOT NULL
                    AND F.MAQUCODI LIKE 'CORTADORA%'
               GROUP BY F.EMPRESA, F.NUMEOTRE) TCOR,
--              
              (SELECT P.EMPRESA, P.NUMEOTRE, 
                      SUM(P.CANTPROD) CANTPROD
               FROM PRD_PASAMAQU P
               WHERE P.MAQUCODI LIKE 'IMPRESORA%'
               GROUP BY P.EMPRESA, P.NUMEOTRE) MIMP,
              (SELECT P.EMPRESA, P.NUMEOTRE, 
                      SUM(P.CANTPROD) CANTPROD
               FROM PRD_PASAMAQU P
               WHERE P.MAQUCODI LIKE 'LAMINADORA%'
               GROUP BY P.EMPRESA, P.NUMEOTRE) MLAM,
              (SELECT P.EMPRESA, P.NUMEOTRE, 
                      SUM(P.CANTPROD) CANTPROD
               FROM PRD_PASAMAQU P
               WHERE P.MAQUCODI LIKE 'LAQUEADORA%'
               GROUP BY P.EMPRESA, P.NUMEOTRE) MLAQ,
              (SELECT P.EMPRESA, P.NUMEOTRE, 
                      SUM(P.CANTPROD) CANTPROD
               FROM PRD_PASAMAQU P
               WHERE P.MAQUCODI LIKE 'MONTAJE%'
               GROUP BY P.EMPRESA, P.NUMEOTRE) MMON,
              (SELECT P.EMPRESA, P.NUMEOTRE, 
                      SUM(DECODE(MARCPASA,'S',0,P.CANTPROD)) CANTPROD
               FROM PRD_PASAMAQU P
               WHERE P.MAQUCODI LIKE 'CORTADORA%'
               GROUP BY P.EMPRESA, P.NUMEOTRE) MCOR,
--Fin Vista 2
              (
               SELECT F.EMPRESA, F.TIP_ARTI, F.PRODUCTO, F.MODI, F.REVI, F.ANCHO, F.LARGO, F.MATBASE, L.FCKG, L.DESCRIPCION FROM HFICTEC F, LFS L
               WHERE F.EMPRESA = L.EMPRESA
                 AND F.MATBASE = L.COD_LFS
               UNION
               SELECT F.EMPRESA, F.TIP_ARTI, F.PRODUCTO, F.MODI, F.REVI, F.ANCHO, F.LARGO, F.MATBASE, L.FCKG, L.DESCRIPCION FROM FIC_SEGESTI F, LFS L
               WHERE F.EMPRESA = L.EMPRESA
                 AND F.MATBASE = L.COD_LFS
              ) FI,
              (SELECT CP.EMPRESA, CP.NUMEPEDI, NULL REFEENPM, CP.DIREENVI, DE.PAIS, DE.NOMBRE
               FROM FIC_CABEPEDI CP, 
                    (SELECT DE.EMPRESA, DE.CLIENTE_ID, DE.LINEA, DE.PAIS, PA.NOMBRE FROM GNR_CLDIRENV DE, GNR_PAISES PA
                     WHERE DE.PAIS = PA.PAIS(+)) DE
               WHERE CP.EMPRESA = DE.EMPRESA(+)
                 AND CP.CLIENTE_ID = DE.CLIENTE_ID(+)
                 AND CP.DIREENVI = DE.LINEA(+)
               UNION
               SELECT CP.EMPRESA, CP.NUMEPEDI, NULL REFEENPM, CP.DIREENVI, DE.PAIS, DE.NOMBRE
               FROM FIC_HICAPEVE CP, 
                    (SELECT DE.EMPRESA, DE.CLIENTE_ID, DE.LINEA, DE.PAIS, PA.NOMBRE FROM GNR_CLDIRENV DE, GNR_PAISES PA
                     WHERE DE.PAIS = PA.PAIS(+)) DE
               WHERE CP.EMPRESA = DE.EMPRESA(+)
                 AND CP.CLIENTE_ID = DE.CLIENTE_ID(+)
                 AND CP.DIREENVI = DE.LINEA(+)
               UNION
               SELECT CP.EMPRESA, CP.NUMEPEDI, CP.REFEENPM, NULL DIREENVI, NULL PAIS, NULL NOMBRE FROM FIC_CABEPEMA CP) P,
              (SELECT EMPRESA, NUMERO, ANNO, VALOR FROM FIC_LICHOBOT
               WHERE CODIGO = P_Utilidad.F_ValoDeva('COOTPEPC')) MPC,
              (SELECT EMPRESA, NUMEPEDI, LINEPEDI, TIPOPEDI FROM FIC_LINEPEDI
               UNION 
               SELECT EMPRESA, NUMEPEDI, LINEPEDI, TIPOPEDI FROM FIC_HILIPEVE
               UNION
               SELECT EMPRESA, NUMEPEDI, LINEPEDI, TIPOPEDI FROM FIC_LINEPEMA) LP
         WHERE O.EMPRESA = A.EMPRESA
           AND O.TIP_ARTI = A.TIP_ARTI
           AND O.COD_ARTI = A.COD_ARTI
           AND O.EMPRESA = P.EMPRESA(+)
           AND O.NUMEPEDI = P.NUMEPEDI(+)
           AND O.EMPRESA = MPC.EMPRESA(+)
           AND O.NUMERO = MPC.NUMERO(+)
           AND O.ANNO = MPC.ANNO(+)
           AND O.EMPRESA = LP.EMPRESA(+)
           AND O.NUMEPEDI = LP.NUMEPEDI(+)
           AND O.LINEPEDI = LP.LINEPEDI(+)
           AND A.EMPRESA = CL.EMPRESA(+)
           AND A.CLIENASOC = CL.CLIENTE_ID(+)
           AND O.EMPRESA = FI.EMPRESA(+)
           AND O.TIP_ARTI = FI.TIP_ARTI(+)
           AND O.COD_ARTI = FI.PRODUCTO(+)
           AND NVL(O.MODI,0) = NVL(FI.MODI(+),0)
           AND NVL(O.REVI,0) = NVL(FI.REVI(+),0)
           AND SUBSTR(FI.MATBASE,1,2) = LIN.LINEA
--Vista 2          
           AND O.EMPRESA = MIMP.EMPRESA(+)
           AND O.NUMERO = MIMP.NUMEOTRE(+)
           AND O.EMPRESA = MLAQ.EMPRESA(+)
           AND O.NUMERO = MLAQ.NUMEOTRE(+)
           AND O.EMPRESA = MLAM.EMPRESA(+)
           AND O.NUMERO = MLAM.NUMEOTRE(+)
           AND O.EMPRESA = MMON.EMPRESA(+)
           AND O.NUMERO = MMON.NUMEOTRE(+)
           AND O.EMPRESA = MCOR.EMPRESA(+)
           AND O.NUMERO = MCOR.NUMEOTRE(+)
--
           AND O.EMPRESA = TIMP.EMPRESA(+)
           AND O.NUMERO = TIMP.NUMEOTRE(+)
           AND O.EMPRESA = TLAQ.EMPRESA(+)
           AND O.NUMERO = TLAQ.NUMEOTRE(+)
           AND O.EMPRESA = TLAM.EMPRESA(+)
           AND O.NUMERO = TLAM.NUMEOTRE(+)
           AND O.EMPRESA = TMON.EMPRESA(+)
           AND O.NUMERO = TMON.NUMEOTRE(+)
           AND O.EMPRESA = TCOR.EMPRESA(+)
           AND O.NUMERO = TCOR.NUMEOTRE(+)
--
           AND O.EMPRESA = NUCA.EMPRESA(+)
           AND O.NUMERO = NUCA.NUMERO(+);
--Fin Vista 2
