--------------------------------------------------------
--  DDL for View ANE_ESTRUC_LAMIN_COST_OT
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "ANALESTA"."ANE_ESTRUC_LAMIN_COST_OT" ("EMPRESA", "NUMEOTRE", "LINEA", "DESCRIPCION_LINEA", "PASADA", "TIP_ARTI", "COD_ARTI", "DESCRIPCION", "GRAMOSM2", "PRECIO", "TRAZA_PRECIO", "TIP_ARTI_OT", "COD_ARTI_OT", "DESCRIPCION_ARTICULO_OT", "CANTIDAD_CIERRE_ALBARAN_M2", "CANTIDAD_CERRADA_OT_M2", "COSTE_FX") AS 
  SELECT M.EMPRESA, M.NUMEOTRE, M.LINETIPR LINEA, LI.DESCRIPCION DESCRIPCION_LINEA, M.DEFIPASA PASADA, M.TIP_ARTI, M.COD_ARTI, A.DESCRIPCION, M.GRAMOSM2, 
          P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_PRECIO(M.EMPRESA, M.TIP_ARTI, M.COD_ARTI,O.FECHA_MODIFICACION_OT),'PRECIO') PRECIO,
          P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_PRECIO(M.EMPRESA, M.TIP_ARTI, M.COD_ARTI,O.FECHA_MODIFICACION_OT),'TRAZA') TRAZA_PRECIO, 
          O.TIP_ARTI_OT, O.COD_ARTI_OT, O.DESCRIPCION_ARTICULO_OT, O.CANTIDAD_CIERRE_ALBARAN_M2, O.CANTIDAD_CERRADA_OT_M2,
          DECODE(O.TIP_ARTI_OT,P_Utilidad.F_ValoDeva('TIARFIF4'),
          (((O.CANTIDAD_CIERRE_ALBARAN_M2 * M.GRAMOSM2) / 1000) * P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_PRECIO(M.EMPRESA, M.TIP_ARTI, M.COD_ARTI,O.FECHA_MODIFICACION_OT),'PRECIO')),
          (((O.CANTIDAD_CERRADA_OT_M2 * M.GRAMOSM2) / 1000) * P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_PRECIO(M.EMPRESA, M.TIP_ARTI, M.COD_ARTI,O.FECHA_MODIFICACION_OT),'PRECIO'))) COSTE_FX 
         FROM PRD_HCLAOTRE M, ARTICULO A, GNR_LINEAS LI, ANALESTA.ANE_ORDENES_DE_TRABAJO_T1 O
            WHERE M.LINETIPR = LI.LINEA
              AND M.EMPRESA = A.EMPRESA
              AND M.TIP_ARTI = A.TIP_ARTI
              AND M.COD_ARTI = A.COD_ARTI
              AND M.EMPRESA = O.EMPRESA
              AND M.NUMEOTRE = O.NUMERO_OT
              AND EXISTS (SELECT 'X' FROM PRD_CABEOTRE C
                           WHERE C.EMPRESA = M.EMPRESA
                             AND C.NUMEOTRE = M.NUMEOTRE
                             AND C.ESTADO != P_Utilidad.F_ValoDeva('ESTARECU'))
         UNION
   SELECT M.EMPRESA, M.NUMEOTRE, M.LINETIPR LINEA, LI.DESCRIPCION DESCRIPCION_LINEA, M.DEFIPASA PASADA, M.TIP_ARTI, M.COD_ARTI, A.DESCRIPCION, M.GRAMOSM2, 
          P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_PRECIO(M.EMPRESA, M.TIP_ARTI, M.COD_ARTI,O.FECHA_MODIFICACION_OT),'PRECIO') PRECIO,
          P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_PRECIO(M.EMPRESA, M.TIP_ARTI, M.COD_ARTI,O.FECHA_MODIFICACION_OT),'TRAZA') TRAZA_PRECIO, 
          O.TIP_ARTI_OT, O.COD_ARTI_OT, O.DESCRIPCION_ARTICULO_OT, O.CANTIDAD_CIERRE_ALBARAN_M2, O.CANTIDAD_CERRADA_OT_M2,
          DECODE(O.TIP_ARTI_OT,P_Utilidad.F_ValoDeva('TIARFIF4'),
          (((O.CANTIDAD_CIERRE_ALBARAN_M2 * M.GRAMOSM2) / 1000) * P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_PRECIO(M.EMPRESA, M.TIP_ARTI, M.COD_ARTI,O.FECHA_MODIFICACION_OT),'PRECIO')),
          (((O.CANTIDAD_CERRADA_OT_M2 * M.GRAMOSM2) / 1000) * P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_PRECIO(M.EMPRESA, M.TIP_ARTI, M.COD_ARTI,O.FECHA_MODIFICACION_OT),'PRECIO'))) COSTE_FX 
         FROM PRD_HCLAHOTR M, ARTICULO A, GNR_LINEAS LI, ANALESTA.ANE_ORDENES_DE_TRABAJO_T1 O
            WHERE M.LINETIPR = LI.LINEA
              AND M.EMPRESA = A.EMPRESA
              AND M.TIP_ARTI = A.TIP_ARTI
              AND M.COD_ARTI = A.COD_ARTI
              AND M.EMPRESA = O.EMPRESA
              AND M.NUMEOTRE = O.NUMERO_OT
              AND NOT EXISTS (SELECT 'X' FROM PRD_CABEOTRE C
                              WHERE C.EMPRESA = M.EMPRESA
                                AND C.NUMEOTRE = M.NUMEOTRE
                                AND C.ESTADO != P_Utilidad.F_ValoDeva('ESTARECU'));
