CREATE OR REPLACE VIEW ANALESTA.ANE_ESTRUCTURA_LAQUEADORA AS
SELECT C.MATBASE LFS, LI.DESCRIPCION DESCRIPCION_LFS, C.IDENTIFI IDENTIFICADOR, P.DEFIPASA PASADA, L.TIP_ARTI TIPO_ARTICULO, L.COD_ARTI ARTICULO, A.DESCRIPCION DESCRIPCION_ARTICULO, L.GRAMOSM2
FROM FIC_CAECLAQU C, LFS LI, FIC_PAECLAQU P, FIC_ESCOLAQU L, ARTICULO A
WHERE LI.EMPRESA IN (SELECT VALOR FROM VALORES_LISTA WHERE CODIGO = 'GNR_EMPRACGR')
  AND C.MATBASE = LI.COD_LFS
  AND C.MATBASE = P.MATBASE
  AND C.IDENTIFI = P.IDENTIFI
  AND L.DEFIPASA = P.DEFIPASA
  AND L.MATBASE = P.MATBASE
  AND L.IDENTIFI = P.IDENTIFI
  AND A.EMPRESA IN (SELECT VALOR FROM VALORES_LISTA WHERE CODIGO = 'GNR_EMPRACGR')
  AND L.TIP_ARTI = A.TIP_ARTI
  AND L.COD_ARTI = A.COD_ARTI;
