--CREATE OR REPLACE FORCE VIEW "ANALESTA"."ANE_ABON" AS
SELECT R.EMPRESA EMPRESA, 
R.CLIENTE_ID CLIENTE, C.RAZON_SOC NOMBRE_CLIENTE,
C.PAIS COD_APIS, C.NOMBRE PAIS,
V.VENDEDOR COD_COMERCIAL, V.NOMBRE_VENDEDOR COMERCIAL,
R.NUMEPEDI PEDIDO,
R.NUMELOTE OT, 

A.NUMEABON ABONO, 


P.FEC_ALTA F_PEDIDO,
DECODE(O.SITUACIO,'C',O.FEC_MODI) F_CIERRE_OT,
FAA.CFFALT F_ABONO,

AC.TIPOABON TIPO_ABONO, I.DESCRIPC DESCRIPCION_TIPO_DE_ABONO, I.PARAMETR ID_PARAMETRIZACION_ABONO, IP.DESCRIPC DESCRIPC_PARAMETRIZACION_ABONO,

R.NUMEFACT FACTURA_ASOCIADA,

F.TIP_ARTI TIPO_PRD, F.PRODUCTO ESPECIALIDAD, SUBSTR(F.MATBASE,1,2) LINEA, F.MATBASE LFS_ESPECIALIDAD, F.UNIDADVENTA U_VENTA,

         FAA.LFCANT * DECODE(F.UNIDADVENTA,P_Utilidad.F_ValoDeva('TIPOUNML'),1,DECODE(NVL(F.ANCHO,0),0,0,DECODE(F.UNIDADVENTA,P_Utilidad.F_ValoDeva('TIPOUNKG'),LFS.FCKG * (1000 / F.ANCHO),
                                                                                                        P_Utilidad.F_ValoDeva('TIPOUNM2'),(1000 / F.ANCHO),
                                                                                                        P_Utilidad.F_ValoDeva('TIPOUNUN'),(1000 / F.ANCHO) * ((F.ANCHO * F.LARGO) / 1000000)))) CANTIDAD_ML,
                                                                                                        
         FAA.LFCANT * DECODE(F.UNIDADVENTA,P_Utilidad.F_ValoDeva('TIPOUNKG'),1,DECODE(NVL(LFS.FCKG,0),0,0,DECODE(F.UNIDADVENTA,P_Utilidad.F_ValoDeva('TIPOUNML'),(1 / LFS.FCKG) * (F.ANCHO / 1000),
                                                                                                        P_Utilidad.F_ValoDeva('TIPOUNM2'),1 / LFS.FCKG,
                                                                                                        P_Utilidad.F_ValoDeva('TIPOUNUN'),(1 / LFS.FCKG) * ((F.ANCHO * F.LARGO) / 1000000)))) CANTIDAD_KG,
                                                                                                        
         FAA.LFCANT * DECODE(F.UNIDADVENTA,P_Utilidad.F_ValoDeva('TIPOUNM2'),1,P_Utilidad.F_ValoDeva('TIPOUNKG'),LFS.FCKG,
                                                             P_Utilidad.F_ValoDeva('TIPOUNML'),(F.ANCHO / 1000),
                                                             P_Utilidad.F_ValoDeva('TIPOUNUN'),(F.ANCHO * F.LARGO) / 1000000) CANTIDAD_M2,

         FAA.LFCANT * DECODE(F.UNIDADVENTA,P_Utilidad.F_ValoDeva('TIPOUNUN'),1,P_Utilidad.F_ValoDeva('TIPOUNML'),DECODE(NVL(F.ANCHO,0)*NVL(F.LARGO,0),0,0,(1 / ((1000 / F.ANCHO) * ((F.ANCHO * F.LARGO) / 1000000)))),
                                                                              P_Utilidad.F_ValoDeva('TIPOUNM2'),DECODE(NVL(F.ANCHO,0)*NVL(F.LARGO,0),0,0,(1000000 / (F.ANCHO * F.LARGO))),
                                                                              P_Utilidad.F_ValoDeva('TIPOUNKG'),DECODE(NVL(F.ANCHO,0)*NVL(F.LARGO,0)*NVL(LFS.FCKG,0),0,0,(1 / ((1 / LFS.FCKG) * ((F.ANCHO * F.LARGO) / 1000000))))) CANTIDAD_UN,

FAA.LFPREU PRECIO_ABONO,

SUM(NVL(A.IMPOABON,0)) EUROS_ABONO, --SUM(NVL(A.IMPONUFA,0)) IMPO_ABONO_NUEVA_FACTURA, SUM(NVL(A.IMPOABON,0) - NVL(A.IMPONUFA,0)) IMPO_ABONO_NETO_FX 

A.NUMEFACT FACTURA_DE_CARGO_1,
FC1.CFFALT F_FACTURA_DE_CARGO_1,
FC1.LFCANT CANTIDAD_CARGO_1,
FC1.LFPREU PRECIO_CARGO_1,
FC1.LFCANT*FC1.LFPREU EUROS_CARGO_1,

AC.NUMEFA02 FACTURA_DE_CARGO_2,
FC2.CFFALT F_FACTURA_DE_CARGO_2,
FC2.LFCANT CANTIDAD_CARGO_2,
FC2.LFPREU PRECIO_CARGO_2,
FC2.LFCANT*FC2.LFPREU EUROS_CARGO_2
                                                                                                        
FROM RCL_RECLCLIE R, --
     (SELECT A.*, R.TIP_ARTI, R.COD_ARTI, R.NUMEPEDI FROM RCL_ACCIONES A, RCL_RECLCLIE R
      WHERE R.EMPRESA = A.EMPRESA
        AND R.NUMERCL = A.NUMERCL
        AND R.ANNO = A.ANNO) A,--RCL_ACCIONES A, --
     (SELECT A.*, R.TIP_ARTI, R.COD_ARTI, R.NUMEPEDI FROM RCL_ACCICOMP A, RCL_RECLCLIE R
      WHERE R.EMPRESA = A.EMPRESA
        AND R.NUMERCL = A.NUMERCL
        AND R.ANNO = A.ANNO) AC,--RCL_ACCICOMP AC,-- 
     RCL_TIPIABON I, --
     FIC_HCABEPED P, --
     FIC_CABEOTRE O, --
     RCL_PARAABON IP, --
     FICTEC F, --
     LFS,--
     (SELECT FA.EMCODI, FA.CFNDEF, FA.CFFALT, F.VATCOD, F.ARCARF, F.CPNROP, F.LFCANT, F.LFPREU, F.VUCVEN FROM FV_ASVEFA01 FA, FV_ASVEFA02 F
      WHERE F.EMCODI = FA.EMCODI
        AND F.DICODI = FA.DICODI
        AND F.ASCANA = FA.ASCANA
        AND F.PPTIPO = FA.PPTIPO
        AND F.CFNROF = FA.CFNROF) FA,
     (SELECT FA.EMCODI, FA.CFNDEF, FA.CFFALT, F.VATCOD, F.ARCARF, F.CPNROP, F.LFCANT, F.LFPREU, F.VUCVEN FROM FV_ASVEFA01 FA, FV_ASVEFA02 F
      WHERE F.EMCODI = FA.EMCODI
        AND F.DICODI = FA.DICODI
        AND F.ASCANA = FA.ASCANA
        AND F.PPTIPO = FA.PPTIPO
        AND F.CFNROF = FA.CFNROF) FC1,
     (SELECT FA.EMCODI, FA.CFNDEF, FA.CFFALT, F.VATCOD, F.ARCARF, F.CPNROP, F.LFCANT, F.LFPREU, F.VUCVEN FROM FV_ASVEFA01 FA, FV_ASVEFA02 F
      WHERE F.EMCODI = FA.EMCODI
        AND F.DICODI = FA.DICODI
        AND F.ASCANA = FA.ASCANA
        AND F.PPTIPO = FA.PPTIPO
        AND F.CFNROF = FA.CFNROF) FC2,
     (SELECT FA.EMCODI, FA.CFNDEF, FA.CFFALT, F.VATCOD, F.ARCARF, F.CPNROP, F.LFCANT, F.LFPREU, F.VUCVEN FROM FV_ASVEFA01 FA, FV_ASVEFA02 F
      WHERE F.EMCODI = FA.EMCODI
        AND F.DICODI = FA.DICODI
        AND F.ASCANA = FA.ASCANA
        AND F.PPTIPO = FA.PPTIPO
        AND F.CFNROF = FA.CFNROF) FAA,
     (SELECT C.EMPRESA, C.CLIENTE_ID, C.RAZON_SOC, C.PAIS, P.NOMBRE FROM CLIENTES C, GNR_PAISES P WHERE C.PAIS = P.PAIS) C,--
     (SELECT CV.EMPRESA,CV.CLIENTE_ID, CV.VENDEDOR, V.NOMBRE NOMBRE_VENDEDOR FROM GNR_CLVENDED CV, GNR_VENDEDOR V 
      WHERE CV.TIPO = V.TIPO AND CV.VENDEDOR = V.VENDEDOR AND CV.ACTIVA = 'S') V--
WHERE R.EMPRESA = A.EMPRESA
  AND R.NUMERCL = A.NUMERCL
  AND R.ANNO = A.ANNO
  --
  AND A.EMPRESA = AC.EMPRESA
  AND A.NUMERCL = AC.NUMERCL
  AND A.ANNO = AC.ANNO
  AND A.NUMEORDE = AC.NUMEORDE
  --
  AND A.TIPOACCI = 'ABONO' AND A.APROCONT = 'S' 
  --
  AND AC.TIPOABON = I.TIPIFICA(+)
  --
  AND R.EMPRESA = C.EMPRESA
  AND R.CLIENTE_ID = C.CLIENTE_ID
  --
  AND R.EMPRESA = V.EMPRESA(+)
  AND R.CLIENTE_ID = V.CLIENTE_ID(+)
  --
  AND R.EMPRESA = P.EMPRESA
  AND R.NUMEPEDI = P.NUMEPEDI
  AND P.TIPOACCI = 'I'
  --
  AND R.EMPRESA = O.EMPRESA
  AND R.NUMELOTE = O.NUMERO
  --
  AND I.PARAMETR = IP.PARAMETR
  --
  AND O.EMPRESA = F.EMPRESA
  AND O.TIP_ARTI = F.TIP_ARTI
  AND O.COD_ARTI = F.PRODUCTO
  --
  AND F.EMPRESA = LFS.EMPRESA
  AND F.MATBASE = LFS.COD_LFS
  --
  AND R.EMPRESA = FA.EMCODI(+)
  AND R.NUMEFACT = FA.CFNDEF(+)
  AND R.TIP_ARTI = FA.VATCOD(+)
  AND R.COD_ARTI = FA.ARCARF(+)
  AND R.NUMEPEDI = FA.CPNROP(+)
  --
  AND A.EMPRESA = FC1.EMCODI(+)
  AND A.NUMEFACT = FC1.CFNDEF(+)
  AND A.TIP_ARTI = FC1.VATCOD(+)
  AND A.COD_ARTI = FC1.ARCARF(+)
  --AND A.NUMEPEDI = FC1.CPNROP(+)
  --
  AND AC.EMPRESA = FC2.EMCODI(+)
  AND AC.NUMEFA02 = FC2.CFNDEF(+)
  AND AC.TIP_ARTI = FC2.VATCOD(+)
  AND AC.COD_ARTI = FC2.ARCARF(+)
  --AND AC.NUMEPEDI = FC2.CPNROP(+)
  --
  AND A.EMPRESA = FAA.EMCODI(+)
  AND A.NUMEABON = FAA.CFNDEF(+)
  AND A.TIP_ARTI = FAA.VATCOD(+)
  AND A.COD_ARTI = FAA.ARCARF(+)
  AND A.NUMEPEDI = FAA.CPNROP(+)
  AND R.NUMEPEDI LIKE '2016%'
  --AND R.NUMEPEDI = 2014000006
GROUP BY R.EMPRESA, 
R.CLIENTE_ID, C.RAZON_SOC,
C.PAIS, C.NOMBRE,
V.VENDEDOR, V.NOMBRE_VENDEDOR, 
R.NUMEPEDI, 
R.NUMELOTE, 
A.NUMEABON, 
A.NUMEFACT, 
FC1.CFFALT,
FC1.LFCANT,
FC1.LFPREU,
AC.NUMEFA02,
FC2.CFFALT,
FC2.LFCANT,
FC2.LFPREU,
P.FEC_ALTA,
DECODE(O.SITUACIO,'C',O.FEC_MODI), 
FAA.CFFALT,
AC.TIPOABON, I.DESCRIPC, I.PARAMETR, IP.DESCRIPC, R.NUMEFACT,
F.TIP_ARTI, F.PRODUCTO, F.MATBASE, F.UNIDADVENTA, 
FAA.LFCANT, 
F.ANCHO, F.LARGO, LFS.FCKG,
FAA.LFPREU; 

 
SELECT * FROM RCL_TIPIABON;

SELECT * FROM RCL_RECLCLIE;

SELECT * FROM FV_ASVEFA02;

SELECT * FROM RCL_PARAABON;

SELECT FA.EMCODI, FA.CFNDEF, FA.CFFALT, F.VATCOD, F.ARCARF, F.CPNROP, F.LFCANT, F.LFPREU, F.VUCVEN 
FROM FV_ASVEFA01 FA, FV_ASVEFA02 F
WHERE F.EMCODI = FA.EMCODI
 AND F.DICODI = FA.DICODI
 AND F.ASCANA = FA.ASCANA
 AND F.CFNROF = FA.CFNROF
 AND F.CFNROF = 2014000317;

        
SELECT * FROM FV_ASVEFA01 WHERE CFNDEF=20161001660;

SELECT * FROM FV_ASVEFA01 WHERE CFNROF = 2014000317;
SELECT * FROM FV_ASVEFA02 WHERE CFNROF = 2016001744;

SELECT CV.EMPRESA,CV.CLIENTE_ID, CV.VENDEDOR, V.NOMBRE NOMBRE_VENDEDOR FROM GNR_CLVENDED CV, GNR_VENDEDOR V 
      WHERE --CV.EMPRESA = V.EMPRESA AND 
      CV.TIPO = V.TIPO AND CV.VENDEDOR = V.VENDEDOR AND CV.ACTIVA = 'S' AND CV.CLIENTE_ID = '1052';