--CREATE TABLE ANALESTA.ANE_M_PRO_REAL AS
SELECT EMPRESA,N_CLIENTE,CLIENTE,OT,FECHA_DE_LA_OT,FECHA_CIERRE_DE_LA_OT,TIPO_PRD,ESPECIALIDAD,LINEA,LFS,N_CAPAS_TOTALES,CANTIDAD_DE_FASES,
		 ANCHO_CLIENTE,N_DE_CORTES,N_DE_VECES,ANCHO_DE_PRODUCCION,ORIGEN_MP,
		 TIPO_MP,COD_MP,LFS_MP,
		 --ANCHO_MP,UNIDAD_ORIGEN,
		 --PRECIO_UNITARIO_MP_M2_COMPRAS,PRECIO_UNITARIO_MP_M2_ALGORIT,PRECIO_UNIT_MP_M2_ALGO_COSTES,PRECIO_UNITARIO_MP_M2,LOTE_CONSUMIDO,
		 --TRAZA_P_UNITARIO_MP_M2_ALGORIT,TRAZA_P_UNIT_MP_M2_ALGO_COSTES,
		 FASE_MP,SECCION_PRODUCTIVA_MP,MAQUINA_MP,
		 SUM(M2_MERMPLAN) M2_MERMPLAN,
		 SUM(M2_MERMPLAN_EXESO) M2_MERMPLAN_EXESO,
		 SUM(EUR_MERMPLAN) EUR_MERMPLAN,
		 SUM(EUR_MERMPLAN_EXESO) EUR_MERMPLAN_EXESO,
		 SUM(ML_CONSUMIDOS) ML_CONSUMIDOS,
		 SUM(ML_PRODUCIDOS) ML_PRODUCIDOS,
		 --BORRAR I
		 NULL ML_CONSUMIDOS_REALES, --SUM(ML_CONSUMIDOS_REALES) ML_CONSUMIDOS_REALES,
		 NULL ML_PRODUCIDOS_REALES, --SUM(ML_PRODUCIDOS_REALES) ML_PRODUCIDOS_REALES,
		 NULL ML_MERMAS_ACUMULADAS_HAS_MAQ, --MAX(ML_MERMAS_ACUMULADAS_HAS_MAQ) ML_MERMAS_ACUMULADAS_HAS_MAQ,
		 NULL ML_MERMAS_ACUMULADAS_EN_MAQ, --MAX(ML_MERMAS_ACUMULADAS_EN_MAQ) ML_MERMAS_ACUMULADAS_EN_MAQ,
		 --BORRAR F

		 SUM(ML_ENHEBRADO_MAQUINA) ML_ENHEBRADO_MAQUINA,
		 SUM(ML_AJ_MAQUINA_MAQUINA) ML_AJ_MAQUINA_MAQUINA,
		 SUM(ML_CAMBIO_BOBINA_MAQUINA) ML_CAMBIO_BOBINA_MAQUINA,
		 SUM(ML_MERMA_TIRADA_MQUINA) ML_MERMA_TIRADA_MQUINA,
		 SUM(ML_SANEAMIENTOS_MAQUINA) ML_SANEAMIENTOS_MAQUINA,
		 SUM(ML_MERMA_PROCESO_MQUINA) ML_MERMA_PROCESO_MQUINA,
		 SUM(M2_CONSUMIDOS) M2_CONSUMIDOS,
		 SUM(M2_PRODUCIDOS) M2_PRODUCIDOS,
		 
		 --BORRAR I
		 NULL M2_PRODUCIDOS_REALES, --SUM(M2_PRODUCIDOS_REALES) M2_PRODUCIDOS_REALES,
		 NULL M2_CONSUMIDOS_REALES, --SUM(M2_CONSUMIDOS_REALES) M2_CONSUMIDOS_REALES,
		 NULL M2_MERMAS_ACUMULADAS_HAS_MAQ, --MAX(M2_MERMAS_ACUMULADAS_HAS_MAQ) M2_MERMAS_ACUMULADAS_HAS_MAQ,
		 NULL M2_MERMAS_ACUMULADAS_EN_MAQ, --MAX(M2_MERMAS_ACUMULADAS_EN_MAQ) M2_MERMAS_ACUMULADAS_EN_MAQ,
		 --BORRAR F
		 
		 SUM(M2_ENHEBRADO_MAQUINA) M2_ENHEBRADO_MAQUINA,
		 SUM(M2_AJ_MAQUINA_MAQUINA) M2_AJ_MAQUINA_MAQUINA,
		 SUM(M2_CAMBIO_BOBINA_MAQUINA) M2_CAMBIO_BOBINA_MAQUINA,
		 SUM(M2_MERMA_TIRADA_MQUINA) M2_MERMA_TIRADA_MQUINA,
		 SUM(M2_SANEAMIENTOS_MAQUINA) M2_SANEAMIENTOS_MAQUINA,
		 SUM(M2_MERMA_PROCESO_MQUINA) M2_MERMA_PROCESO_MQUINA,
		 SUM(EUROS_ML_CONSUMIDOS) EUROS_ML_CONSUMIDOS,
		 SUM(EUROS_ML_PRODUCIDOS) EUROS_ML_PRODUCIDOS,
		 
		 --BORRAR I
		 NULL EUROS_ML_CONSUMIDOS_REALES, --SUM(EUROS_ML_CONSUMIDOS_REALES) EUROS_ML_CONSUMIDOS_REALES,
		 NULL EUROS_ML_PRODUCIDOS_REALES, --SUM(EUROS_ML_PRODUCIDOS_REALES) EUROS_ML_PRODUCIDOS_REALES,
		 NULL EUR_MERMAS_ACUMULADAS_HAS_MAQ, --MAX(EUR_MERMAS_ACUMULADAS_HAS_MAQ) EUR_MERMAS_ACUMULADAS_HAS_MAQ,
		 NULL EUR_MERMAS_ACUMULADAS_EN_MAQ, --MAX(EUR_MERMAS_ACUMULADAS_EN_MAQ) EUR_MERMAS_ACUMULADAS_EN_MAQ,
		 --BORRAR F
		 
		 SUM(EUROS_ML_ENHEBRADO) EUROS_ML_ENHEBRADO,
		 SUM(EUROS_ML_AJ_MAQUINA) EUROS_ML_AJ_MAQUINA,
		 SUM(EUROS_ML_CAMBIO_BOBINA) EUROS_ML_CAMBIO_BOBINA,
		 SUM(EUROS_ML_MERMA_TIRADA) EUROS_ML_MERMA_TIRADA,
		 SUM(EUROS_ML_SANEAMIENTOS) EUROS_ML_SANEAMIENTOS,
		 SUM(EUROS_ML_MERMA_PROCESO) EUROS_ML_MERMA_PROCESO,
		 SUM(EUROS_MERMA_TOTAL_MAQUINA) EUROS_MERMA_TOTAL_MAQUINA,
		 FECHA_FACTURA,UNIDAD_CIERRE,Q_CERRADA_ML,Q_CERRADA_M2,Q_CERRADA_KG,Q_CERRADA_UN,FUENTE_DEL_CIERRE,
		 SUM(TOTAL_M2_MERMPLAN) TOTAL_M2_MERMPLAN,
		 SUM(TOTAL_EUROS_MERMPLAN) TOTAL_EUROS_MERMPLAN,
		 SUM(ML_MERMA_TOTAL) ML_MERMA_TOTAL,
		 SUM(M2_MERMA_TOTAL) M2_MERMA_TOTAL
FROM ANE_M_PRO WHERE EMPRESA = '05' AND OT = 2016000205 
GROUP BY EMPRESA,N_CLIENTE,CLIENTE,OT,FECHA_DE_LA_OT,FECHA_CIERRE_DE_LA_OT,TIPO_PRD,ESPECIALIDAD,LINEA,LFS,N_CAPAS_TOTALES,CANTIDAD_DE_FASES,
		 ANCHO_CLIENTE,N_DE_CORTES,N_DE_VECES,ANCHO_DE_PRODUCCION,ORIGEN_MP,
		 TIPO_MP,COD_MP,LFS_MP,
		 FASE_MP,SECCION_PRODUCTIVA_MP,MAQUINA_MP,
		 FECHA_FACTURA,UNIDAD_CIERRE,Q_CERRADA_ML,Q_CERRADA_M2,Q_CERRADA_KG,Q_CERRADA_UN,FUENTE_DEL_CIERRE
ORDER BY FASE_MP;

				UPDATE ANALESTA.ANE_M_PRO_REAL 
				SET ML_CONSUMIDOS_REALES = NULL,
					 M2_CONSUMIDOS_REALES = NULL,
					 ML_PRODUCIDOS_REALES = NULL,
					 M2_PRODUCIDOS_REALES = NULL;

SELECT * FROM ANALESTA.ANE_M_PRO_REAL ORDER BY FASE_MP;