CREATE OR REPLACE VIEW "ANALESTA"."ANE_MER_NUMERO_MAQUPROC_OT" AS 
         SELECT EMPRESA, NUMEOTRE, CONTADOR, 
                DECODE(INSTR(MAQUCODI,'CORTADORA'),1,'CORTADORAS',
                DECODE(INSTR(MAQUCODI,'LAMINADORA'),1,'LAMINADORAS',
                DECODE(INSTR(MAQUCODI,'LAQUEADORA'),1,'LAQUEADORAS',
                DECODE(INSTR(MAQUCODI,'IMPRESORA'),1,'IMPRESORAS')))) MAQUINA,
         COUNT(DISTINCT MAQUCODI) NUMERO_MAQUINAS_PROCESO
         FROM PRD_PASAMAQU
         GROUP BY EMPRESA, NUMEOTRE, CONTADOR, 
                  DECODE(INSTR(MAQUCODI,'CORTADORA'),1,'CORTADORAS',
                  DECODE(INSTR(MAQUCODI,'LAMINADORA'),1,'LAMINADORAS',
                  DECODE(INSTR(MAQUCODI,'LAQUEADORA'),1,'LAQUEADORAS',
                  DECODE(INSTR(MAQUCODI,'IMPRESORA'),1,'IMPRESORAS'))));