--------------------------------------------------------
--  DDL for View ANE_LAMINA
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "ANALESTA"."ANE_LAMINA" ("EMPRESA", "CLIENTE", "NOMBRE_DEL_CLIENTE", "PAIS", "NOMBRE_PAIS", "VENDEDOR", "NOMBRE_VENDEDOR", "OT", "IMPRESA_ANONIMA", "FEC_CIERRE_OT", "FACTURA", "FECHA_FACTURA", "UNIDAD_VENTA", "CANTIDAD_ML", "CANTIDAD_M2", "CANTIDAD_KG", "CANTIDAD_UN", "TIPO_PRD", "ESPECIALIDAD", "LINEA", "LFS", "N_CAPAS_TOTALES", "ANCHO_ESPECIALIDAD", "N_DE_CORTES", "N_DE_VECES", "ORIGEN_MP", "TIPO", "COD_MP", "ANCHO", "LFS_MP", "PEDIDO_O_LOTE_INTERNO_MP", "FECHA_ORIGEN_MP", "PROV_MP", "UNIDAD_ORIGEN", "PRECIO_UNITARIO_MP_M2_COMPRAS", "PRECIO_UNITARIO_MP_M2_ALGORIT", "PRECIO_UNITARIO_MP_M2", "LOTE_CONSUMIDO", "TRAZA_P_UNITARIO_MP_M2_ALGORIT", "Q_CONS_LAMINA_KG_MP", "Q_CONS_LAMINA_ML_MP", "Q_CONS_LAMINA_M2_MP", "Q_PROD_LAMINA_KG_MP", "Q_PROD_LAMINA_ML_MP", "Q_PROD_LAMINA_M2_MP", "EUROS_M2_PRODUCIDOS_MP", "Q_CERRADA_KG", "Q_CERRADA_ML", "Q_CERRADA_M2", "UNIDAD_CIERRE", "FUENTE_DEL_CIERRE", "EXCLUIDA") AS 
  SELECT M.EMPRESA, M.CLIENTE, M.NOMBRE_DEL_CLIENTE, 
     M.PAIS, M.NOMBRE NOMBRE_PAIS,
     M.VENDEDOR, M.NOMBRE_VENDEDOR, 
     M.OT,
     M.IMPRESA_ANONIMA,
     M.FEC_CIERRE_OT, 
     M.FACTURA, M.FECHA_FACTURA,
     --
     M.UNIDAD_VENTA, M.CANTIDAD_ML, M.CANTIDAD_M2, M.CANTIDAD_KG, M.CANTIDAD_UN,
     --
     M.TIPO_PRD, M.ESPECIALIDAD, M.LINEA, M.LFS, 
			(SELECT COUNT(DISTINCT LFS.COD_LFS) FROM FIC_LINEOTRE LO, ARTICULO A, LFS 
			 WHERE LO.EMPRESA = A.EMPRESA 
			   AND LO.TIP_ARES = A.TIP_ARTI
				AND LO.COD_ARES = A.COD_ARTI
				AND A.EMPRESA = LFS.EMPRESA
				AND A.COD_LFS = LFS.COD_LFS
			   AND LO.EMPRESA = M.EMPRESA 
				AND LO.NUMERO = M.OT) N_CAPAS_TOTALES,
       M.ANCHO_ESPECIALIDAD,
		 --
       /*CASE WHEN M.FASE IS NULL THEN ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material(M.EMPRESA, M.OT, (SELECT MAX(LO.FASE) FROM FIC_LINEOTRE LO
																							   WHERE LO.EMPRESA = M.EMPRESA 
																								  AND LO.NUMERO = M.OT
																								  AND ((INSTR(LO.COD_ARES,'IMPRESORA') != 0) OR
																								       (INSTR(LO.COD_ARES,'CORTADORA') != 0) OR
																										 (INSTR(LO.COD_ARES,'LAMINADORA') != 0) OR
																										 (INSTR(LO.COD_ARES,'LAQUEADORA') != 0))))
            ELSE ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material(M.EMPRESA, M.OT, M.FASE)
            END N_DE_CORTES,*/
       
		 M.N_DE_CORTES,
		                                                                         
		 ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material_Exp_OT(M.EMPRESA, M.OT, (SELECT MAX(LO.FASE) FROM FIC_LINEOTRE LO
																							   WHERE LO.EMPRESA = M.EMPRESA 
																								  AND LO.NUMERO = M.OT
																								  AND ((INSTR(LO.COD_ARES,'IMPRESORA') != 0) OR
																								       (INSTR(LO.COD_ARES,'CORTADORA') != 0) OR
																										 (INSTR(LO.COD_ARES,'LAMINADORA') != 0) OR
																										 (INSTR(LO.COD_ARES,'LAQUEADORA') != 0)))) N_DE_VECES,
		 
		 CASE WHEN TRIM(M.PEDIDO) IS NOT NULL THEN 'C'
          WHEN TRIM(M.PEDIDO_TM) IS NOT NULL THEN 'T'
          WHEN TRIM(M.FECHA_CIERRE_OT_SEMIELABORADO) IS NOT NULL THEN 'P'
          ELSE 'O' 
          END ORIGEN_MP,
		 
		 M.TIPO, M.COD_MP, M.ANCHO, M.LFS_MP,
		 
		 CASE WHEN TRIM(M.PEDIDO) IS NOT NULL THEN TO_CHAR(M.PEDIDO)
		      WHEN TRIM(M.PEDIDO_TM) IS NOT NULL THEN TO_CHAR(M.PEDIDO_TM)
          WHEN TRIM(M.FECHA_CIERRE_OT_SEMIELABORADO) IS NOT NULL THEN M.LOTE
             ELSE NULL 
             END PEDIDO_O_LOTE_INTERNO_MP,
		 
		 CASE WHEN TRIM(M.PEDIDO) IS NOT NULL THEN M.FECHA_RECEPCION
          WHEN TRIM(M.PEDIDO_TM) IS NOT NULL THEN M.FECHRECE_TM
		      WHEN TRIM(M.FECHA_CIERRE_OT_SEMIELABORADO) IS NOT NULL THEN M.FECHA_CIERRE_OT_SEMIELABORADO
            ELSE M.FECHA_ENTRADA_ALMACEN 
            END FECHA_ORIGEN_MP,
		 
		 CASE WHEN TRIM(M.PEDIDO) IS NOT NULL THEN M.PROV
          WHEN TRIM(M.PEDIDO_TM) IS NOT NULL THEN M.PROVEEDO_TM
          WHEN TRIM(M.FECHA_CIERRE_OT_SEMIELABORADO) IS NOT NULL THEN 'EN'
          ELSE NULL
          END PROV_MP,
       
       CASE WHEN TRIM(M.PEDIDO) IS NOT NULL THEN M.UNIDAD_COMPRADA
            WHEN TRIM(M.FECHA_CIERRE_OT_SEMIELABORADO) IS NOT NULL THEN P_Utilidad.F_ValoDeva('TIPOUNML')
            ELSE P_Utilidad.F_ValoDeva('TIPOUNM2')
            END UNIDAD_ORIGEN,
       
       M.PRECIO_COMPRA_CALCULADO PRECIO_UNITARIO_MP_M2_COMPRAS, 
       P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_PRECIO(M.EMPRESA,M.TIPO,M.COD_MP,M.FEC_MODI),'PRECIO') PRECIO_UNITARIO_MP_M2_ALGORIT, 
       DECODE(NVL(M.PRECIO_COMPRA_CALCULADO,0),0,P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_PRECIO(M.EMPRESA,M.TIPO,M.COD_MP,M.FEC_MODI),'PRECIO'),M.PRECIO_COMPRA_CALCULADO) PRECIO_UNITARIO_MP_M2,
       
       M.LOTE LOTE_CONSUMIDO,
		 
		 --M.PEDIDO, M.LOTE, M.FECHA_RECEPCION, M.FECHA_CIERRE_OT_SEMIELABORADO, 
		 --M.CANTIDAD_COMPRA, M.CANTIDAD_EQUIVALENTE, M.UNIDAD_COMPRADA, M.DIVISA, M.PRECIO_COMPRA,
		 
       P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_PRECIO(M.EMPRESA,M.TIPO,M.COD_MP,M.FEC_MODI),'TRAZA') TRAZA_P_UNITARIO_MP_M2_ALGORIT,
--
		 
       SUM(M.CANTIDAD_CONSUMIDA) *
		 DECODE(P_Utilidad.F_ValoDeva('TIPOUNML'),P_Utilidad.F_ValoDeva('TIPOUNKG'),1,DECODE(NVL(M.FCKG,0),0,0,DECODE(P_Utilidad.F_ValoDeva('TIPOUNML'),P_Utilidad.F_ValoDeva('TIPOUNML'),(1 / M.FCKG) * (M.ANCHO / 1000),
                                                                                                        P_Utilidad.F_ValoDeva('TIPOUNM2'),1 / M.FCKG,
                                                                                                        P_Utilidad.F_ValoDeva('TIPOUNUN'),(1 / M.FCKG) * ((M.ANCHO * NULL) / 1000000)))) Q_CONS_LAMINA_KG_MP,
		 SUM(M.CANTIDAD_CONSUMIDA) *
		 DECODE(P_Utilidad.F_ValoDeva('TIPOUNML'),P_Utilidad.F_ValoDeva('TIPOUNML'),1,DECODE(NVL(M.ANCHO,0),0,0,DECODE(P_Utilidad.F_ValoDeva('TIPOUNML'),P_Utilidad.F_ValoDeva('TIPOUNKG'),M.FCKG * (1000 / M.ANCHO),
                                                                                                        P_Utilidad.F_ValoDeva('TIPOUNM2'),(1000 / M.ANCHO),
                                                                                                        P_Utilidad.F_ValoDeva('TIPOUNUN'),(1000 / M.ANCHO) * ((M.ANCHO * NULL) / 1000000)))) Q_CONS_LAMINA_ML_MP,
       SUM(M.CANTIDAD_CONSUMIDA) *
		 DECODE(P_Utilidad.F_ValoDeva('TIPOUNML'),P_Utilidad.F_ValoDeva('TIPOUNM2'),1,P_Utilidad.F_ValoDeva('TIPOUNKG'),M.FCKG,
                                                             P_Utilidad.F_ValoDeva('TIPOUNML'),(M.ANCHO / 1000),
                                                             P_Utilidad.F_ValoDeva('TIPOUNUN'),(M.ANCHO * NULL) / 1000000) Q_CONS_LAMINA_M2_MP,
--
       SUM(M.CANTIDAD_PRODUCIDA) *
		 DECODE(P_Utilidad.F_ValoDeva('TIPOUNML'),P_Utilidad.F_ValoDeva('TIPOUNKG'),1,DECODE(NVL(M.FCKG,0),0,0,DECODE(P_Utilidad.F_ValoDeva('TIPOUNML'),P_Utilidad.F_ValoDeva('TIPOUNML'),(1 / M.FCKG) * (M.ANCHO / 1000),
                                                                                                        P_Utilidad.F_ValoDeva('TIPOUNM2'),1 / M.FCKG,
                                                                                                        P_Utilidad.F_ValoDeva('TIPOUNUN'),(1 / M.FCKG) * ((M.ANCHO * NULL) / 1000000)))) Q_PROD_LAMINA_KG_MP,
		 SUM(M.CANTIDAD_PRODUCIDA) *
		 DECODE(P_Utilidad.F_ValoDeva('TIPOUNML'),P_Utilidad.F_ValoDeva('TIPOUNML'),1,DECODE(NVL(M.ANCHO,0),0,0,DECODE(P_Utilidad.F_ValoDeva('TIPOUNML'),P_Utilidad.F_ValoDeva('TIPOUNKG'),M.FCKG * (1000 / M.ANCHO),
                                                                                                        P_Utilidad.F_ValoDeva('TIPOUNM2'),(1000 / M.ANCHO),
                                                                                                        P_Utilidad.F_ValoDeva('TIPOUNUN'),(1000 / M.ANCHO) * ((M.ANCHO * NULL) / 1000000)))) Q_PROD_LAMINA_ML_MP,
       SUM(M.CANTIDAD_PRODUCIDA) *
		 DECODE(P_Utilidad.F_ValoDeva('TIPOUNML'),P_Utilidad.F_ValoDeva('TIPOUNM2'),1,P_Utilidad.F_ValoDeva('TIPOUNKG'),M.FCKG,
                                                             P_Utilidad.F_ValoDeva('TIPOUNML'),(M.ANCHO / 1000),
                                                             P_Utilidad.F_ValoDeva('TIPOUNUN'),(M.ANCHO * NULL) / 1000000) Q_PROD_LAMINA_M2_MP,
		  
		 SUM(M.CANTIDAD_PRODUCIDA) *
		 DECODE(NVL(M.PRECIO_COMPRA_CALCULADO,0),0,P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_PRECIO(M.EMPRESA,M.TIPO,M.COD_MP,M.FEC_MODI),'PRECIO'),M.PRECIO_COMPRA_CALCULADO) *
		 DECODE(P_Utilidad.F_ValoDeva('TIPOUNML'),P_Utilidad.F_ValoDeva('TIPOUNM2'),1,P_Utilidad.F_ValoDeva('TIPOUNKG'),M.FCKG,
                                                             P_Utilidad.F_ValoDeva('TIPOUNML'),(M.ANCHO / 1000),
                                                             P_Utilidad.F_ValoDeva('TIPOUNUN'),(M.ANCHO * NULL) / 1000000) EUROS_M2_PRODUCIDOS_MP,
                                                             
       DECODE(NVL(M.LPCANT,0),0,M.CANTCERR,M.LPCANT) *
       DECODE(DECODE(NVL(M.LPCANT,0),0,M.UNIDAD_OT,M.VUCVEN),P_Utilidad.F_ValoDeva('TIPOUNKG'),1,DECODE(NVL(M.FCKG_OT,0),0,0,DECODE(DECODE(NVL(M.LPCANT,0),0,M.UNIDAD_OT,M.VUCVEN),P_Utilidad.F_ValoDeva('TIPOUNML'),(1 / M.FCKG_OT) * (M.ANCHO_ESPECIALIDAD / 1000),
                                                                                                        P_Utilidad.F_ValoDeva('TIPOUNM2'),1 / M.FCKG_OT,
                                                                                                        P_Utilidad.F_ValoDeva('TIPOUNUN'),(1 / M.FCKG_OT) * ((M.ANCHO_ESPECIALIDAD * NULL) / 1000000)))) Q_CERRADA_KG,
		 DECODE(NVL(M.LPCANT,0),0,M.CANTCERR,M.LPCANT) *
       DECODE(DECODE(NVL(M.LPCANT,0),0,M.UNIDAD_OT,M.VUCVEN),P_Utilidad.F_ValoDeva('TIPOUNML'),1,DECODE(NVL(M.ANCHO_ESPECIALIDAD,0),0,0,DECODE(DECODE(NVL(M.LPCANT,0),0,M.UNIDAD_OT,M.VUCVEN),P_Utilidad.F_ValoDeva('TIPOUNKG'),M.FCKG_OT * (1000 / M.ANCHO_ESPECIALIDAD),
                                                                                                        P_Utilidad.F_ValoDeva('TIPOUNM2'),(1000 / M.ANCHO_ESPECIALIDAD),
                                                                                                        P_Utilidad.F_ValoDeva('TIPOUNUN'),(1000 / M.ANCHO_ESPECIALIDAD) * ((M.ANCHO_ESPECIALIDAD * NULL) / 1000000)))) Q_CERRADA_ML,
       DECODE(NVL(M.LPCANT,0),0,M.CANTCERR,M.LPCANT) *
       DECODE(DECODE(NVL(M.LPCANT,0),0,M.UNIDAD_OT,M.VUCVEN),P_Utilidad.F_ValoDeva('TIPOUNM2'),1,P_Utilidad.F_ValoDeva('TIPOUNKG'),M.FCKG_OT,
                                                             P_Utilidad.F_ValoDeva('TIPOUNML'),(M.ANCHO_ESPECIALIDAD / 1000),
                                                             P_Utilidad.F_ValoDeva('TIPOUNUN'),(M.ANCHO_ESPECIALIDAD * NULL) / 1000000) Q_CERRADA_M2,
		  
		 DECODE(NVL(M.LPCANT,0),0,M.UNIDAD_OT,M.VUCVEN) UNIDAD_CIERRE,
       DECODE(NVL(M.LPCANT,0),0,'CIERRE DE OT','EXPEDICION') FUENTE_DEL_CIERRE,
       
       ANALESTA.P_ANE_MERMLAMI_PRAG.F_Verifica_Ot(M.EMPRESA, M.OT, M.NUMEPEDI) EXCLUIDA
FROM (
SELECT O.EMPRESA, AO.CLIENASOC CLIENTE, C.RAZON_SOC NOMBRE_DEL_CLIENTE, 
       C.PAIS, C.NOMBRE,
       V.VENDEDOR, V.NOMBRE_VENDEDOR,
       O.NUMERO OT,
       DECODE(O.TIP_ARTI,P_UTILIDAD.F_VALODEVA('TIARFIF4'),DECODE(SUBSTR(O.COD_ARTI,3,1),P_UTILIDAD.F_VALODEVA('TIPOPROY'),'ANONIMA','IMPRESA')) IMPRESA_ANONIMA,
       M.TIP_ARTI TIPO, M.COD_ARTI COD_MP, --A.ANCHO,--NVL(A.ANCHO,CC.ANCHO) ANCHO,
--
      DECODE(A.ANCHO,NULL,(SELECT DC.ANCHO 
      FROM PRD_LIBOCORT C,
				--
				(SELECT M.EMPRESA, M.NUMEOTRE, M.FASESEQU, M.CONTADOR FROM PRD_MAQURUTA M
				 WHERE NOT EXISTS (SELECT 'X' FROM PRD_HCABEOTR O WHERE O.EMPRESA = M.EMPRESA AND O.NUMEOTRE = M.NUMEOTRE)
				 UNION
				 SELECT M.EMPRESA, M.NUMEOTRE, M.FASESEQU, M.CONTADOR FROM PRD_HMAQURUT M) MA, 
				--	
				FIC_LIPCORTR DC 
				WHERE MA.EMPRESA = DC.EMPRESA
				  AND MA.NUMEOTRE = DC.NUMERO
				  AND SUBSTR(MA.NUMEOTRE,1,4) = DC.ANNO
				  AND MA.FASESEQU = (DC.FASE * 100) + DC.SECUENCI
				  AND MA.EMPRESA = C.EMPRESA
				  AND MA.NUMEOTRE = C.NUMEOTRE
				  AND MA.CONTADOR = C.CONTADOR
				  AND DC.NUM_CORTE = C.NUMECORT
				  AND MA.EMPRESA = M.EMPRESA
				  AND MA.NUMEOTRE = M.NUOTBOBI
				  AND C.CONTADOR = M.CONTBOBI
				  AND C.CONTBOBI = M.COBOBOBI),A.ANCHO) ANCHO,
--
       (SELECT C.PCNROP FROM FV_ASCOAL02 C WHERE C.EMCODI = M.EMPRESA AND C.VATCOD = M.TIP_ARTI AND C.ARCARF = M.COD_ARTI AND C.ASLOTE = M.LOTE AND ROWNUM = 1) PEDIDO,
       (SELECT C.NUMEPECO FROM FIC_ENMAMATE C WHERE C.EMPRESA = M.EMPRESA AND C.TIP_ARTI = M.TIP_ARTI AND C.COD_ARTI = M.COD_ARTI AND C.LOTE = M.LOTE AND ROWNUM = 1) PEDIDO_TM,
       (SELECT C.FECHRECE FROM FIC_ENMAMATE C WHERE C.EMPRESA = M.EMPRESA AND C.TIP_ARTI = M.TIP_ARTI AND C.COD_ARTI = M.COD_ARTI AND C.LOTE = M.LOTE AND ROWNUM = 1) FECHRECE_TM,
       (SELECT C.PROVEEDO FROM FIC_ENMAMATE C WHERE C.EMPRESA = M.EMPRESA AND C.TIP_ARTI = M.TIP_ARTI AND C.COD_ARTI = M.COD_ARTI AND C.LOTE = M.LOTE AND ROWNUM = 1) PROVEEDO_TM,
		 
		   (SELECT MIN(H.AHFMOV) AHFMOV FROM FV_ASALHI01 H WHERE H.EMCODI = M.EMPRESA AND H.VATCOD = M.TIP_ARTI AND H.ARCARF = M.COD_ARTI AND H.ASLOTE = M.LOTE AND H.AHTIMO = 'E') FECHA_ENTRADA_ALMACEN,
       
       FA.CFNDEF FACTURA, FA.CFFALT FECHA_FACTURA,
       --
		 --/*
       FA.VUCVEN UNIDAD_VENTA, 
       DECODE(FA.VUCVEN,P_Utilidad.F_ValoDeva('TIPOUNML'),1,DECODE(NVL(FI.ANCHO,0),0,0,DECODE(FA.VUCVEN,P_Utilidad.F_ValoDeva('TIPOUNKG'),FI.FCKG * (1000 / FI.ANCHO),
                                                                                                        P_Utilidad.F_ValoDeva('TIPOUNM2'),(1000 / FI.ANCHO),
                                                                                                        P_Utilidad.F_ValoDeva('TIPOUNUN'),(1000 / FI.ANCHO) * ((FI.ANCHO * FI.LARGO) / 1000000)))) * FA.LFCANT CANTIDAD_ML,
       DECODE(FA.VUCVEN,P_Utilidad.F_ValoDeva('TIPOUNM2'),1,P_Utilidad.F_ValoDeva('TIPOUNKG'),FI.FCKG,
                                                             P_Utilidad.F_ValoDeva('TIPOUNML'),(FI.ANCHO / 1000),
                                                             P_Utilidad.F_ValoDeva('TIPOUNUN'),(FI.ANCHO * FI.LARGO) / 1000000) * FA.LFCANT CANTIDAD_M2,
       DECODE(FA.VUCVEN,P_Utilidad.F_ValoDeva('TIPOUNKG'),1,DECODE(NVL(FI.FCKG,0),0,0,DECODE(FA.VUCVEN,P_Utilidad.F_ValoDeva('TIPOUNML'),(1 / FI.FCKG) * (FI.ANCHO / 1000),
                                                                                                        P_Utilidad.F_ValoDeva('TIPOUNM2'),1 / FI.FCKG,
                                                                                                        P_Utilidad.F_ValoDeva('TIPOUNUN'),(1 / FI.FCKG) * ((FI.ANCHO * FI.LARGO) / 1000000)))) * FA.LFCANT CANTIDAD_KG,
       DECODE(FA.VUCVEN,P_Utilidad.F_ValoDeva('TIPOUNUN'),1,P_Utilidad.F_ValoDeva('TIPOUNML'),DECODE(NVL(FI.ANCHO,0)*NVL(FI.LARGO,0),0,0,(1 / ((1000 / FI.ANCHO) * ((FI.ANCHO * FI.LARGO) / 1000000)))),
                                                                              P_Utilidad.F_ValoDeva('TIPOUNM2'),DECODE(NVL(FI.ANCHO,0)*NVL(FI.LARGO,0),0,0,(1000000 / (FI.ANCHO * FI.LARGO))),
                                                                              P_Utilidad.F_ValoDeva('TIPOUNKG'),DECODE(NVL(FI.ANCHO,0)*NVL(FI.LARGO,0)*NVL(FI.FCKG,0),0,0,(1 / ((1 / FI.FCKG) * ((FI.ANCHO * FI.LARGO) / 1000000))))) * FA.LFCANT CANTIDAD_UN,
       --*/
		 --
		 
       (SELECT C.MPCPRO FROM FV_ASCOAL02 C WHERE C.EMCODI = M.EMPRESA AND C.VATCOD = M.TIP_ARTI AND C.ARCARF = M.COD_ARTI AND C.ASLOTE = M.LOTE AND ROWNUM = 1) PROV,
		 /*
       (SELECT C.ALUNST FROM FV_ASCOAL02 C WHERE C.EMCODI = M.EMPRESA AND C.VATCOD = M.TIP_ARTI AND C.ARCARF = M.COD_ARTI AND C.ASLOTE = M.LOTE AND ROWNUM = 1) UNIDAD_STOCK_EN_COMPRA,*/
		 
       (SELECT C.ALUNCO FROM FV_ASCOAL02 C WHERE C.EMCODI = M.EMPRESA AND C.VATCOD = M.TIP_ARTI AND C.ARCARF = M.COD_ARTI AND C.ASLOTE = M.LOTE AND ROWNUM = 1) UNIDAD_COMPRADA,
		 
       M.LOTE,
		 
       (SELECT CA.ACFENT FROM FV_ASCOAL02 C, FV_ASCOAL01 CA 
        WHERE C.EMCODI = M.EMPRESA AND C.VATCOD = M.TIP_ARTI AND C.ARCARF = M.COD_ARTI AND C.ASLOTE = M.LOTE 
          AND CA.EMCODI = C.EMCODI AND CA.DICODI = C.DICODI AND CA.ACANYA = C.ACANYA AND CA.ACNROA = C.ACNROA AND CA.TIPDOC IS NULL
         
          AND ROWNUM = 1) FECHA_RECEPCION, 
			 
       DECODE(M.TIP_ARTI,P_UTILIDAD.F_VALODEVA('TIARSEF4'),(SELECT OS.FEC_MODI FROM FIC_CABEOTRE OS WHERE OS.EMPRESA = M.EMPRESA AND TO_CHAR(OS.NUMERO) = M.LOTE AND OS.TIP_ARTI = M.TIP_ARTI AND OS.COD_ARTI = M.COD_ARTI AND OS.SITUACIO = 'C')) FECHA_CIERRE_OT_SEMIELABORADO,
		 /*
       (SELECT C.ALCANT FROM FV_ASCOAL02 C WHERE C.EMCODI = M.EMPRESA AND C.VATCOD = M.TIP_ARTI AND C.ARCARF = M.COD_ARTI AND C.ASLOTE = M.LOTE AND ROWNUM = 1) CANTIDAD_COMPRA,
       (SELECT C.ALCAEQ FROM FV_ASCOAL02 C WHERE C.EMCODI = M.EMPRESA AND C.VATCOD = M.TIP_ARTI AND C.ARCARF = M.COD_ARTI AND C.ASLOTE = M.LOTE AND ROWNUM = 1) CANTIDAD_EQUIVALENTE,*/
		 /*
       (SELECT C.ALPREU FROM FV_ASCOAL02 C WHERE C.EMCODI = M.EMPRESA AND C.VATCOD = M.TIP_ARTI AND C.ARCARF = M.COD_ARTI AND C.ASLOTE = M.LOTE AND ROWNUM = 1) PRECIO_COMPRA,
       (SELECT C.DIVISA FROM FV_ASCOAL02 C WHERE C.EMCODI = M.EMPRESA AND C.VATCOD = M.TIP_ARTI AND C.ARCARF = M.COD_ARTI AND C.ASLOTE = M.LOTE AND ROWNUM = 1) DIVISA,*/
       (
         SELECT DECODE(C.ALUNST,P_Utilidad.F_ValoDeva('TIPOUNM2'),DECODE(C.ALUPRE,0,DECODE(C.ALCANT, 0, 0,((C.ALPREU * D.CAMBIO) * C.ALCAEQ) / C.ALCANT),
                                                                  DECODE(C.ALCANT, 0, 0,(((C.ALPREU * D.CAMBIO) * C.ALCAEQ) / C.ALCANT) / C.ALUPRE) 
                      ))ALPREU  
         FROM FV_ASCOAL02 C, GNR_DICOTIZA D, FV_ASCOAL01 CA
            WHERE CA.EMCODI = C.EMCODI
              AND CA.DICODI = C.DICODI
              AND CA.ACANYA = C.ACANYA
              AND CA.ACNROA = C.ACNROA
              AND CA.TIPDOC IS NULL
              AND C.DIVISA = D.DIVISA
              AND D.DIVISAMA = P_UTILIDAD.F_VALODEVA('DIVIEURO')
              AND TRUNC(C.ACFENT) BETWEEN TRUNC(DESDFECH) AND TRUNC(HASTFECH)
              AND (C.VATCOD != P_UTILIDAD.F_VALODEVA('TIARMPF4') OR (C.VATCOD = P_UTILIDAD.F_VALODEVA('TIARMPF4') AND C.VNACOD IN ('1','43','16','46')))
              AND C.EMCODI = M.EMPRESA
              AND C.VATCOD = M.TIP_ARTI
              AND C.ARCARF = M.COD_ARTI
              AND C.ASLOTE = M.LOTE
              AND ROWNUM = 1) PRECIO_COMPRA_CALCULADO,
      M.CANTCONS CANTIDAD_CONSUMIDA,
      M.CANTPROD CANTIDAD_PRODUCIDA, 
      A.FCKG, A.COD_LFS LFS_MP, 
      O.FEC_MODI, 
		  DECODE(O.SITUACIO,'C',O.FEC_MODI) FEC_CIERRE_OT, O.TIP_ARTI TIPO_PRD, O.COD_ARTI ESPECIALIDAD, SUBSTR(AO.COD_LFS,1,2) LINEA, AO.COD_LFS LFS, AO.ANCHO ANCHO_ESPECIALIDAD, O.NUMEPEDI, O.CANTCERR, O.UNIDAD UNIDAD_OT, LO.FCKG FCKG_OT,
      ALB.VUCVEN, ALB.LPCANT, 
		--MP.FASE
		CASE WHEN MP.FASE IS NULL THEN ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material(O.EMPRESA, O.NUMERO, (SELECT MAX(LO.FASE) FROM FIC_LINEOTRE LO
																							   WHERE LO.EMPRESA = O.EMPRESA 
																								  AND LO.NUMERO = O.NUMERO
																								  AND ((INSTR(LO.COD_ARES,'IMPRESORA') != 0) OR
																								       (INSTR(LO.COD_ARES,'CORTADORA') != 0) OR
																										 (INSTR(LO.COD_ARES,'LAMINADORA') != 0) OR
																										 (INSTR(LO.COD_ARES,'LAQUEADORA') != 0))))
            ELSE ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material(O.EMPRESA, O.NUMERO, MP.FASE)
            END N_DE_CORTES
FROM FIC_CABEOTRE O, PRD_MAPAMAQU M, --1
     (SELECT MA.EMPRESA, MA.NUMEOTRE, MA.CONTADOR, DECODE(INSTR(MA.MAQUCODI,'CORTADORA'),0,NULL,L.FASE) FASE, L.FASE FASEBUMP--, MIN(MP.IZQUIERD) IZQUIERD, MIN(MP.DERECHA) DERECHA 
      FROM --PRD_MAQUMPLA MP, 
           (SELECT MR.EMPRESA, MR.NUMEOTRE, MR.CONTADOR, MR.FASESEQU, MR.MAQUTIPO, MR.MAQUCODI, MR.ESTADO FROM PRD_MAQURUTA MR
            WHERE NOT EXISTS (SELECT 'X' FROM PRD_HCABEOTR OTC WHERE OTC.EMPRESA = MR.EMPRESA AND OTC.NUMEOTRE = MR.NUMEOTRE)
            UNION
            SELECT MR.EMPRESA, MR.NUMEOTRE, MR.CONTADOR, MR.FASESEQU, MR.MAQUTIPO, MR.MAQUCODI, MR.ESTADO FROM PRD_HMAQURUT MR) MA, 
           FIC_LINEOTRE L
         WHERE /*MP.EMPRESA = MA.EMPRESA
           AND MP.MAQUTIPO = MA.MAQUTIPO
           AND MP.MAQUCODI = MA.MAQUCODI
           AND */L.EMPRESA = MA.EMPRESA
           AND L.NUMERO = MA.NUMEOTRE
           AND L.TIP_ARES = P_UTILIDAD.F_VALODEVA('TIPORECU')
           AND (L.COD_ARES NOT LIKE 'CORTADORA%' OR --Si es diferente de Cortadora 
                (                                   --o
                 L.COD_ARES LIKE 'CORTADORA%' AND NOT EXISTS (SELECT 'X'
                                                              FROM VALORES_LISTA V
                                                              WHERE V.CODIGO = 'FIC_TIPIRECU'
                                                                AND INSTR(L.COD_ARES,P_UTILIDAD.F_VALOCAMPO(V.VALOR,'RECURSO')) != 0
                                                                AND P_UTILIDAD.F_VALOCAMPO(V.VALOR,'CODIGO') = L.TIPIRECU
                                                                AND P_UTILIDAD.F_VALOCAMPO(V.VALOR,'PRE-CORTE') = 'S')--L.FASE = L.FASESIGU --Si es cortadora pero no es pre-corte
                )
               )
           AND MA.FASESEQU = (L.FASE * 100) + L.SECUENCI
           --AND TIPO = 'E'
      --GROUP BY MA.EMPRESA, MA.NUMEOTRE, MA.CONTADOR, DECODE(INSTR(MA.MAQUCODI,'CORTADORA'),0,NULL,L.FASE)
      ) MP,
     --ARTICULO A, LFS L, 
     (SELECT A.EMPRESA, A.TIP_ARTI, A.COD_ARTI, A.DESCRIPCION, A.ANCHO, L.FCKG, A.COD_LFS FROM ARTICULO A, LFS L WHERE A.EMPRESA = L.EMPRESA AND A.COD_LFS = L.COD_LFS) A,--4
     --CLIENTES C,
     (SELECT C.EMPRESA, C.CLIENTE_ID, C.RAZON_SOC, C.PAIS, P.NOMBRE, M.CLDESC MERCADO FROM CLIENTES C, GNR_PAISES P, FV_ASMATA20 M WHERE C.PAIS = P.PAIS AND C.TIPOPCLI = M.CLCLAS) C,--5
     (SELECT CV.EMPRESA,CV. CLIENTE_ID, CV.VENDEDOR, V.NOMBRE NOMBRE_VENDEDOR FROM GNR_CLVENDED CV, GNR_VENDEDOR V WHERE CV.TIPO = V.TIPO AND CV.VENDEDOR = V.VENDEDOR AND CV.ACTIVA = 'S') V,--6
     (SELECT LO.EMCODI, LO.ASLOTE, LO.CFNDEF, FA.CFFALT, F.VUCVEN, SUM(F.LFCANT) LFCANT, F.VATCOD, F.ARCARF, F.CPNROP
      FROM FV_ASVELO01 LO, FV_ASVEFA01 FA, FV_ASVEFA02 F 
      WHERE LO.EMCODI = FA.EMCODI
        AND LO.CFNDEF = FA.CFNDEF
		  
		  AND LO.CPNROP = F.CPNROP
		  AND LO.ALNROP = F.ALNROP
		  AND LO.VATCOD = F.VATCOD
		  AND LO.ARCARF = F.ARCARF
		  
        AND F.EMCODI = FA.EMCODI
        AND F.DICODI = FA.DICODI
        AND F.ASCANA = FA.ASCANA
        AND F.PPTIPO = FA.PPTIPO
        AND F.CFNROF = FA.CFNROF
        AND F.VATCOD = P_Utilidad.F_ValoDeva('TIARFIF4')
		GROUP BY LO.EMCODI, LO.ASLOTE, LO.CFNDEF, FA.CFFALT, F.VUCVEN, F.VATCOD, F.ARCARF, F.CPNROP) FA,--7
     (SELECT F.EMPRESA, F.TIP_ARTI, F.PRODUCTO, F.MODI, F.REVI, F.ANCHO, F.LARGO, F.MATBASE, L.FCKG, L.DESCRIPCION, F.CLIENTE_ID FROM HFICTEC F, LFS L
      WHERE F.EMPRESA = L.EMPRESA
        AND F.MATBASE = L.COD_LFS
      UNION
      SELECT F.EMPRESA, F.TIP_ARTI, F.PRODUCTO, F.MODI, F.REVI, F.ANCHO, F.LARGO, F.MATBASE, L.FCKG, L.DESCRIPCION, F.CLIENTE_ID FROM FIC_SEGESTI F, LFS L
      WHERE F.EMPRESA = L.EMPRESA
        AND F.MATBASE = L.COD_LFS
     ) FI,
     ARTICULO AO, --2
	  LFS LO,--3
     (SELECT O.EMPRESA, O.NUMERO, A.VUCVEN, SUM(A.LACANT) LPCANT --Unidad y Cantidad de Expedición de Albaranes
            FROM FV_ASVEALH02 A, 
                 FIC_CABEOTRE O,
                 (SELECT DISTINCT EMCODI, CPNROP, ASLOTE, ALNROP, VATCOD, ARCARF, CFNROF FROM FV_ASVELO01 WHERE PROCED = 'F') L
            WHERE A.EMCODI = O.EMPRESA
              AND A.VATCOD = O.TIP_ARTI
              AND A.ARCARF = O.COD_ARTI
              AND A.DICODI = '01'
              AND A.ASCANA = 1
              AND A.CPNROP = O.NUMEPEDI
              AND L.EMCODI = A.EMCODI
              AND L.ALNROP = A.ALNROP
              AND L.VATCOD = A.VATCOD
              AND L.ARCARF = A.ARCARF
              AND L.CPNROP = A.CPNROP
              AND L.EMCODI = O.EMPRESA
              AND L.ASLOTE = TO_CHAR(O.NUMERO)
              AND L.CPNROP = O.NUMEPEDI
              AND NVL(L.CFNROF,0) != 0
              AND EXISTS (SELECT 'X' FROM FV_ASVEFA02 F
                         WHERE F.EMCODI = O.EMPRESA
                           AND F.DICODI = '01'
                           AND F.ASCANA = 1
                           AND F.CPNROP = O.NUMEPEDI
                           AND F.VATCOD = O.TIP_ARTI
                           AND F.ARCARF = O.COD_ARTI)--Este Facturada la OT
              AND NOT EXISTS (SELECT 'X' FROM FIC_LINEPEDI P
                              WHERE P.EMPRESA = O.EMPRESA
                                AND P.NUMEPEDI = O.NUMEPEDI
                                AND P.TIP_ARTI = O.TIP_ARTI
                                AND P.COD_ARTI = O.COD_ARTI)--No quede Pendiente nada por Generar Albaran
              AND O.TIP_ARTI = P_UTILIDAD.F_VALODEVA('TIARFIF4')
         GROUP BY O.EMPRESA, O.NUMERO, A.VUCVEN) ALB/*,
     (SELECT C.EMPRESA, C.NUMEOTRE, C.CONTADOR, C.CONTBOBI, DC.ANCHO 
      FROM PRD_LIBOCORT C,
           (SELECT M.EMPRESA, M.NUMEOTRE, M.FASESEQU, M.CONTADOR FROM PRD_MAQURUTA M
            WHERE NOT EXISTS (SELECT 'X' FROM PRD_HCABEOTR O WHERE O.EMPRESA = M.EMPRESA AND O.NUMEOTRE = M.NUMEOTRE)
            UNION
            SELECT M.EMPRESA, M.NUMEOTRE, M.FASESEQU, M.CONTADOR FROM PRD_HMAQURUT M) M, 
           FIC_LIPCORTR DC 
            WHERE M.EMPRESA = DC.EMPRESA
              AND M.NUMEOTRE = DC.NUMERO
              AND SUBSTR(M.NUMEOTRE,1,4) = DC.ANNO
              AND M.FASESEQU = (DC.FASE * 100) + DC.SECUENCI
              AND M.EMPRESA = C.EMPRESA
              AND M.NUMEOTRE = C.NUMEOTRE
              AND M.CONTADOR = C.CONTADOR
              AND DC.NUM_CORTE = C.NUMECORT) CC*/
              --AND M.EMPRESA = '10'
              --AND M.NUMEOTRE = 2016001095
              --AND C.CONTADOR = 1
             -- AND C.CONTBOBI = 5
WHERE O.EMPRESA = M.EMPRESA
  AND O.NUMERO = M.NUMEOTRE
  --1
  AND O.EMPRESA = AO.EMPRESA
  AND O.TIP_ARTI = AO.TIP_ARTI
  AND O.COD_ARTI = AO.COD_ARTI
  --2
  AND AO.EMPRESA = LO.EMPRESA
  AND AO.COD_LFS = LO.COD_LFS
  --3
  AND M.EMPRESA = A.EMPRESA(+)
  AND M.TIP_ARTI = A.TIP_ARTI(+)
  AND M.COD_ARTI = A.COD_ARTI(+)
  --4
  /*AND M.EMPRESA = CC.EMPRESA(+)
  AND M.NUMEOTRE = CC.NUMEOTRE(+)
  AND M.CONTBOBI = CC.CONTADOR(+)
  AND M.COBOBOBI = CC.CONTBOBI(+)*/
  --
  AND AO.EMPRESA = C.EMPRESA(+)
  AND AO.CLIENASOC = C.CLIENTE_ID(+)
  --5
  AND AO.EMPRESA = V.EMPRESA(+)
  AND AO.CLIENASOC = V.CLIENTE_ID(+)
  --6
  AND O.EMPRESA = FA.EMCODI(+)
  AND O.NUMERO = FA.ASLOTE(+)
  AND O.TIP_ARTI = FA.VATCOD(+)
  AND O.COD_ARTI = FA.ARCARF(+)
  AND O.NUMEPEDI = FA.CPNROP(+)
  --7
  AND O.EMPRESA = FI.EMPRESA(+)
  AND O.TIP_ARTI = FI.TIP_ARTI(+)
  AND O.COD_ARTI = FI.PRODUCTO(+)
  AND NVL(O.MODI,0) = NVL(FI.MODI(+),0)
  AND NVL(O.REVI,0) = NVL(FI.REVI(+),0)
  --
  AND (M.TIP_ARTI IN (P_UTILIDAD.F_VALODEVA('TIARMPF4'),P_UTILIDAD.F_VALODEVA('TIARSEF4'),P_UTILIDAD.F_VALODEVA('TIARFIF4')) OR (M.TIP_ARTI = P_UTILIDAD.F_VALODEVA('TIARCOSC') AND M.NUMEOTRE != M.LOTE))
  --AND A.EMPRESA = L.EMPRESA
  --AND A.COD_LFS = L.COD_LFS
  AND O.EMPRESA = ALB.EMPRESA(+)
  AND O.NUMERO = ALB.NUMERO(+)
  --
  AND M.EMPRESA = MP.EMPRESA(+)
  AND M.NUMEOTRE = MP.NUMEOTRE(+)
  AND M.CONTADOR = MP.CONTADOR(+)
  --
  --AND O.EMPRESA IN ('10','05') AND O.FEC_MODI >= TO_DATE('01-01-2016','DD-MM-YYYY')
  --AND O.NUMERO = 2015004498
  --AND O.EMPRESA = '05' AND O.NUMERO IN (2015000506,2015000406)
  --AND O.EMPRESA = '05' AND O.NUMERO = 2016000059
) M
GROUP BY M.EMPRESA, M.CLIENTE, M.NOMBRE_DEL_CLIENTE, 
      M.PAIS, M.NOMBRE,
      M.VENDEDOR, M.NOMBRE_VENDEDOR, 
      M.OT, 
      M.IMPRESA_ANONIMA,
      M.FEC_CIERRE_OT, 
      M.FACTURA, M.FECHA_FACTURA,
      M.UNIDAD_VENTA, M.CANTIDAD_ML, M.CANTIDAD_M2, M.CANTIDAD_KG, M.CANTIDAD_UN,
      M.TIPO_PRD, M.ESPECIALIDAD, M.LINEA, M.LFS, 
      M.ANCHO_ESPECIALIDAD,
			M.PEDIDO, M.PEDIDO_TM, M.PROVEEDO_TM, M.FECHRECE_TM,
      M.FECHA_CIERRE_OT_SEMIELABORADO, 
			M.TIPO, M.COD_MP, M.ANCHO, M.LFS_MP,
			M.LOTE,
			M.FECHA_RECEPCION, M.FECHA_ENTRADA_ALMACEN,
			M.PROV, M.UNIDAD_COMPRADA, M.PRECIO_COMPRA_CALCULADO, M.FEC_MODI,
			M.FCKG, M.NUMEPEDI, M.UNIDAD_OT, M.CANTCERR, M.FCKG_OT,
      M.VUCVEN, M.LPCANT,--, M.FASE;
		M.N_DE_CORTES;

