CREATE OR REPLACE VIEW "ANALESTA"."ANE_PERSONAL_DEPA_SECC" AS
SELECT PL.EMPRESA, PL.ANNO, PL.MES, SPDE.DEPARTAM, D.DEPARTAM DESCRIPCION_DEPARTAM, PL.SECCION, S.SECCION DESCRIPCION_SECCION, PL.NUMEPERS, PL.NUMEPEUN
FROM ANE_CONFPMSR PL, GNR_SPDEEMPR SPDE, GNR_DEPAEMPR D, GNR_SEPREMPR S
WHERE PL.SECCION = SPDE.SECCION
  AND SPDE.DEPARTAM = D.CODIGO
  AND PL.SECCION = S.CODIGO;