--------------------------------------------------------
--  DDL for View ANE_MC_OT
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "ANALESTA"."ANE_MC_OT" ("NUMERO", "FEC_ALTA", "FEC_CIERRE", "NUMEPEDI", "FEC_ALTA_PEDIDO", "TOTAL_PARTES", "IDENT_PARTE", "SITUACION", "EMPRESA", "CLIENTE_ID", "NOMBRE_CLIENTE", "PAIS", "NOMBRE_PAIS", "VENDEDOR", "NOMBRE_VENDEDOR", "TIP_ARTI", "PRODUCTO", "LINEA", "LFS", "DESCRIPCION_LFS", "ALBARAN", "FECHA_ALBARAN", "FACTURA", "FECHA_FACTURA", "UNIDAD_CIERRE", "CANTIDAD_ML", "CANTIDAD_M2", "CANTIDAD_KG", "CANTIDAD_UN", "FUENTE_DEL_CIERRE") AS 
  SELECT O.NUMERO, O.FEC_ALTA, DECODE(O.SITUACIO,'C',O.FEC_MODI) FEC_CIERRE, P.NUMEPEDI, P.FEC_ALTA FEC_ALTA_PEDIDO,
       (SELECT COUNT(*) FROM FIC_CABEOTTE OTT WHERE OTT.EMPRESA = O.EMPRESA AND OTT.NUMEPEDI = O.NUMEPEDI) TOTAL_PARTES,
       ANALESTA.P_ANE_MERMLAMI_PRAG.F_Numero_Parte(O.EMPRESA,O.NUMEPEDI,O.NUMEOTTE) IDENT_PARTE,
DECODE(
       (SELECT '5' COMPRUEBA
            FROM FV_ASVEFA02 F, 
                 (SELECT DISTINCT EMCODI, DICODI, ASCANA, CFNROF, CPNROP, ASLOTE FROM FV_ASVELO01 WHERE PROCED = 'F') L
            WHERE F.EMCODI = L.EMCODI
              AND F.DICODI = L.DICODI
              AND F.ASCANA = L.ASCANA
              AND F.CFNROF = L.CFNROF
              AND F.CPNROP = L.CPNROP
              AND L.EMCODI = O.EMPRESA
              --AND L.ASLOTE = TO_CHAR(O.NUMERO)
              AND L.ASLOTE = O.NUMERO
              AND L.CPNROP = O.NUMEPEDI
              AND (F.VATCOD = P_UTILIDAD.F_VALODEVA('TIARFIF4') OR 
                   (F.VATCOD = P_UTILIDAD.F_VALODEVA('TIARGCF4') AND 
                    EXISTS (SELECT 'X' FROM VALORES_LISTA LH
                            WHERE LH.CODIGO = 'GNR_ARTIHORA'
                              AND P_UTILIDAD.F_VALOCAMPO(LH.VALOR,'EMPRESA') = F.EMCODI 
                              AND P_UTILIDAD.F_VALOCAMPO(LH.VALOR,'TIP_ARTI') = F.VATCOD 
                              AND P_UTILIDAD.F_VALOCAMPO(LH.VALOR,'COD_ARTI') = F.ARCARF
                           )
                   )
                  )
              AND NVL(L.CFNROF,0) != 0
              AND F.PPTIPO NOT IN ('A','X','B','L','O')
              AND ROWNUM = 1),'5','FACTURADO A CLIENTE',
       DECODE((SELECT '4' COMPRUEBA
            FROM FV_ASVEAL02 A, 
                 (SELECT DISTINCT EMCODI, DICODI, ASCANA, ALNROP, CPNROP, ASLOTE FROM FV_ASVELO01 WHERE NVL(CFNROF,0) = 0) L
            WHERE A.EMCODI = L.EMCODI
              AND A.DICODI = L.DICODI
              AND A.ASCANA = L.ASCANA
              AND A.ALNROP = L.ALNROP
              AND A.CPNROP = L.CPNROP
              AND L.EMCODI = O.EMPRESA
              --AND L.ASLOTE = TO_CHAR(O.NUMERO)
              AND L.ASLOTE = O.NUMERO
              AND L.CPNROP = O.NUMEPEDI
              AND (A.VATCOD = P_UTILIDAD.F_VALODEVA('TIARFIF4') OR 
                   (A.VATCOD = P_UTILIDAD.F_VALODEVA('TIARGCF4') AND 
                    EXISTS (SELECT 'X' FROM VALORES_LISTA LH
                            WHERE LH.CODIGO = 'GNR_ARTIHORA'
                              AND P_UTILIDAD.F_VALOCAMPO(LH.VALOR,'EMPRESA') = A.EMCODI 
                              AND P_UTILIDAD.F_VALOCAMPO(LH.VALOR,'TIP_ARTI') = A.VATCOD 
                              AND P_UTILIDAD.F_VALOCAMPO(LH.VALOR,'COD_ARTI') = A.ARCARF
                           )
                   )
                  )
              AND ROWNUM = 1),'4','ALBARÁN EMITIDO PERO NO FACTURADO',
              DECODE(O.SITUACIO,'C','FINALIZADA',
              DECODE((SELECT '2' FROM PRD_PRMAEVEN E WHERE E.EMPRESA = O.EMPRESA AND E.NUMEOTRE = O.NUMERO AND ROWNUM = 1),'2','EN CURSO',
              DECODE((SELECT '2' FROM PRD_CAPAMAQU E WHERE E.EMPRESA = O.EMPRESA AND E.NUMEOTRE = O.NUMERO AND ROWNUM = 1),'2','EN CURSO',
              'NO INCIADO'))))) SITUACION,
O.EMPRESA, 
F.CLIENTE_ID, C.RAZON_SOC NOMBRE_CLIENTE,
C.PAIS, C.NOMBRE NOMBRE_PAIS,
V.VENDEDOR, V.NOMBRE_VENDEDOR,
F.TIP_ARTI, F.PRODUCTO, SUBSTR(F.MATBASE,1,2) LINEA, F.MATBASE LFS, LFS.DESCRIPCION DESCRIPCION_LFS, AL.ALNROP ALBARAN, AL.ALFALT FECHA_ALBARAN, FA.CFNDEF FACTURA, FA.CFFALT FECHA_FACTURA,
--O.UNIDAD,
DECODE(NVL(ALB.LPCANT,0),0,O.UNIDAD,ALB.VUCVEN) UNIDAD_CIERRE,
			DECODE(DECODE(NVL(ALB.LPCANT,0),0,O.UNIDAD,ALB.VUCVEN),P_Utilidad.F_ValoDeva('TIPOUNML'),1,DECODE(NVL(F.ANCHO,0),0,0,DECODE(DECODE(NVL(ALB.LPCANT,0),0,O.UNIDAD,ALB.VUCVEN),P_Utilidad.F_ValoDeva('TIPOUNKG'),LFS.FCKG * (1000 / F.ANCHO),
                                                                                                        P_Utilidad.F_ValoDeva('TIPOUNM2'),(1000 / F.ANCHO),
                                                                                                        P_Utilidad.F_ValoDeva('TIPOUNUN'),(1000 / F.ANCHO) * ((F.ANCHO * F.LARGO) / 1000000)))) * DECODE(NVL(ALB.LPCANT,0),0,O.CANTCERR,ALB.LPCANT) CANTIDAD_ML,
         DECODE(DECODE(NVL(ALB.LPCANT,0),0,O.UNIDAD,ALB.VUCVEN),P_Utilidad.F_ValoDeva('TIPOUNM2'),1,P_Utilidad.F_ValoDeva('TIPOUNKG'),LFS.FCKG,
                                                             P_Utilidad.F_ValoDeva('TIPOUNML'),(F.ANCHO / 1000),
                                                             P_Utilidad.F_ValoDeva('TIPOUNUN'),(F.ANCHO * F.LARGO) / 1000000) * DECODE(NVL(ALB.LPCANT,0),0,O.CANTCERR,ALB.LPCANT) CANTIDAD_M2,
         DECODE(DECODE(NVL(ALB.LPCANT,0),0,O.UNIDAD,ALB.VUCVEN),P_Utilidad.F_ValoDeva('TIPOUNKG'),1,DECODE(NVL(LFS.FCKG,0),0,0,DECODE(DECODE(NVL(ALB.LPCANT,0),0,O.UNIDAD,ALB.VUCVEN),P_Utilidad.F_ValoDeva('TIPOUNML'),(1 / LFS.FCKG) * (F.ANCHO / 1000),
                                                                                                        P_Utilidad.F_ValoDeva('TIPOUNM2'),1 / LFS.FCKG,
                                                                                                        P_Utilidad.F_ValoDeva('TIPOUNUN'),(1 / LFS.FCKG) * ((F.ANCHO * F.LARGO) / 1000000)))) * DECODE(NVL(ALB.LPCANT,0),0,O.CANTCERR,ALB.LPCANT) CANTIDAD_KG,
			DECODE(DECODE(NVL(ALB.LPCANT,0),0,O.UNIDAD,ALB.VUCVEN),P_Utilidad.F_ValoDeva('TIPOUNUN'),1,P_Utilidad.F_ValoDeva('TIPOUNML'),DECODE(NVL(F.ANCHO,0)*NVL(F.LARGO,0),0,0,(1 / ((1000 / F.ANCHO) * ((F.ANCHO * F.LARGO) / 1000000)))),
                                                                              P_Utilidad.F_ValoDeva('TIPOUNM2'),DECODE(NVL(F.ANCHO,0)*NVL(F.LARGO,0),0,0,(1000000 / (F.ANCHO * F.LARGO))),
                                                                              P_Utilidad.F_ValoDeva('TIPOUNKG'),DECODE(NVL(F.ANCHO,0)*NVL(F.LARGO,0)*NVL(LFS.FCKG,0),0,0,(1 / ((1 / LFS.FCKG) * ((F.ANCHO * F.LARGO) / 1000000))))) * DECODE(NVL(ALB.LPCANT,0),0,O.CANTCERR,ALB.LPCANT) CANTIDAD_UN,
DECODE(NVL(ALB.LPCANT,0),0,'CIERRE DE OT','EXPEDICION') FUENTE_DEL_CIERRE
FROM FIC_CABEOTRE O,
     HFICTEC F, LFS,
     (SELECT C.EMPRESA, C.CLIENTE_ID, C.RAZON_SOC, C.PAIS, P.NOMBRE FROM CLIENTES C, GNR_PAISES P WHERE C.PAIS = P.PAIS) C,
     (SELECT CV.EMPRESA,CV. CLIENTE_ID, CV.VENDEDOR, V.NOMBRE NOMBRE_VENDEDOR FROM GNR_CLVENDED CV, GNR_VENDEDOR V WHERE CV.TIPO = V.TIPO AND CV.VENDEDOR = V.VENDEDOR AND CV.ACTIVA = 'S') V,
     FIC_HCABEPED P,
     (SELECT LO.EMCODI, LO.ASLOTE, LO.ALNROP, AL.ALFALT
      FROM FV_ASVELO01 LO,
      (SELECT HA.EMCODI, HA.ALNROP, HA.ALFALT FROM FV_ASVEALH01 HA
       UNION
       SELECT AL.EMCODI, AL.ALNROP, AL.ALFALT FROM FV_ASVEAL01 AL WHERE NOT EXISTS (SELECT 'X' FROM FV_ASVEALH01 HA WHERE HA.EMCODI = AL.EMCODI AND HA.DICODI = AL.DICODI AND HA.ASCANA = AL.ASCANA AND HA.PPTIPO = AL.PPTIPO AND HA.ALNROP = AL.ALNROP)) AL
      WHERE LO.EMCODI = AL.EMCODI
        AND LO.ALNROP = AL.ALNROP) AL,
     (SELECT LO.EMCODI, LO.ASLOTE, LO.CFNDEF, FA.CFFALT
      FROM FV_ASVELO01 LO, FV_ASVEFA01 FA
      WHERE LO.EMCODI = FA.EMCODI
        AND LO.CFNDEF = FA.CFNDEF) FA,
     (SELECT O.EMPRESA, O.NUMERO, A.VUCVEN, SUM(A.LACANT) LPCANT --Unidad y Cantidad de Expedición de Albaranes
            FROM FV_ASVEALH02 A, 
                 FIC_CABEOTRE O,
                 (SELECT DISTINCT EMCODI, CPNROP, ASLOTE, ALNROP, VATCOD, ARCARF, CFNROF FROM FV_ASVELO01 WHERE PROCED = 'F') L
            WHERE A.EMCODI = O.EMPRESA
              AND A.VATCOD = O.TIP_ARTI
              AND A.ARCARF = O.COD_ARTI
              AND A.DICODI = '01'
              AND A.ASCANA = 1
              AND A.CPNROP = O.NUMEPEDI
              AND L.EMCODI = A.EMCODI
              AND L.ALNROP = A.ALNROP
              AND L.VATCOD = A.VATCOD
              AND L.ARCARF = A.ARCARF
              AND L.CPNROP = A.CPNROP
              AND L.EMCODI = O.EMPRESA
              AND L.ASLOTE = TO_CHAR(O.NUMERO)
              AND L.CPNROP = O.NUMEPEDI
              AND NVL(L.CFNROF,0) != 0
              AND EXISTS (SELECT 'X' FROM FV_ASVEFA02 F
                         WHERE F.EMCODI = O.EMPRESA
                           AND F.DICODI = '01'
                           AND F.ASCANA = 1
                           AND F.CPNROP = O.NUMEPEDI
                           AND F.VATCOD = O.TIP_ARTI
                           AND F.ARCARF = O.COD_ARTI)--Este Facturada la OT
              /*AND NOT EXISTS (SELECT 'X' FROM FIC_LINEPEDI P
                              WHERE P.EMPRESA = O.EMPRESA
                                AND P.NUMEPEDI = O.NUMEPEDI
                                AND P.TIP_ARTI = O.TIP_ARTI
                                AND P.COD_ARTI = O.COD_ARTI)--No quede Pendiente nada por Generar Albaran*/
              AND O.TIP_ARTI = P_UTILIDAD.F_VALODEVA('TIARFIF4')
         GROUP BY O.EMPRESA, O.NUMERO, A.VUCVEN) ALB
WHERE O.EMPRESA = F.EMPRESA
  AND O.TIP_ARTI = F.TIP_ARTI
  AND O.COD_ARTI = F.PRODUCTO
  AND O.MODI = F.MODI
  AND O.REVI = F.REVI
  AND F.EMPRESA = LFS.EMPRESA
  AND F.MATBASE = LFS.COD_LFS
  AND F.EMPRESA = C.EMPRESA
  AND F.CLIENTE_ID = C.CLIENTE_ID
  AND F.EMPRESA = V.EMPRESA(+)
  AND F.CLIENTE_ID = V.CLIENTE_ID(+)
  AND O.TIP_ARTI = P_UTILIDAD.F_VALODEVA('TIARFIF4')
  AND O.EMPRESA = P.EMPRESA
  AND O.NUMEPEDI = P.NUMEPEDI
  AND P.TIPOACCI = 'I'
  AND O.EMPRESA = AL.EMCODI(+)
  AND O.NUMERO = AL.ASLOTE(+)
  AND O.EMPRESA = FA.EMCODI(+)
  AND O.NUMERO = FA.ASLOTE(+)
  AND O.EMPRESA = ALB.EMPRESA(+)
  AND O.NUMERO = ALB.NUMERO(+)
  --AND O.EMPRESA IN ('10','05') AND O.FEC_MODI >= TO_DATE('01-01-2016','DD-MM-YYYY');;
