CREATE OR REPLACE VIEW "ANALESTA"."ANE_COSTES_SECC_PRODU_ANNO_MES" AS 
SELECT S.EMPRESA, S.ANNO, S.MES, NULL SECCION, TIPOMAQU DESCRIPCION_SECCION, S.COSTREAL COSTE_DIRECTO_REAL, S.COINREAL COSTE_INDIRECTO_REAL, S.COSRREAL COSTE_SUBREPARTO_REAL, S.HOREEFCO HORAS_REALES_EFECTIVAS, S.UNGRREAL UNIDADES_GRATIFICACION_REAL
FROM PRD_SECCANCO S
WHERE S.EMPRESA IN (SELECT VALOR FROM VALORES_LISTA WHERE CODIGO = 'GNR_EMPRACGR')
UNION
SELECT S.EMPRESA, S.ANNO, S.MES, SE.CODIGO SECCION, SE.SECCION DESCRIPCION_SECCION, S.COSTREAL COSTE_DIRECTO_REAL, S.COINREAL COSTE_INDIRECTO_REAL, S.COSRREAL COSTE_SUBREPARTO_REAL, S.HOREEFCO HORAS_REALES_EFECTIVAS, S.UNGRREAL UNIDADES_GRATIFICACION_REAL
FROM ANE_CODEANMS S, GNR_SEPREMPR SE
WHERE S.EMPRESA IN (SELECT VALOR FROM VALORES_LISTA WHERE CODIGO = 'GNR_EMPRACGR')
  AND S.SECCION = SE.CODIGO
  AND S.SECCION NOT IN (P_UTILIDAD.F_VALODEVA('COSEIMPR'),P_UTILIDAD.F_VALODEVA('COSELAMI'),P_UTILIDAD.F_VALODEVA('COSELAQU'),P_UTILIDAD.F_VALODEVA('COSECORT'));