--------------------------------------------------------
--  DDL for View ANE_ENERGIA
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "ANALESTA"."ANE_ENERGIA" ("EMPRESA", "N_CLIENTE", "CLIENTE", "OT", "FECHA_CIERRE_OT", "N_PEDIDO", "IMPRESA_ANONIMA", "ESPECIALIDAD", "LINEA", "LFS", "TIPO_PRODUCTO", "CANTIDAD_DE_FASES", "IDENTIFICACION_DEL_N_DE_FASE", "SECCION_PRODUCTIVA", "MAQUINA", "ML_PASADOS_MAQUINA") AS 
  SELECT O.EMPRESA, F.CLIENTE_ID N_CLIENTE, C.RAZON_SOC CLIENTE, O.NUMERO OT, DECODE(O.SITUACIO,'C',O.FEC_MODI) FECHA_CIERRE_OT, O.NUMEPEDI N_PEDIDO,
         DECODE(O.TIP_ARTI,P_UTILIDAD.F_VALODEVA('TIARFIF4'),DECODE(SUBSTR(O.COD_ARTI,3,1),P_UTILIDAD.F_VALODEVA('TIPOPROY'),'ANONIMA','IMPRESA')) IMPRESA_ANONIMA,
         O.COD_ARTI ESPECIALIDAD, SUBSTR(F.MATBASE,1,2) LINEA, F.MATBASE LFS, O.TIP_ARTI TIPO_PRODUCTO,
         DECODE((SELECT 'X' FROM PRD_HCABEOTR OTC WHERE OTC.EMPRESA = O.EMPRESA AND OTC.NUMEOTRE = O.NUMERO),NULL,
                 (SELECT COUNT(*) FASES FROM PRD_MAQURUTA MR
                  WHERE NOT EXISTS (SELECT 'X' FROM PRD_HCABEOTR OTC WHERE OTC.EMPRESA = MR.EMPRESA AND OTC.NUMEOTRE = MR.NUMEOTRE)
                    AND MR.EMPRESA = O.EMPRESA
                    AND MR.NUMEOTRE = O.NUMERO
                    AND MR.MAQUCODI != P_UTILIDAD.F_VALODEVA('MAQUALMA')),
                 (SELECT COUNT(*) FASES FROM PRD_HMAQURUT MR
                  WHERE MR.EMPRESA = O.EMPRESA
                    AND MR.NUMEOTRE = O.NUMERO
                    AND MR.MAQUCODI != P_UTILIDAD.F_VALODEVA('MAQUALMA'))
                 ) CANTIDAD_DE_FASES,
         MA.CONTADOR IDENTIFICACION_DEL_N_DE_FASE,
         DECODE(INSTR(MA.MAQUCODI,'CORTADORA'),1,'Sección Cortadoras',DECODE(INSTR(MA.MAQUCODI,'IMPRESORA'),1,'Sección Impresoras',DECODE(INSTR(MA.MAQUCODI,'LAMINADORA'),1,'Sección Laminadoras',DECODE(INSTR(MA.MAQUCODI,'LAQUEADORA'),1,'Sección Laqueadoras')))) SECCION_PRODUCTIVA,
         MA.MAQUCODI MAQUINA,
         SUM(EC.CANTPROD) ML_PASADOS_MAQUINA
  FROM FIC_CABEOTRE O, 
       CLIENTES C,
       HFICTEC F,
       (SELECT MR.EMPRESA, MR.NUMEOTRE, MR.FASESEQU, MR.MAQUTIPO, MR.MAQUCODI, MR.CONTADOR FROM PRD_MAQURUTA MR
        WHERE NOT EXISTS (SELECT 'X' FROM PRD_HCABEOTR OTC WHERE OTC.EMPRESA = MR.EMPRESA AND OTC.NUMEOTRE = MR.NUMEOTRE)
        UNION
        SELECT MR.EMPRESA, MR.NUMEOTRE, MR.FASESEQU, MR.MAQUTIPO, MR.MAQUCODI, MR.CONTADOR FROM PRD_HMAQURUT MR) MA,
       PRD_PASAMAQU EC
  WHERE O.EMPRESA = F.EMPRESA
    AND O.TIP_ARTI = F.TIP_ARTI AND O.COD_ARTI = F.PRODUCTO AND O.MODI = F.MODI AND O.REVI = F.REVI
    AND F.EMPRESA = C.EMPRESA
    AND F.CLIENTE_ID = C.CLIENTE_ID
    AND O.EMPRESA = MA.EMPRESA
    AND O.NUMERO = MA.NUMEOTRE
    AND EC.EMPRESA = MA.EMPRESA
    AND EC.NUMEOTRE = MA.NUMEOTRE
    AND EC.CONTADOR = MA.CONTADOR
    
    --AND O.NUMEPEDI LIKE '2016%'
    --AND O.EMPRESA IN ('10','05') AND TRUNC(O.FEC_MODI) BETWEEN TO_DATE('01-01-2016','DD-MM-YYYY') AND TO_DATE('31-12-2016','DD-MM-YYYY')
  GROUP BY O.EMPRESA, F.CLIENTE_ID, C.RAZON_SOC, O.NUMERO, DECODE(O.SITUACIO,'C',O.FEC_MODI), O.NUMEPEDI,
           DECODE(O.TIP_ARTI,P_UTILIDAD.F_VALODEVA('TIARFIF4'),DECODE(SUBSTR(O.COD_ARTI,3,1),P_UTILIDAD.F_VALODEVA('TIPOPROY'),'ANONIMA','IMPRESA')),
           O.COD_ARTI, SUBSTR(F.MATBASE,1,2), F.MATBASE, O.TIP_ARTI,
         MA.CONTADOR,
         DECODE(INSTR(MA.MAQUCODI,'CORTADORA'),1,'Sección Cortadoras',DECODE(INSTR(MA.MAQUCODI,'IMPRESORA'),1,'Sección Impresoras',DECODE(INSTR(MA.MAQUCODI,'LAMINADORA'),1,'Sección Laminadoras',DECODE(INSTR(MA.MAQUCODI,'LAQUEADORA'),1,'Sección Laqueadoras')))),
         MA.MAQUCODI
  UNION ALL
  SELECT CO.EMPRESA, CO.N_CLIENTE, CO.CLIENTE, CO.OT, CO.FECHA_CIERRE_OT, CO.N_PEDIDO,
          NVL((SELECT 'IMPRESA' FROM FIC_LINEOTRE LO WHERE LO.EMPRESA = CO.EMPRESA AND LO.NUMERO = CO.OT AND INSTR(LO.COD_ARES,'IMPRESORA') != 0 AND ROWNUM = 1),'ANONIMA') IMPRESA_ANONIMA,
          CO.ESPECIALIDAD, CO.LINEA, CO.LFS, CO.TIPO_PRODUCTO, CO.CANTIDAD_DE_FASES, CO.IDENTIFICACION_DEL_N_DE_FASE, CO.SECCION_PRODUCTIVA, CO.MAQUINA, CO.ML_PASADOS_MAQUINA FROM (
  SELECT O.EMPRESA, NULL N_CLIENTE, NULL CLIENTE, O.NUMERO OT, DECODE(O.SITUACIO,'C',O.FEC_MODI) FECHA_CIERRE_OT, O.NUMEPEDI N_PEDIDO,
         O.COD_ARTI ESPECIALIDAD, SUBSTR(F.MATBASE,1,2) LINEA, F.MATBASE LFS, O.TIP_ARTI TIPO_PRODUCTO,
         DECODE((SELECT 'X' FROM PRD_HCABEOTR OTC WHERE OTC.EMPRESA = O.EMPRESA AND OTC.NUMEOTRE = O.NUMERO),NULL,
                 (SELECT COUNT(*) FASES FROM PRD_MAQURUTA MR
                  WHERE NOT EXISTS (SELECT 'X' FROM PRD_HCABEOTR OTC WHERE OTC.EMPRESA = MR.EMPRESA AND OTC.NUMEOTRE = MR.NUMEOTRE)
                    AND MR.EMPRESA = O.EMPRESA
                    AND MR.NUMEOTRE = O.NUMERO
                    AND MR.MAQUCODI != P_UTILIDAD.F_VALODEVA('MAQUALMA')),
                 (SELECT COUNT(*) FASES FROM PRD_HMAQURUT MR
                  WHERE MR.EMPRESA = O.EMPRESA
                    AND MR.NUMEOTRE = O.NUMERO
                    AND MR.MAQUCODI != P_UTILIDAD.F_VALODEVA('MAQUALMA'))
                 ) CANTIDAD_DE_FASES,
         MA.CONTADOR IDENTIFICACION_DEL_N_DE_FASE,
         DECODE(INSTR(MA.MAQUCODI,'CORTADORA'),1,'Sección Cortadoras',DECODE(INSTR(MA.MAQUCODI,'IMPRESORA'),1,'Sección Impresoras',DECODE(INSTR(MA.MAQUCODI,'LAMINADORA'),1,'Sección Laminadoras',DECODE(INSTR(MA.MAQUCODI,'LAQUEADORA'),1,'Sección Laqueadoras')))) SECCION_PRODUCTIVA,
         MA.MAQUCODI MAQUINA,
         SUM(EC.CANTPROD) ML_PASADOS_MAQUINA
  FROM FIC_CABEOTRE O,
       FIC_SEGESTI F,
       (SELECT MR.EMPRESA, MR.NUMEOTRE, MR.FASESEQU, MR.MAQUTIPO, MR.MAQUCODI, MR.CONTADOR FROM PRD_MAQURUTA MR
        WHERE NOT EXISTS (SELECT 'X' FROM PRD_HCABEOTR OTC WHERE OTC.EMPRESA = MR.EMPRESA AND OTC.NUMEOTRE = MR.NUMEOTRE)
        UNION
        SELECT MR.EMPRESA, MR.NUMEOTRE, MR.FASESEQU, MR.MAQUTIPO, MR.MAQUCODI, MR.CONTADOR FROM PRD_HMAQURUT MR) MA,
       PRD_PASAMAQU EC
  WHERE O.EMPRESA = F.EMPRESA
    AND O.TIP_ARTI = P_UTILIDAD.F_VALODEVA('TIARSEF4') AND O.TIP_ARTI = F.TIP_ARTI AND O.COD_ARTI = F.PRODUCTO
    AND O.EMPRESA = MA.EMPRESA
    AND O.NUMERO = MA.NUMEOTRE
    AND EC.EMPRESA = MA.EMPRESA
    AND EC.NUMEOTRE = MA.NUMEOTRE
    AND EC.CONTADOR = MA.CONTADOR
    
    --AND O.NUMEPEDI LIKE '2016%'
    --AND O.EMPRESA IN ('10','05') AND TRUNC(O.FEC_MODI) BETWEEN TO_DATE('01-01-2016','DD-MM-YYYY') AND TO_DATE('31-12-2016','DD-MM-YYYY')
  GROUP BY O.EMPRESA, O.NUMERO, DECODE(O.SITUACIO,'C',O.FEC_MODI), O.NUMEPEDI,
           O.COD_ARTI, SUBSTR(F.MATBASE,1,2), F.MATBASE, O.TIP_ARTI,
         MA.CONTADOR,
         DECODE(INSTR(MA.MAQUCODI,'CORTADORA'),1,'Sección Cortadoras',DECODE(INSTR(MA.MAQUCODI,'IMPRESORA'),1,'Sección Impresoras',DECODE(INSTR(MA.MAQUCODI,'LAMINADORA'),1,'Sección Laminadoras',DECODE(INSTR(MA.MAQUCODI,'LAQUEADORA'),1,'Sección Laqueadoras')))),
         MA.MAQUCODI) CO
   UNION ALL
   SELECT CO.EMPRESA, CO.N_CLIENTE, CO.CLIENTE, CO.OT, CO.FECHA_CIERRE_OT, CO.N_PEDIDO,
          NVL((SELECT 'IMPRESA' FROM FIC_LINEOTRE LO WHERE LO.EMPRESA = CO.EMPRESA AND LO.NUMERO = CO.OT AND INSTR(LO.COD_ARES,'IMPRESORA') != 0 AND ROWNUM = 1),'ANONIMA') IMPRESA_ANONIMA,
          CO.ESPECIALIDAD, CO.LINEA, CO.LFS, CO.TIPO_PRODUCTO, CO.CANTIDAD_DE_FASES, CO.IDENTIFICACION_DEL_N_DE_FASE, CO.SECCION_PRODUCTIVA, CO.MAQUINA, CO.ML_PASADOS_MAQUINA FROM (
   SELECT O.EMPRESA, F.CLIENTE_ID N_CLIENTE, C.RAZON_SOC CLIENTE, O.NUMERO OT, DECODE(O.SITUACIO,'C',O.FEC_MODI) FECHA_CIERRE_OT, O.NUMEPEDI N_PEDIDO,
         O.COD_ARTI ESPECIALIDAD, SUBSTR(F.MATBASE,1,2) LINEA, F.MATBASE LFS, O.TIP_ARTI TIPO_PRODUCTO,
         DECODE((SELECT 'X' FROM PRD_HCABEOTR OTC WHERE OTC.EMPRESA = O.EMPRESA AND OTC.NUMEOTRE = O.NUMERO),NULL,
                 (SELECT COUNT(*) FASES FROM PRD_MAQURUTA MR
                  WHERE NOT EXISTS (SELECT 'X' FROM PRD_HCABEOTR OTC WHERE OTC.EMPRESA = MR.EMPRESA AND OTC.NUMEOTRE = MR.NUMEOTRE)
                    AND MR.EMPRESA = O.EMPRESA
                    AND MR.NUMEOTRE = O.NUMERO
                    AND MR.MAQUCODI != P_UTILIDAD.F_VALODEVA('MAQUALMA')),
                 (SELECT COUNT(*) FASES FROM PRD_HMAQURUT MR
                  WHERE MR.EMPRESA = O.EMPRESA
                    AND MR.NUMEOTRE = O.NUMERO
                    AND MR.MAQUCODI != P_UTILIDAD.F_VALODEVA('MAQUALMA'))
                 ) CANTIDAD_DE_FASES,
         MA.CONTADOR IDENTIFICACION_DEL_N_DE_FASE,
         DECODE(INSTR(MA.MAQUCODI,'CORTADORA'),1,'Sección Cortadoras',DECODE(INSTR(MA.MAQUCODI,'IMPRESORA'),1,'Sección Impresoras',DECODE(INSTR(MA.MAQUCODI,'LAMINADORA'),1,'Sección Laminadoras',DECODE(INSTR(MA.MAQUCODI,'LAQUEADORA'),1,'Sección Laqueadoras')))) SECCION_PRODUCTIVA,
         MA.MAQUCODI MAQUINA,
         SUM(EC.CANTPROD) ML_PASADOS_MAQUINA
  FROM FIC_CABEOTRE O, 
       CLIENTES C,
       FIC_HPIGESTI F,
       (SELECT MR.EMPRESA, MR.NUMEOTRE, MR.FASESEQU, MR.MAQUTIPO, MR.MAQUCODI, MR.CONTADOR FROM PRD_MAQURUTA MR
        WHERE NOT EXISTS (SELECT 'X' FROM PRD_HCABEOTR OTC WHERE OTC.EMPRESA = MR.EMPRESA AND OTC.NUMEOTRE = MR.NUMEOTRE)
        UNION
        SELECT MR.EMPRESA, MR.NUMEOTRE, MR.FASESEQU, MR.MAQUTIPO, MR.MAQUCODI, MR.CONTADOR FROM PRD_HMAQURUT MR) MA,
       PRD_PASAMAQU EC
  WHERE O.EMPRESA = F.EMPRESA
    AND O.NUMEPEDI = F.NUMEPEDI
    AND F.EMPRESA = C.EMPRESA(+)
    AND F.CLIENTE_ID = C.CLIENTE_ID(+)
    AND O.EMPRESA = MA.EMPRESA
    AND O.NUMERO = MA.NUMEOTRE
    AND EC.EMPRESA = MA.EMPRESA
    AND EC.NUMEOTRE = MA.NUMEOTRE
    AND EC.CONTADOR = MA.CONTADOR
    
    --AND O.NUMEPEDI LIKE '2016%'
    --AND O.EMPRESA IN ('10','05') AND TRUNC(O.FEC_MODI) BETWEEN TO_DATE('01-01-2016','DD-MM-YYYY') AND TO_DATE('31-12-2016','DD-MM-YYYY')
  GROUP BY O.EMPRESA, F.CLIENTE_ID, C.RAZON_SOC, O.NUMERO, DECODE(O.SITUACIO,'C',O.FEC_MODI), O.NUMEPEDI,
           O.COD_ARTI, SUBSTR(F.MATBASE,1,2), F.MATBASE, O.TIP_ARTI,
         MA.CONTADOR,
         DECODE(INSTR(MA.MAQUCODI,'CORTADORA'),1,'Sección Cortadoras',DECODE(INSTR(MA.MAQUCODI,'IMPRESORA'),1,'Sección Impresoras',DECODE(INSTR(MA.MAQUCODI,'LAMINADORA'),1,'Sección Laminadoras',DECODE(INSTR(MA.MAQUCODI,'LAQUEADORA'),1,'Sección Laqueadoras')))),
         MA.MAQUCODI) CO
         
    --ORDER BY O.EMPRESA, O.NUMERO, MA.CONTADOR;
