CREATE OR REPLACE VIEW "ANALESTA"."ANE_MER_CONFIG_MERMAS_SISTEMA" AS 
SELECT P_UTILIDAD.F_VALOCAMPO(VALOR,'MAQUINA') MAQUINA, P_UTILIDAD.F_VALOCAMPO(VALOR,'MERMA') MERMA, P_UTILIDAD.F_VALOCAMPO(VALOR,'CARACTERISTICA') CARACTERISTICA, P_UTILIDAD.F_VALOCAMPO(VALOR,'EVENCODI') EVENCODI, P_UTILIDAD.F_VALOCAMPO(VALOR,'CAPTACION') CAPTACION
FROM VALORES_LISTA WHERE CODIGO = 'PRD_EQCAMERM'
UNION
SELECT P_UTILIDAD.F_VALOCAMPO(VALOR,'MAQUINA') MAQUINA, P_UTILIDAD.F_VALOCAMPO(VALOR,'MERMA') MERMA, P_UTILIDAD.F_VALOCAMPO(VALOR,'CARACTERISTICA2') CARACTERISTICA, P_UTILIDAD.F_VALOCAMPO(VALOR,'EVENCODI') EVENCODI, P_UTILIDAD.F_VALOCAMPO(VALOR,'CAPTACION') CAPTACION
FROM VALORES_LISTA WHERE CODIGO = 'PRD_EQCAMERM'
AND P_UTILIDAD.F_VALOCAMPO(VALOR,'CARACTERISTICA2') IS NOT NULL;