--TIMP_CM, TLAM_CM, TLAQ_CM, TCOR_CM, PMON_CM, COSE_IMP, COSE_LAM, COSE_LAQ, COSE_COR, COSE_MON, MIMP_CM, MLAM_CM, MLAQ_CM, MCOR_CM
--
  CREATE OR REPLACE VIEW "ANALESTA"."ANE_ORDENES_DE_TRABAJO_P4" AS 
  SELECT O.EMPRESA, O.NUMERO NUMERO_OT, O.ANNO ANNO_OT, O.SITUACIO, O.FEC_MODI FECHA_MODIFICACION_OT, TO_CHAR(O.FEC_MODI,'YYYY') ANNO_MODIFICACION_OT, TO_CHAR(O.FEC_MODI,'MM') MES_MODIFICACION_OT,
         CL.CLIENTE_ID, CL.RAZON_SOC, CL.VENDEDOR, CL.TIPO_VENDEDOR, CL.DESCRIPCION_VENEDEDOR, CL.VENCIMIENTO_FX,
         O.TIP_ARTI TIP_ARTI_OT, O.COD_ARTI COD_ARTI_OT, A.DESCRIPCION DESCRIPCION_ARTICULO_OT, O.MODI MODIFICACION, O.REVI REVISION, DECODE(O.TIP_ARTI,P_Utilidad.F_ValoDeva('TIARFIF4'), DECODE(SUBSTR(O.COD_ARTI,3,1), P_Utilidad.F_ValoDeva('TIPOPROY'), 'ANONIMO', 'IMPRESO')) TIPO_ARTICULO,
         P_GNR_AGRUESTR.F_ASIGNA_AGRUESTR(O.EMPRESA, SUBSTR(O.COD_ARTI,4,4),O.TIP_ARTI, O.COD_ARTI) AGRUPACION_ESTRATEGICA,
         O.NUMEPEDI PEDIDO_OT, O.LINEPEDI LINEA_PEDIDO_OT, NVL(LP.TIPOPEDI,'NE') TIPO_DE_PEDIDO, P.REFEENPM REFERENCIA_PEDIDO_MATRIZ_OT, 
         P.DIREENVI CODIGO_DIRECCION_ENVIO, P.PAIS CODIGO_PAIS_DIREC_ENVIO_PEDIDO, P.NOMBRE PAIS_DIREC_ENVIO_PEDIDO, CL.PAIS CODIGO_PAIS_CLIENTE, CL.DESCRIPCION_PAIS PAIS_CLIENTE, 
         DECODE(P.PAIS, NULL,CL.PAIS,P.PAIS) CODIGO_PAIS_ENTREGA, DECODE(P.NOMBRE, NULL,CL.DESCRIPCION_PAIS,P.NOMBRE) PAIS_ENTREGA, DECODE(DECODE(P.PAIS, NULL,CL.PAIS,P.PAIS),NULL,'N',P_Utilidad.F_ValoDeva('PAISESPA'),'N','E') TIPO_PEDIDO,
         O.CANTCERR CANTIDAD_CERRADA_OT, O.UNIDAD UNIDAD_CERRADA_OT, 
         DECODE(O.UNIDAD,P_Utilidad.F_ValoDeva('TIPOUNML'),1,DECODE(NVL(FI.ANCHO,0),0,0,DECODE(O.UNIDAD,P_Utilidad.F_ValoDeva('TIPOUNKG'),FI.FCKG * (1000 / FI.ANCHO),
                                                                                                         P_Utilidad.F_ValoDeva('TIPOUNM2'),(1000 / FI.ANCHO),
                                                                                                         P_Utilidad.F_ValoDeva('TIPOUNUN'),(1000 / FI.ANCHO) * ((FI.ANCHO * FI.LARGO) / 1000000)))) FACTOR_ML_CIERRE_OT_FX, 
         O.CANTCERR * 
         DECODE(O.UNIDAD,P_Utilidad.F_ValoDeva('TIPOUNML'),1,DECODE(NVL(FI.ANCHO,0),0,0,DECODE(O.UNIDAD,P_Utilidad.F_ValoDeva('TIPOUNKG'),FI.FCKG * (1000 / FI.ANCHO),
                                                                                                         P_Utilidad.F_ValoDeva('TIPOUNM2'),(1000 / FI.ANCHO),
                                                                                                         P_Utilidad.F_ValoDeva('TIPOUNUN'),(1000 / FI.ANCHO) * ((FI.ANCHO * FI.LARGO) / 1000000))))
         CANTIDAD_CERRADA_OT_ML,
         DECODE(O.UNIDAD,P_Utilidad.F_ValoDeva('TIPOUNM2'),1,P_Utilidad.F_ValoDeva('TIPOUNKG'),FI.FCKG,
                                                               P_Utilidad.F_ValoDeva('TIPOUNML'),(FI.ANCHO / 1000),
                                                               P_Utilidad.F_ValoDeva('TIPOUNUN'),(FI.ANCHO * FI.LARGO) / 1000000) FACTOR_M2_CIERRE_OT_FX,
         O.CANTCERR *
         DECODE(O.UNIDAD,P_Utilidad.F_ValoDeva('TIPOUNM2'),1,P_Utilidad.F_ValoDeva('TIPOUNKG'),FI.FCKG,
                                                               P_Utilidad.F_ValoDeva('TIPOUNML'),(FI.ANCHO / 1000),
                                                               P_Utilidad.F_ValoDeva('TIPOUNUN'),(FI.ANCHO * FI.LARGO) / 1000000)
         CANTIDAD_CERRADA_OT_M2,
         O.NUMEOTTE NUMERO_OTT, O.ANNOOTTE ANNO_OTT,
         NVL(MPC.VALOR,'N') MATERIAL_PROPIEDAD_CLIENTE,
         FI.ANCHO, FI.LARGO, FI.MATBASE, FI.DESCRIPCION DESCRIPCION_MATBASE, SUBSTR(FI.MATBASE,1,2) LINEA, LIN.DESCRIPCION DESCRIPCION_LINEA,
-------------------------- 
--Vista 4
                --
                MAA.COSTE_BOBINAS_FX MAT_AUX_AGRU_FX,
--
                NVL(MAE.COSTE_TOTAL_CONTRA_INDUCTOR_FX,0)+NVL(MAEG.COSTE_TOTAL_CONTRA_INDUCTOR_FX,0) +
                NVL(DECODE(O.TIP_ARTI,P_Utilidad.F_ValoDeva('TIARFIF4'), DECODE(SUBSTR(O.COD_ARTI,3,1), P_Utilidad.F_ValoDeva('TIPOPROX'),NVL(MAEI.COSTE_TOTAL_CONTRA_INDUCTOR_FX,0)+NVL(MAEGI.COSTE_TOTAL_CONTRA_INDUCTOR_FX,0), 
                                                                                                        P_Utilidad.F_ValoDeva('TIPOPROZ'),NVL(MAEI.COSTE_TOTAL_CONTRA_INDUCTOR_FX,0)+NVL(MAEGI.COSTE_TOTAL_CONTRA_INDUCTOR_FX,0))),0) + 
                DECODE(NVL(OLQ.NUMERO_MATERIALES,0),0,0,NVL(MAELQ.COSTE_TOTAL_CONTRA_INDUCTOR_FX,0)+NVL(MAEGLQ.COSTE_TOTAL_CONTRA_INDUCTOR_FX,0)) + 
                DECODE(NVL(OLA.NUMERO_MATERIALES,0),0,0,NVL(MAELA.COSTE_TOTAL_CONTRA_INDUCTOR_FX,0)+NVL(MAEGLA.COSTE_TOTAL_CONTRA_INDUCTOR_FX,0))
                MAT_AUXILIARES_FX
--Fin Vista 4
         FROM FIC_CABEOTRE O, ARTICULO A, ANALESTA.ANE_CLIENTES CL, GNR_LINEAS LIN,
--Vista 4
              (SELECT L.EMPRESA, L.NUMERO, L.ANNO, COUNT(*) NUMERO_MATERIALES
               FROM FIC_LINEOTRE L
               WHERE (INSTR(L.COD_ARES,'LAQUEADORA') != 0) OR
                     (L.TIP_ARES = p_Utilidad.F_ValoDeva('TIARMPF4') AND 
                       EXISTS (SELECT 'X' FROM VALORES_LISTA MLT 
                         WHERE MLT.CODIGO = 'FIC_TERMMALA' 
                           AND MLT.VALOR = SUBSTR(L.COD_ARES,-1))) OR
                     (L.TIP_ARES = p_Utilidad.F_ValoDeva('TIARSEF4') AND 
                       EXISTS (SELECT 'X' FROM VALORES_LISTA MLT 
                         WHERE MLT.CODIGO = 'FIC_LINEMALA' 
                           AND MLT.VALOR = SUBSTR(L.COD_ARES,1,2)))
                GROUP BY L.EMPRESA, L.NUMERO, L.ANNO) OLQ,
              (SELECT L.EMPRESA, L.NUMERO, L.ANNO, COUNT(*) NUMERO_MATERIALES
               FROM FIC_LINEOTRE L
               WHERE (INSTR(L.COD_ARES,'LAMINADORA') != 0) OR
                     (L.TIP_ARES = p_Utilidad.F_ValoDeva('TIARSEF4') AND 
                       EXISTS (SELECT 'X' FROM VALORES_LISTA MLT 
                         WHERE MLT.CODIGO = 'FIC_LINEMALA' 
                           AND MLT.VALOR = SUBSTR(L.COD_ARES,1,2)))
                GROUP BY L.EMPRESA, L.NUMERO, L.ANNO) OLA,
--
              (SELECT ANNO, APLICA_A_EMPRESA_GRUPO, SUM(COSTE_TOTAL_CONTRA_INDUCTOR_FX) COSTE_TOTAL_CONTRA_INDUCTOR_FX FROM ANALESTA.ANE_AUXILIARES
               WHERE APLICA_A_TIPO_ESPECIALIDAD = 'APLICA A TODOS LAS ESPECIALIDADES'
               GROUP BY ANNO, APLICA_A_EMPRESA_GRUPO) MAE,
--
              (SELECT ANNO, SUM(COSTE_TOTAL_CONTRA_INDUCTOR_FX) COSTE_TOTAL_CONTRA_INDUCTOR_FX FROM ANALESTA.ANE_AUXILIARES
               WHERE APLICA_A_EMPRESA_GRUPO = 'GR'
                 AND APLICA_A_TIPO_ESPECIALIDAD = 'APLICA A TODOS LAS ESPECIALIDADES'
               GROUP BY ANNO) MAEG,
              --
              (SELECT ANNO, APLICA_A_EMPRESA_GRUPO, SUM(COSTE_TOTAL_CONTRA_INDUCTOR_FX) COSTE_TOTAL_CONTRA_INDUCTOR_FX FROM ANALESTA.ANE_AUXILIARES
               WHERE APLICA_A_TIPO_ESPECIALIDAD = 'APLICA A LAS ESPECIALIDADES IMPRESAS'
               GROUP BY ANNO, APLICA_A_EMPRESA_GRUPO) MAEI,
              (SELECT ANNO, SUM(COSTE_TOTAL_CONTRA_INDUCTOR_FX) COSTE_TOTAL_CONTRA_INDUCTOR_FX FROM ANALESTA.ANE_AUXILIARES
               WHERE APLICA_A_EMPRESA_GRUPO = 'GR'
                 AND APLICA_A_TIPO_ESPECIALIDAD = 'APLICA A LAS ESPECIALIDADES IMPRESAS'
               GROUP BY ANNO) MAEGI,
              (SELECT ANNO, APLICA_A_EMPRESA_GRUPO, SUM(COSTE_TOTAL_CONTRA_INDUCTOR_FX) COSTE_TOTAL_CONTRA_INDUCTOR_FX FROM ANALESTA.ANE_AUXILIARES
               WHERE APLICA_A_TIPO_ESPECIALIDAD = 'APLICA A LAS ESPECIALIDADES LAQUEADAS'
               GROUP BY ANNO, APLICA_A_EMPRESA_GRUPO) MAELQ,
              (SELECT ANNO, SUM(COSTE_TOTAL_CONTRA_INDUCTOR_FX) COSTE_TOTAL_CONTRA_INDUCTOR_FX FROM ANALESTA.ANE_AUXILIARES
               WHERE APLICA_A_EMPRESA_GRUPO = 'GR'
                 AND APLICA_A_TIPO_ESPECIALIDAD = 'APLICA A LAS ESPECIALIDADES LAQUEADAS'
               GROUP BY ANNO) MAEGLQ,
              (SELECT ANNO, APLICA_A_EMPRESA_GRUPO, SUM(COSTE_TOTAL_CONTRA_INDUCTOR_FX) COSTE_TOTAL_CONTRA_INDUCTOR_FX FROM ANALESTA.ANE_AUXILIARES
               WHERE APLICA_A_TIPO_ESPECIALIDAD = 'APLICA A LAS ESPECIALIDADES LAMINADAS'
               GROUP BY ANNO, APLICA_A_EMPRESA_GRUPO) MAELA,
              (SELECT ANNO, SUM(COSTE_TOTAL_CONTRA_INDUCTOR_FX) COSTE_TOTAL_CONTRA_INDUCTOR_FX FROM ANALESTA.ANE_AUXILIARES
               WHERE APLICA_A_EMPRESA_GRUPO = 'GR'
                 AND APLICA_A_TIPO_ESPECIALIDAD = 'APLICA A LAS ESPECIALIDADES LAMINADAS'
               GROUP BY ANNO) MAEGLA,
--
              (SELECT EMPRESA, NUMERO_OT, SUM(COSTE_BOBINAS_FX) COSTE_BOBINAS_FX 
               FROM ANALESTA.ANE_FORMULAS_AUX_ACUMULADOS_OT 
               GROUP BY EMPRESA, NUMERO_OT) MAA,--Materiales auxiliares agrupados
--Fin Vista 4           
              (
               SELECT F.EMPRESA, F.TIP_ARTI, F.PRODUCTO, F.MODI, F.REVI, F.ANCHO, F.LARGO, F.MATBASE, L.FCKG, L.DESCRIPCION FROM HFICTEC F, LFS L
               WHERE F.EMPRESA = L.EMPRESA
                 AND F.MATBASE = L.COD_LFS
               UNION
               SELECT F.EMPRESA, F.TIP_ARTI, F.PRODUCTO, F.MODI, F.REVI, F.ANCHO, F.LARGO, F.MATBASE, L.FCKG, L.DESCRIPCION FROM FIC_SEGESTI F, LFS L
               WHERE F.EMPRESA = L.EMPRESA
                 AND F.MATBASE = L.COD_LFS
              ) FI,
              (SELECT CP.EMPRESA, CP.NUMEPEDI, NULL REFEENPM, CP.DIREENVI, DE.PAIS, DE.NOMBRE
               FROM FIC_CABEPEDI CP, 
                    (SELECT DE.EMPRESA, DE.CLIENTE_ID, DE.LINEA, DE.PAIS, PA.NOMBRE FROM GNR_CLDIRENV DE, GNR_PAISES PA
                     WHERE DE.PAIS = PA.PAIS(+)) DE
               WHERE CP.EMPRESA = DE.EMPRESA(+)
                 AND CP.CLIENTE_ID = DE.CLIENTE_ID(+)
                 AND CP.DIREENVI = DE.LINEA(+)
               UNION
               SELECT CP.EMPRESA, CP.NUMEPEDI, NULL REFEENPM, CP.DIREENVI, DE.PAIS, DE.NOMBRE
               FROM FIC_HICAPEVE CP, 
                    (SELECT DE.EMPRESA, DE.CLIENTE_ID, DE.LINEA, DE.PAIS, PA.NOMBRE FROM GNR_CLDIRENV DE, GNR_PAISES PA
                     WHERE DE.PAIS = PA.PAIS(+)) DE
               WHERE CP.EMPRESA = DE.EMPRESA(+)
                 AND CP.CLIENTE_ID = DE.CLIENTE_ID(+)
                 AND CP.DIREENVI = DE.LINEA(+)
               UNION
               SELECT CP.EMPRESA, CP.NUMEPEDI, CP.REFEENPM, NULL DIREENVI, NULL PAIS, NULL NOMBRE FROM FIC_CABEPEMA CP) P,
              (SELECT EMPRESA, NUMERO, ANNO, VALOR FROM FIC_LICHOBOT
               WHERE CODIGO = P_Utilidad.F_ValoDeva('COOTPEPC')) MPC,
              (SELECT EMPRESA, NUMEPEDI, LINEPEDI, TIPOPEDI FROM FIC_LINEPEDI
               UNION 
               SELECT EMPRESA, NUMEPEDI, LINEPEDI, TIPOPEDI FROM FIC_HILIPEVE
               UNION
               SELECT EMPRESA, NUMEPEDI, LINEPEDI, TIPOPEDI FROM FIC_LINEPEMA) LP
         WHERE O.EMPRESA = A.EMPRESA
           AND O.TIP_ARTI = A.TIP_ARTI
           AND O.COD_ARTI = A.COD_ARTI
           AND O.EMPRESA = P.EMPRESA(+)
           AND O.NUMEPEDI = P.NUMEPEDI(+)
           AND O.EMPRESA = MPC.EMPRESA(+)
           AND O.NUMERO = MPC.NUMERO(+)
           AND O.ANNO = MPC.ANNO(+)
           AND O.EMPRESA = LP.EMPRESA(+)
           AND O.NUMEPEDI = LP.NUMEPEDI(+)
           AND O.LINEPEDI = LP.LINEPEDI(+)
           AND A.EMPRESA = CL.EMPRESA(+)
           AND A.CLIENASOC = CL.CLIENTE_ID(+)
           AND O.EMPRESA = FI.EMPRESA(+)
           AND O.TIP_ARTI = FI.TIP_ARTI(+)
           AND O.COD_ARTI = FI.PRODUCTO(+)
           AND NVL(O.MODI,0) = NVL(FI.MODI(+),0)
           AND NVL(O.REVI,0) = NVL(FI.REVI(+),0)
           AND SUBSTR(FI.MATBASE,1,2) = LIN.LINEA
--Vista 4
           AND O.EMPRESA = MAA.EMPRESA(+)
           AND O.NUMERO = MAA.NUMERO_OT(+)
--
           AND O.EMPRESA = MAE.APLICA_A_EMPRESA_GRUPO(+)
           AND TO_CHAR(O.FEC_MODI,'YYYY') = MAE.ANNO(+)
--
           AND TO_CHAR(O.FEC_MODI,'YYYY') = MAEG.ANNO(+)
           --
           AND O.EMPRESA = MAEI.APLICA_A_EMPRESA_GRUPO(+)
           AND TO_CHAR(O.FEC_MODI,'YYYY') = MAEI.ANNO(+)
           AND TO_CHAR(O.FEC_MODI,'YYYY') = MAEGI.ANNO(+)
           --
           AND O.EMPRESA = MAELQ.APLICA_A_EMPRESA_GRUPO(+)
           AND TO_CHAR(O.FEC_MODI,'YYYY') = MAELQ.ANNO(+)
           AND TO_CHAR(O.FEC_MODI,'YYYY') = MAEGLQ.ANNO(+)
           --
           AND O.EMPRESA = MAELA.APLICA_A_EMPRESA_GRUPO(+)
           AND TO_CHAR(O.FEC_MODI,'YYYY') = MAELA.ANNO(+)
           AND TO_CHAR(O.FEC_MODI,'YYYY') = MAEGLA.ANNO(+)
--
           --
           AND O.EMPRESA = OLQ.EMPRESA(+)
           AND O.NUMERO = OLQ.NUMERO(+)
           AND O.ANNO = OLQ.ANNO(+)
           AND O.EMPRESA = OLA.EMPRESA(+)
           AND O.NUMERO = OLA.NUMERO(+)
           AND O.ANNO = OLA.ANNO(+);
--Fin Vista 4
