CREATE OR REPLACE VIEW ANALESTA.ANE_INDUCTOR_REPARTO_ANNO_MES AS
SELECT V.ANNO, V.MES, V.INDUREPA INDUCTOR, I.INDUREPA DESCRIPCION_INDUCTOR, V.TOTAL, 
       V.EMPRESA1, V.VALOR1, V.EMPRESA2, V.VALOR2, V.EMPRESA3, V.VALOR3 
FROM ANE_VAINRECO V, GNR_INRECOCO I
WHERE V.INDUREPA = I.CODIGO
  AND V.TIPO = 'R';