  CREATE OR REPLACE VIEW "ANALESTA"."ANE_ORDENES_DE_TRABAJO_P5" AS 
  SELECT O.EMPRESA, O.NUMERO NUMERO_OT, O.ANNO ANNO_OT, O.SITUACIO, O.FEC_MODI FECHA_MODIFICACION_OT, TO_CHAR(O.FEC_MODI,'YYYY') ANNO_MODIFICACION_OT, TO_CHAR(O.FEC_MODI,'MM') MES_MODIFICACION_OT,
         CL.CLIENTE_ID, CL.RAZON_SOC, CL.VENDEDOR, CL.TIPO_VENDEDOR, CL.DESCRIPCION_VENEDEDOR, CL.VENCIMIENTO_FX,
         O.TIP_ARTI TIP_ARTI_OT, O.COD_ARTI COD_ARTI_OT, A.DESCRIPCION DESCRIPCION_ARTICULO_OT, O.MODI MODIFICACION, O.REVI REVISION, DECODE(O.TIP_ARTI,P_Utilidad.F_ValoDeva('TIARFIF4'), DECODE(SUBSTR(O.COD_ARTI,3,1), P_Utilidad.F_ValoDeva('TIPOPROY'), 'ANONIMO', 'IMPRESO')) TIPO_ARTICULO,
         P_GNR_AGRUESTR.F_ASIGNA_AGRUESTR(O.EMPRESA, SUBSTR(O.COD_ARTI,4,4),O.TIP_ARTI, O.COD_ARTI) AGRUPACION_ESTRATEGICA,
         O.NUMEPEDI PEDIDO_OT, O.LINEPEDI LINEA_PEDIDO_OT, NVL(LP.TIPOPEDI,'NE') TIPO_DE_PEDIDO, P.REFEENPM REFERENCIA_PEDIDO_MATRIZ_OT, 
         P.DIREENVI CODIGO_DIRECCION_ENVIO, P.PAIS CODIGO_PAIS_DIREC_ENVIO_PEDIDO, P.NOMBRE PAIS_DIREC_ENVIO_PEDIDO, CL.PAIS CODIGO_PAIS_CLIENTE, CL.DESCRIPCION_PAIS PAIS_CLIENTE, 
         DECODE(P.PAIS, NULL,CL.PAIS,P.PAIS) CODIGO_PAIS_ENTREGA, DECODE(P.NOMBRE, NULL,CL.DESCRIPCION_PAIS,P.NOMBRE) PAIS_ENTREGA, DECODE(DECODE(P.PAIS, NULL,CL.PAIS,P.PAIS),NULL,'N',P_Utilidad.F_ValoDeva('PAISESPA'),'N','E') TIPO_PEDIDO,
         O.CANTCERR CANTIDAD_CERRADA_OT, O.UNIDAD UNIDAD_CERRADA_OT, 
         DECODE(O.UNIDAD,P_Utilidad.F_ValoDeva('TIPOUNML'),1,DECODE(NVL(FI.ANCHO,0),0,0,DECODE(O.UNIDAD,P_Utilidad.F_ValoDeva('TIPOUNKG'),FI.FCKG * (1000 / FI.ANCHO),
                                                                                                         P_Utilidad.F_ValoDeva('TIPOUNM2'),(1000 / FI.ANCHO),
                                                                                                         P_Utilidad.F_ValoDeva('TIPOUNUN'),(1000 / FI.ANCHO) * ((FI.ANCHO * FI.LARGO) / 1000000)))) FACTOR_ML_CIERRE_OT_FX, 
         O.CANTCERR * 
         DECODE(O.UNIDAD,P_Utilidad.F_ValoDeva('TIPOUNML'),1,DECODE(NVL(FI.ANCHO,0),0,0,DECODE(O.UNIDAD,P_Utilidad.F_ValoDeva('TIPOUNKG'),FI.FCKG * (1000 / FI.ANCHO),
                                                                                                         P_Utilidad.F_ValoDeva('TIPOUNM2'),(1000 / FI.ANCHO),
                                                                                                         P_Utilidad.F_ValoDeva('TIPOUNUN'),(1000 / FI.ANCHO) * ((FI.ANCHO * FI.LARGO) / 1000000))))
         CANTIDAD_CERRADA_OT_ML,
         DECODE(O.UNIDAD,P_Utilidad.F_ValoDeva('TIPOUNM2'),1,P_Utilidad.F_ValoDeva('TIPOUNKG'),FI.FCKG,
                                                               P_Utilidad.F_ValoDeva('TIPOUNML'),(FI.ANCHO / 1000),
                                                               P_Utilidad.F_ValoDeva('TIPOUNUN'),(FI.ANCHO * FI.LARGO) / 1000000) FACTOR_M2_CIERRE_OT_FX,
         O.CANTCERR *
         DECODE(O.UNIDAD,P_Utilidad.F_ValoDeva('TIPOUNM2'),1,P_Utilidad.F_ValoDeva('TIPOUNKG'),FI.FCKG,
                                                               P_Utilidad.F_ValoDeva('TIPOUNML'),(FI.ANCHO / 1000),
                                                               P_Utilidad.F_ValoDeva('TIPOUNUN'),(FI.ANCHO * FI.LARGO) / 1000000)
         CANTIDAD_CERRADA_OT_M2,
         O.NUMEOTTE NUMERO_OTT, O.ANNOOTTE ANNO_OTT,
         NVL(MPC.VALOR,'N') MATERIAL_PROPIEDAD_CLIENTE,
         FI.ANCHO, FI.LARGO, FI.MATBASE, FI.DESCRIPCION DESCRIPCION_MATBASE, SUBSTR(FI.MATBASE,1,2) LINEA, LIN.DESCRIPCION DESCRIPCION_LINEA,
-------------------------- 
--Vista 5
         CHP.COSTE_HORA_PREIMPRESION_FX,
         DECODE(NVL(LP.TIPOPEDI,'NE'),'N',TEC.TECNOLOGIA,'M',TEC.TECNOLOGIA) TECNOLOGIA_APLICA_PED_N_M_FX,
         ANALESTA.P_ANE_MERMLAMI_PRAG.F_NumeGrre(O.EMPRESA, O.NUMERO, O.ANNO, DECODE(NVL(LP.TIPOPEDI,'NE'),'N',TEC.TECNOLOGIA,'M',TEC.TECNOLOGIA)) NUMERO_GRABADOS_OT,
         ANALESTA.P_ANE_MERMLAMI_PRAG.F_IngrGrab(O.EMPRESA, O.NUMERO, O.ANNO) INGRESOS_GRABADOS_OT,
         ANALESTA.P_ANE_MERMLAMI_PRAG.F_CocoExpn(O.EMPRESA, O.NUMERO, O.ANNO, DECODE(NVL(LP.TIPOPEDI,'NE'),'N',TEC.TECNOLOGIA,'M',TEC.TECNOLOGIA)) PEDIDOS_COMPRA_PREIM_ASOCIA_OT,
         ANALESTA.P_ANE_MERMLAMI_PRAG.F_HoraPrei(O.EMPRESA, O.NUMERO, O.ANNO, DECODE(NVL(LP.TIPOPEDI,'NE'),'N',TEC.TECNOLOGIA,'M',TEC.TECNOLOGIA)) MINUTOS_PREIM_ASOCIA_OT,
         (ANALESTA.P_ANE_MERMLAMI_PRAG.F_HoraPrei(O.EMPRESA, O.NUMERO, O.ANNO, DECODE(NVL(LP.TIPOPEDI,'NE'),'N',TEC.TECNOLOGIA,'M',TEC.TECNOLOGIA))/60) * CHP.COSTE_HORA_PREIMPRESION_FX COSTE_TIEMPO_PREIMP_ASOCIA_OT,
         P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_HoOEPrei(O.EMPRESA, O.NUMERO, O.ANNO, DECODE(NVL(LP.TIPOPEDI,'NE'),'N',TEC.TECNOLOGIA,'M',TEC.TECNOLOGIA)),'EMPRESA1') EMP1_PREIM_OTRA_EMPR_ASOCIA_OT,
         P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_HoOEPrei(O.EMPRESA, O.NUMERO, O.ANNO, DECODE(NVL(LP.TIPOPEDI,'NE'),'N',TEC.TECNOLOGIA,'M',TEC.TECNOLOGIA)),'MINUTOS1') MIN1_PREIM_OTRA_EMPR_ASOCIA_OT,
         (P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_HoOEPrei(O.EMPRESA, O.NUMERO, O.ANNO, DECODE(NVL(LP.TIPOPEDI,'NE'),'N',TEC.TECNOLOGIA,'M',TEC.TECNOLOGIA)),'MINUTOS1') /60) * CHP.COSTE_HORA_PREIMPRESION_FX COSTE_EM1_TIE_PREIMP_ASOCIA_OT,
         P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_HoOEPrei(O.EMPRESA, O.NUMERO, O.ANNO, DECODE(NVL(LP.TIPOPEDI,'NE'),'N',TEC.TECNOLOGIA,'M',TEC.TECNOLOGIA)),'EMPRESA2') EMP2_PREIM_OTRA_EMPR_ASOCIA_OT,
         P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_HoOEPrei(O.EMPRESA, O.NUMERO, O.ANNO, DECODE(NVL(LP.TIPOPEDI,'NE'),'N',TEC.TECNOLOGIA,'M',TEC.TECNOLOGIA)),'MINUTOS2') MIN2_PREIM_OTRA_EMPR_ASOCIA_OT,
         (P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_HoOEPrei(O.EMPRESA, O.NUMERO, O.ANNO, DECODE(NVL(LP.TIPOPEDI,'NE'),'N',TEC.TECNOLOGIA,'M',TEC.TECNOLOGIA)),'MINUTOS2') /60) * CHP.COSTE_HORA_PREIMPRESION_FX COSTE_EM2_TIE_PREIMP_ASOCIA_OT,
         P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_HoOEPrei(O.EMPRESA, O.NUMERO, O.ANNO, DECODE(NVL(LP.TIPOPEDI,'NE'),'N',TEC.TECNOLOGIA,'M',TEC.TECNOLOGIA)),'EMPRESA3') EMP3_PREIM_OTRA_EMPR_ASOCIA_OT,
         P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_HoOEPrei(O.EMPRESA, O.NUMERO, O.ANNO, DECODE(NVL(LP.TIPOPEDI,'NE'),'N',TEC.TECNOLOGIA,'M',TEC.TECNOLOGIA)),'MINUTOS3') MIN3_PREIM_OTRA_EMPR_ASOCIA_OT,
         (P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_HoOEPrei(O.EMPRESA, O.NUMERO, O.ANNO, DECODE(NVL(LP.TIPOPEDI,'NE'),'N',TEC.TECNOLOGIA,'M',TEC.TECNOLOGIA)),'MINUTOS3') /60) * CHP.COSTE_HORA_PREIMPRESION_FX COSTE_EM3_TIE_PREIMP_ASOCIA_OT
--Fin Vista 5
         FROM FIC_CABEOTRE O, ARTICULO A, ANALESTA.ANE_CLIENTES CL, GNR_LINEAS LIN,
--Vista n
              ANALESTA.ANE_ANAL_COSTE_HORA_PREIMPRESI CHP,
              (SELECT O.EMPRESA, O.NUMERO, O.ANNO, DECODE(TEC.TIPO_IMPRE, 'FLEXO', DECODE(TEC.FILMAR,'S','FLEXO/ANALOGICO','FLEXO/DIGITAL'),'HUECO') TECNOLOGIA
                FROM FIC_CABEOTRE O, HFICTEC HFT, 
                (SELECT LSC.EMPRESA, LSC.NUMETRAB, LSC.TIPO_IMPRE, LSC.FILMAR FROM PRI_LISELCOL LSC
                 WHERE (LSC.EMPRESA, LSC.NUMETRAB, LSC.CONTADOR||LSC.POSICION) IN 
                      (SELECT LSCM.EMPRESA, LSCM.NUMETRAB, MAX(LSCM.CONTADOR||LSCM.POSICION) FROM PRI_LISELCOL LSCM
                       WHERE LSCM.EMPRESA = LSC.EMPRESA 
                         AND LSCM.NUMETRAB = LSC.NUMETRAB
                       GROUP BY LSCM.EMPRESA, LSCM.NUMETRAB)) TEC 
                WHERE O.EMPRESA = HFT.EMPRESA
                  AND O.TIP_ARTI = HFT.TIP_ARTI
                  AND O.COD_ARTI = HFT.PRODUCTO
                  AND O.MODI = HFT.MODI
                  AND O.REVI = HFT.REVI
                  AND HFT.EMPRESA = TEC.EMPRESA
                  AND HFT.NUMETRAB = TEC.NUMETRAB
                  AND HFT.NUMEPEDI IS NOT NULL 
                  AND HFT.REVI = 0
                  --AND vCP_PEDINUMO IN ('N','M')
              ) TEC,
--Fin Vista n          
              (
               SELECT F.EMPRESA, F.TIP_ARTI, F.PRODUCTO, F.MODI, F.REVI, F.ANCHO, F.LARGO, F.MATBASE, L.FCKG, L.DESCRIPCION FROM HFICTEC F, LFS L
               WHERE F.EMPRESA = L.EMPRESA
                 AND F.MATBASE = L.COD_LFS
               UNION
               SELECT F.EMPRESA, F.TIP_ARTI, F.PRODUCTO, F.MODI, F.REVI, F.ANCHO, F.LARGO, F.MATBASE, L.FCKG, L.DESCRIPCION FROM FIC_SEGESTI F, LFS L
               WHERE F.EMPRESA = L.EMPRESA
                 AND F.MATBASE = L.COD_LFS
              ) FI,
              (SELECT CP.EMPRESA, CP.NUMEPEDI, NULL REFEENPM, CP.DIREENVI, DE.PAIS, DE.NOMBRE
               FROM FIC_CABEPEDI CP, 
                    (SELECT DE.EMPRESA, DE.CLIENTE_ID, DE.LINEA, DE.PAIS, PA.NOMBRE FROM GNR_CLDIRENV DE, GNR_PAISES PA
                     WHERE DE.PAIS = PA.PAIS(+)) DE
               WHERE CP.EMPRESA = DE.EMPRESA(+)
                 AND CP.CLIENTE_ID = DE.CLIENTE_ID(+)
                 AND CP.DIREENVI = DE.LINEA(+)
               UNION
               SELECT CP.EMPRESA, CP.NUMEPEDI, NULL REFEENPM, CP.DIREENVI, DE.PAIS, DE.NOMBRE
               FROM FIC_HICAPEVE CP, 
                    (SELECT DE.EMPRESA, DE.CLIENTE_ID, DE.LINEA, DE.PAIS, PA.NOMBRE FROM GNR_CLDIRENV DE, GNR_PAISES PA
                     WHERE DE.PAIS = PA.PAIS(+)) DE
               WHERE CP.EMPRESA = DE.EMPRESA(+)
                 AND CP.CLIENTE_ID = DE.CLIENTE_ID(+)
                 AND CP.DIREENVI = DE.LINEA(+)
               UNION
               SELECT CP.EMPRESA, CP.NUMEPEDI, CP.REFEENPM, NULL DIREENVI, NULL PAIS, NULL NOMBRE FROM FIC_CABEPEMA CP) P,
              (SELECT EMPRESA, NUMERO, ANNO, VALOR FROM FIC_LICHOBOT
               WHERE CODIGO = P_Utilidad.F_ValoDeva('COOTPEPC')) MPC,
              (SELECT EMPRESA, NUMEPEDI, LINEPEDI, TIPOPEDI FROM FIC_LINEPEDI
               UNION 
               SELECT EMPRESA, NUMEPEDI, LINEPEDI, TIPOPEDI FROM FIC_HILIPEVE
               UNION
               SELECT EMPRESA, NUMEPEDI, LINEPEDI, TIPOPEDI FROM FIC_LINEPEMA) LP
         WHERE O.EMPRESA = A.EMPRESA
           AND O.TIP_ARTI = A.TIP_ARTI
           AND O.COD_ARTI = A.COD_ARTI
           AND O.EMPRESA = P.EMPRESA(+)
           AND O.NUMEPEDI = P.NUMEPEDI(+)
           AND O.EMPRESA = MPC.EMPRESA(+)
           AND O.NUMERO = MPC.NUMERO(+)
           AND O.ANNO = MPC.ANNO(+)
           AND O.EMPRESA = LP.EMPRESA(+)
           AND O.NUMEPEDI = LP.NUMEPEDI(+)
           AND O.LINEPEDI = LP.LINEPEDI(+)
           AND A.EMPRESA = CL.EMPRESA(+)
           AND A.CLIENASOC = CL.CLIENTE_ID(+)
           AND O.EMPRESA = FI.EMPRESA(+)
           AND O.TIP_ARTI = FI.TIP_ARTI(+)
           AND O.COD_ARTI = FI.PRODUCTO(+)
           AND NVL(O.MODI,0) = NVL(FI.MODI(+),0)
           AND NVL(O.REVI,0) = NVL(FI.REVI(+),0)
           AND SUBSTR(FI.MATBASE,1,2) = LIN.LINEA
--Vista n
           AND TO_CHAR(O.FEC_MODI,'YYYY') = CHP.ANNO(+)
           --
           AND O.EMPRESA = TEC.EMPRESA(+)
           AND O.NUMERO = TEC.NUMERO(+)
           AND O.ANNO = TEC.ANNO(+);
--Fin Vista n
