SELECT * FROM ANALESTA.ANE_M_PRO_REAL_C WHERE EMPRESA = '05' AND OT = '2015000686' ORDER BY FASE_MP;
SELECT * FROM ANALESTA.ANE_M_PRO WHERE EMPRESA = '05' AND OT = '2015000686' ORDER BY FASE_MP;

SELECT * FROM ANALESTA.ANE_M_PRO_REAL_C WHERE ML_PRODUCIDOS_REALES = 0;

SELECT * FROM ANALESTA.ANE_M_PRO_REAL_C WHERE TIPO_MP = 'RE' AND ML_PRODUCIDOS_REALES = 0;

SELECT * FROM ANALESTA.ANE_M_PRO_MATERIAL WHERE EMPRESA = '05' AND OT = 2016000507 AND LFS_MP = '70TN025';

SELECT * FROM ANALESTA.ANE_M_PRO_REAL_CONTADOR WHERE EMPRESA = '05' AND OT = 2016000507 AND LFS_MP = '70TN025';

		   SELECT DECODE(SUM(NVL(M2_CONSUMIDOS,0)),0,0,SUM(NVL(EUROS_ML_CONSUMIDOS,0)) / SUM(M2_CONSUMIDOS)) PRECIO
			FROM ANALESTA.ANE_M_PRO_REAL 
			WHERE EMPRESA = '05' 
			  AND OT = 2016000507
			  AND FASE_MP = 3
			  AND TIPO_MP = 'M'
			  --AND COD_MP = '70TN02505357';
			  AND LFS_MP = '70TN025';

SELECT * FROM ANALESTA.ANE_M_PRO_MATERIAL WHERE TIPO_MP = 'RE' AND ML_PRODUCIDOS_REALES = 0;

CREATE OR REPLACE VIEW ANALESTA.ANE_M_PRO_MATERIAL AS
SELECT M.EMPRESA, 
       --1
		 M.N_CLIENTE,
       M.CLIENTE,
		 --
       M.OT, 
		 --2
		 M.FECHA_DE_LA_OT,
		 M.FECHA_CIERRE_DE_LA_OT,
		 M.FECHA_FACTURA,
		 M.TIPO_PRD,
		 M.ESPECIALIDAD,
		 M.LINEA,
		 M.LFS,
		 --
		 M.N_CAPAS_TOTALES,
		 M.CANTIDAD_DE_FASES,
		 M.ANCHO_CLIENTE,
		 M.N_DE_CORTES,
		 M.N_DE_VECES,
		 M.ANCHO_DE_PRODUCCION,
		 --
		 M.TIPO_MP_M TIPO_MP,
		 --
		 DECODE(M.TIPO_MP,P_UTILIDAD.F_VALODEVA('TIARREST'),'RESTO',M.LFS_MP_M) LFS_MP,
		 --
		 PRECIO,--DECODE(NVL(SUM(M2_CONSUMIDOS_M),0),0,NULL,SUM(EUROS_ML_CONSUMIDOS_M) / SUM(M2_CONSUMIDOS_M)) PRECIO_MEDIO_MP_LFS_M2,
		 --
		 M.FASE_MP,
		 M.SECCION_PRODUCTIVA_MP SECCION_PRODUCTIVA,
		 M.MAQUINA_MP MAQUINA,
		 M.UNIDAD_CIERRE,
		 M.Q_CERRADA_ML,
		 M.Q_CERRADA_M2,
		 M.Q_CERRADA_KG,
		 M.Q_CERRADA_UN,
		 M.FUENTE_DEL_CIERRE,
		 M.ML_CONSUMIDOS, M.ML_PRODUCIDOS,
		 M.ML_CONSUMIDOS_REALES, M.ML_PRODUCIDOS_REALES,
		 M.ML_MERMA_TOTAL TOTAL_MERMA_ML,
		 M.ML_MERMAS_ACUMULADAS_EN_MAQ,
		 M.ML_ENHEBRADO_MAQUINA,
		 M.ML_AJ_MAQUINA_MAQUINA,
		 M.ML_CAMBIO_BOBINA_MAQUINA,
		 M.ML_MERMA_TIRADA_MQUINA,
		 M.ML_SANEAMIENTOS_MAQUINA,
		 M.ML_MERMA_PROCESO_MQUINA,
		 M.M2_CONSUMIDOS, M.M2_PRODUCIDOS,
		 M.M2_CONSUMIDOS_REALES, M.M2_PRODUCIDOS_REALES,
		 M.M2_MERMA_TOTAL TOTAL_MERMA_M2,
		 M.M2_MERMAS_ACUMULADAS_EN_MAQ,
		 M.M2_ENHEBRADO_MAQUINA,
		 M.M2_AJ_MAQUINA_MAQUINA,
		 M.M2_CAMBIO_BOBINA_MAQUINA,
		 M.M2_MERMA_TIRADA_MQUINA,
		 M.M2_SANEAMIENTOS_MAQUINA,
		 M.M2_MERMA_PROCESO_MQUINA,
		 M.EUROS_ML_CONSUMIDOS_REALES,
		 M.EUROS_ML_PRODUCIDOS_REALES,
		 M.EUROS_ML_ENHEBRADO,
		 M.EUROS_ML_AJ_MAQUINA,
		 M.EUROS_ML_CAMBIO_BOBINA,
		 M.EUROS_ML_MERMA_TIRADA,
		 M.EUROS_ML_SANEAMIENTOS,
		 M.EUROS_ML_MERMA_PROCESO,
		 M.EUROS_MERMA_TOTAL_MAQUINA
FROM ANALESTA.ANE_M_PRO_REAL_CONTADOR M
--WHERE EMPRESA = '05' AND OT = '2016000205'
/*GROUP BY M.EMPRESA, 
       --1
		 M.N_CLIENTE,
       M.CLIENTE,
		 --
       M.OT, 
		 --2
		 M.FECHA_DE_LA_OT,
		 M.FECHA_CIERRE_DE_LA_OT,
		 M.FECHA_FACTURA,
		 M.TIPO_PRD,
		 M.ESPECIALIDAD,
		 M.LINEA,
		 M.LFS,
		 --
		 M.N_CAPAS_TOTALES,
		 M.CANTIDAD_DE_FASES,
		 M.ANCHO_CLIENTE,
		 M.N_DE_CORTES,
		 M.N_DE_VECES,
		 M.ANCHO_DE_PRODUCCION,
		 --
		 M.TIPO_MP_M,
		 --
		 M.LFS_MP_M,
		 --
		 M.FASE_MP,
		 M.SECCION_PRODUCTIVA_MP,
		 M.MAQUINA_MP,
		 M.UNIDAD_CIERRE,
		 M.Q_CERRADA_ML,
		 M.Q_CERRADA_M2,
		 M.Q_CERRADA_KG,
		 M.Q_CERRADA_UN,
		 M.FUENTE_DEL_CIERRE,
		 M.ML_CONSUMIDOS, M.ML_PRODUCIDOS,
		 M.ML_CONSUMIDOS_REALES, M.ML_PRODUCIDOS_REALES,
		 M.ML_MERMA_TOTAL,
		 M.ML_ENHEBRADO_MAQUINA,
		 M.ML_AJ_MAQUINA_MAQUINA,
		 M.ML_CAMBIO_BOBINA_MAQUINA,
		 M.ML_MERMA_TIRADA_MQUINA,
		 M.ML_SANEAMIENTOS_MAQUINA,
		 M.ML_MERMA_PROCESO_MQUINA,
		 M.M2_CONSUMIDOS, M.M2_PRODUCIDOS,
		 M.M2_CONSUMIDOS_REALES, M.M2_PRODUCIDOS_REALES,
		 M.M2_MERMA_TOTAL,
		 M.M2_ENHEBRADO_MAQUINA,
		 M.M2_AJ_MAQUINA_MAQUINA,
		 M.M2_CAMBIO_BOBINA_MAQUINA,
		 M.M2_MERMA_TIRADA_MQUINA,
		 M.M2_SANEAMIENTOS_MAQUINA,
		 M.M2_MERMA_PROCESO_MQUINA,
		 M.EUROS_ML_CONSUMIDOS_REALES,
		 M.EUROS_ML_PRODUCIDOS_REALES,
		 M.EUROS_ML_ENHEBRADO,
		 M.EUROS_ML_AJ_MAQUINA,
		 M.EUROS_ML_CAMBIO_BOBINA,
		 M.EUROS_ML_MERMA_TIRADA,
		 M.EUROS_ML_SANEAMIENTOS,
		 M.EUROS_ML_MERMA_PROCESO,
		 M.EUROS_MERMA_TOTAL_MAQUINA
ORDER BY M.FASE_MP*/;

--CREATE OR REPLACE VIEW ANALESTA.ANE_M_PRO_MATERIAL AS
SELECT M.EMPRESA, 
       --1
		 M.N_CLIENTE,
       M.CLIENTE,
		 --
       M.NUMEOTRE, 
		 --2
		 M.FECHA_DE_LA_OT,
		 M.FECHA_CIERRE_DE_LA_OT,
		 M.FECHA_FACTURA,
		 M.TIPO_PRD,
		 M.ESPECIALIDAD,
		 M.LINEA,
		 M.LFS,
		 --
		 M.TIPO_MP,
		 M.COD_LFS LFS_MP,
		 DECODE(NVL(SUM(M.CANTCORE * (M.ANCHO_MP/1000)),0),0,0,(SUM(M.CANTCORE * (M.ANCHO_MP/1000) * DECODE(NVL((M.PRECIO_ML * (1000/M.ANCHO_MP)),0),0,--Prevalece el precio de costes
																	 DECODE(NVL(M.PRECIO_COMPRA_CALCULADO,0),0,M.F_PRECIO,PRECIO_COMPRA_CALCULADO),M.PRECIO_ML * (1000/M.ANCHO_MP))))/SUM(M.CANTCORE * (M.ANCHO_MP/1000))) PRECIO_MEDIO_MP_LFS_M2, 
		 M.CONTADOR FASE_MP, 
		 DECODE(INSTR(M.MAQUCODI,'CORTADORA'),1,'Sección Cortadoras',DECODE(INSTR(M.MAQUCODI,'IMPRESORA'),1,'Sección Impresoras',DECODE(INSTR(M.MAQUCODI,'LAMINADORA'),1,'Sección Laminadoras',DECODE(INSTR(M.MAQUCODI,'LAQUEADORA'),1,'Sección Laqueadoras')))) SECCION_PRODUCTIVA,
		 M.MAQUCODI MAQUINA,	
		 UNIDAD_CIERRE, CANTIDAD_ML Q_CERRADA_ML, CANTIDAD_M2 Q_CERRADA_M2, CANTIDAD_KG Q_CERRADA_KG, CANTIDAD_UN Q_CERRADA_UN, FUENTE_DEL_CIERRE,
		 --
		 --SUM(M.M2_MERMPLAN) M2_MERMPLAN, 
		 --SUM(M.M2_MERMPLAN_EXESO) M2_MERMPLAN_EXESO,
		 --
		 --SUM(M.M2_MERMPLAN) + SUM(M.M2_MERMPLAN_EXESO) TOTAL_M2_MERMPLAN,
		 --
		 --SUM(EUR_MERMPLAN) EUR_MERMPLAN,
		 --SUM(EUR_MERMPLAN_EXESO) EUR_MERMPLAN_EXESO,
		 --
		 --SUM(EUR_MERMPLAN) + SUM(EUR_MERMPLAN_EXESO) TOTAL_EUROS_MERMPLAN,
		 --
		 SUM(M.CANTCONS) ML_CONSUMIDOS_FASE, SUM(M.CANTPROD) ML_PRODUCIDOS_FASE,
       SUM(M.CANTCORE) ML_CONSUMIDOS_REALES_FASE, SUM(M.CANTPRRE) ML_PRODUCIDOS_REALES_FASE,
		 SUM(M.CANTCORE) - SUM(M.CANTPRRE) ML_TOTAL_MERMA_FASE
--SUM(M.CANTCORE * (M.ANCHO_MP/1000)) M2_CONSUMIDOS_REALES_REALES_FASE, SUM(M.CANTPRRE * (M.ANCHO_MP/1000)) M2_PRODUCIDOS_REALES_REALES_FASE,
--SUM(M.CANTCORE * (M.ANCHO_MP/1000) * DECODE(NVL((M.PRECIO_ML * (1000/M.ANCHO_MP)),0),0,--Prevalece el precio de costes
--		                                        DECODE(NVL(M.PRECIO_COMPRA_CALCULADO,0),0,M.F_PRECIO,PRECIO_COMPRA_CALCULADO),M.PRECIO_ML * (1000/M.ANCHO_MP))) EUROS_ML_CONSUMIDOS
FROM (

SELECT 
A.COD_LFS, 
M.PRECIO_ML_M PRECIO_ML,
(
SELECT DECODE(C.ALUNST,P_Utilidad.F_ValoDeva('TIPOUNM2'),DECODE(C.ALUPRE,0,DECODE(C.ALCANT, 0, 0,((C.ALPREU * D.CAMBIO) * C.ALCAEQ) / C.ALCANT),
																			DECODE(C.ALCANT, 0, 0,(((C.ALPREU * D.CAMBIO) * C.ALCAEQ) / C.ALCANT) / C.ALUPRE) 
				 ))ALPREU  
FROM FV_ASCOAL02 C, GNR_DICOTIZA D, FV_ASCOAL01 CA
	WHERE CA.EMCODI = C.EMCODI
	  AND CA.DICODI = C.DICODI
	  AND CA.ACANYA = C.ACANYA
	  AND CA.ACNROA = C.ACNROA
	  AND CA.TIPDOC IS NULL
	  AND C.DIVISA = D.DIVISA
	  AND D.DIVISAMA = P_UTILIDAD.F_VALODEVA('DIVIEURO')
	  AND TRUNC(C.ACFENT) BETWEEN TRUNC(DESDFECH) AND TRUNC(HASTFECH)
	  AND (C.VATCOD != P_UTILIDAD.F_VALODEVA('TIARMPF4') OR (C.VATCOD = P_UTILIDAD.F_VALODEVA('TIARMPF4') AND C.VNACOD IN ('1','43','16','46')))
	  AND C.EMCODI = M.EMPRESA_M
	  AND C.VATCOD = M.TIP_ARTI_M
	  AND C.ARCARF = M.COD_ARTI_M
	  AND C.ASLOTE = P_UTILIDAD.F_VALOCAMPO(M.LOTE_M,'LOTE')
	  AND ROWNUM = 1) PRECIO_COMPRA_CALCULADO,
P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_PRECIO(M.EMPRESA_M,M.TIP_ARTI_M,M.COD_ARTI_M,O.FEC_MODI),'PRECIO') F_PRECIO,
DECODE(A.ANCHO,NULL
		,M.ANCHO
		,A.ANCHO) ANCHO_MP,
M.EMPRESA,M.NUMEOTRE,M.CONTADOR,M.TIP_ARTI TIPO_MP,M.COD_ARTI,M.LOTE,M.CANTCONS,M.CANTPROD,M.MEACSAFI,M.MEACSFMA,M.CANTCORE,M.CANTPRRE,
M.EMPRESA_M,M.NUMEOTRE_M,M.CONTADOR_M,M.TIP_ARTI_M,M.COD_ARTI_M,M.LOTE_M,M.CANTCONS_M_M,M.CANTPROD_M,M.MEACSAFI_M,M.MEACSFMA_M,M.CANTCORE_M,M.CANTPRRE_M,
--0
MA.MAQUCODI,
--1
AO.CLIENASOC N_CLIENTE,
C.RAZON_SOC CLIENTE,
--2
O.FEC_MODI FECHA_DE_LA_OT,
DECODE(O.SITUACIO,'C',O.FEC_MODI,NULL) FECHA_CIERRE_DE_LA_OT,
FA.CFFALT FECHA_FACTURA,
O.TIP_ARTI TIPO_PRD,
O.COD_ARTI ESPECIALIDAD,
SUBSTR(AO.COD_LFS,1,2) LINEA,
AO.COD_LFS LFS,
(SELECT COUNT(DISTINCT LFS.COD_LFS) FROM FIC_LINEOTRE LO, ARTICULO A, LFS 
 WHERE LO.EMPRESA = A.EMPRESA 
	AND LO.TIP_ARES = A.TIP_ARTI
	AND LO.COD_ARES = A.COD_ARTI
	AND A.EMPRESA = LFS.EMPRESA
	AND A.COD_LFS = LFS.COD_LFS
	AND LO.EMPRESA = O.EMPRESA 
	AND LO.ANNO = O.ANNO
	AND LO.NUMERO = O.NUMERO) N_CAPAS_TOTALES,
(SELECT COUNT(*) FROM FIC_LINEOTRE LO 
 WHERE LO.EMPRESA = O.EMPRESA 
	AND LO.ANNO = O.ANNO
	AND LO.NUMERO = O.NUMERO
	AND (INSTR(LO.COD_ARES,'IMPRESORA') != 0 OR INSTR(LO.COD_ARES,'LAMINADORA') != 0 OR INSTR(LO.COD_ARES,'LAQUEADORA') != 0 OR INSTR(LO.COD_ARES,'CORTADORA') != 0)) CANTIDAD_DE_FASES,
DECODE(O.TIP_ARTI,P_UTILIDAD.F_VALODEVA('TIARPROI'),(SELECT PI.ANCHO FROM FIC_HPIGESTI PI WHERE PI.EMPRESA = O.EMPRESA AND PI.NUMEPEDI = O.NUMEPEDI),AO.ANCHO) ANCHO_CLIENTE,
--SE ADICIONA
ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material(O.EMPRESA, O.NUMERO, (SELECT MAX(LO.FASE) FROM FIC_LINEOTRE LO
																					WHERE LO.EMPRESA = O.EMPRESA 
																					  AND LO.NUMERO = O.NUMERO
																					  AND ((INSTR(LO.COD_ARES,'IMPRESORA') != 0) OR
																							 (INSTR(LO.COD_ARES,'CORTADORA') != 0) OR
																							 (INSTR(LO.COD_ARES,'LAMINADORA') != 0) OR
																							 (INSTR(LO.COD_ARES,'LAQUEADORA') != 0)))) N_DE_CORTES,
--                                                                        
ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material_Exp_OT(O.EMPRESA, O.NUMERO, (SELECT MAX(LO.FASE) FROM FIC_LINEOTRE LO
																					WHERE LO.EMPRESA = O.EMPRESA 
																					  AND LO.NUMERO = O.NUMERO
																					  AND ((INSTR(LO.COD_ARES,'IMPRESORA') != 0) OR
																							 (INSTR(LO.COD_ARES,'CORTADORA') != 0) OR
																							 (INSTR(LO.COD_ARES,'LAMINADORA') != 0) OR
																							 (INSTR(LO.COD_ARES,'LAQUEADORA') != 0)))) N_DE_VECES,
 CASE WHEN MA.FASE IS NULL THEN ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material_Exp_OT(M.EMPRESA, M.NUMEOTRE, (SELECT MAX(LO.FASE) FROM FIC_LINEOTRE LO
																						WHERE LO.EMPRESA = M.EMPRESA 
																						  AND LO.NUMERO = M.NUMEOTRE
																						  AND ((INSTR(LO.COD_ARES,'IMPRESORA') != 0) OR
																								 (INSTR(LO.COD_ARES,'CORTADORA') != 0) OR
																								 (INSTR(LO.COD_ARES,'LAMINADORA') != 0) OR
																								 (INSTR(LO.COD_ARES,'LAQUEADORA') != 0)))) * DECODE(O.TIP_ARTI,P_UTILIDAD.F_VALODEVA('TIARPROI'),(SELECT PI.ANCHO FROM FIC_HPIGESTI PI WHERE PI.EMPRESA = O.EMPRESA AND PI.NUMEPEDI = O.NUMEPEDI),AO.ANCHO)--A.ANCHO
		ELSE ANALESTA.P_ANE_MERMLAMI_PRAG.F_Cortes_Material_Exp_OT(M.EMPRESA, M.NUMEOTRE, MA.FASE) * DECODE(O.TIP_ARTI,P_UTILIDAD.F_VALODEVA('TIARPROI'),(SELECT PI.ANCHO FROM FIC_HPIGESTI PI WHERE PI.EMPRESA = O.EMPRESA AND PI.NUMEPEDI = O.NUMEPEDI),AO.ANCHO)--A.ANCHO
		END ANCHO_DE_PRODUCCION,
		 --
         DECODE(NVL(ALB.LPCANT,0),0,O.UNIDAD,ALB.VUCVEN) UNIDAD_CIERRE,
			DECODE(DECODE(NVL(ALB.LPCANT,0),0,O.UNIDAD,ALB.VUCVEN),P_Utilidad.F_ValoDeva('TIPOUNML'),1,DECODE(NVL(F.ANCHO,0),0,0,DECODE(DECODE(NVL(ALB.LPCANT,0),0,O.UNIDAD,ALB.VUCVEN),P_Utilidad.F_ValoDeva('TIPOUNKG'),F.FCKG * (1000 / F.ANCHO),
                                                                                                        P_Utilidad.F_ValoDeva('TIPOUNM2'),(1000 / F.ANCHO),
                                                                                                        P_Utilidad.F_ValoDeva('TIPOUNUN'),(1000 / F.ANCHO) * ((F.ANCHO * F.LARGO) / 1000000)))) * DECODE(NVL(ALB.LPCANT,0),0,O.CANTCERR,ALB.LPCANT) CANTIDAD_ML,
         DECODE(DECODE(NVL(ALB.LPCANT,0),0,O.UNIDAD,ALB.VUCVEN),P_Utilidad.F_ValoDeva('TIPOUNM2'),1,P_Utilidad.F_ValoDeva('TIPOUNKG'),F.FCKG,
                                                             P_Utilidad.F_ValoDeva('TIPOUNML'),(F.ANCHO / 1000),
                                                             P_Utilidad.F_ValoDeva('TIPOUNUN'),(F.ANCHO * F.LARGO) / 1000000) * DECODE(NVL(ALB.LPCANT,0),0,O.CANTCERR,ALB.LPCANT) CANTIDAD_M2,
         DECODE(DECODE(NVL(ALB.LPCANT,0),0,O.UNIDAD,ALB.VUCVEN),P_Utilidad.F_ValoDeva('TIPOUNKG'),1,DECODE(NVL(F.FCKG,0),0,0,DECODE(DECODE(NVL(ALB.LPCANT,0),0,O.UNIDAD,ALB.VUCVEN),P_Utilidad.F_ValoDeva('TIPOUNML'),(1 / F.FCKG) * (F.ANCHO / 1000),
                                                                                                        P_Utilidad.F_ValoDeva('TIPOUNM2'),1 / F.FCKG,
                                                                                                        P_Utilidad.F_ValoDeva('TIPOUNUN'),(1 / F.FCKG) * ((F.ANCHO * F.LARGO) / 1000000)))) * DECODE(NVL(ALB.LPCANT,0),0,O.CANTCERR,ALB.LPCANT) CANTIDAD_KG,
			DECODE(DECODE(NVL(ALB.LPCANT,0),0,O.UNIDAD,ALB.VUCVEN),P_Utilidad.F_ValoDeva('TIPOUNUN'),1,P_Utilidad.F_ValoDeva('TIPOUNML'),DECODE(NVL(F.ANCHO,0)*NVL(F.LARGO,0),0,0,(1 / ((1000 / F.ANCHO) * ((F.ANCHO * F.LARGO) / 1000000)))),
                                                                              P_Utilidad.F_ValoDeva('TIPOUNM2'),DECODE(NVL(F.ANCHO,0)*NVL(F.LARGO,0),0,0,(1000000 / (F.ANCHO * F.LARGO))),
                                                                              P_Utilidad.F_ValoDeva('TIPOUNKG'),DECODE(NVL(F.ANCHO,0)*NVL(F.LARGO,0)*NVL(F.FCKG,0),0,0,(1 / ((1 / F.FCKG) * ((F.ANCHO * F.LARGO) / 1000000))))) * DECODE(NVL(ALB.LPCANT,0),0,O.CANTCERR,ALB.LPCANT) CANTIDAD_UN,
DECODE(NVL(ALB.LPCANT,0),0,'CIERRE DE OT','EXPEDICION') FUENTE_DEL_CIERRE,
       --
		 NVL(M.CANTCONS_M_M,0)*(NVL(M.MM_MERMPLAN_M,0)/1000) M2_MERMPLAN, 
		 NVL(M.CANTCONS_M_M,0)*(NVL(M.MM_MERMPLAN_EXESO_M,0)/1000) M2_MERMPLAN_EXESO,
		 --
		 NVL(M.CANTCONS_M_M,0)*(NVL(M.MM_MERMPLAN_M,0)/1000) * 
		 DECODE(NVL((PRECIO_ML * DECODE(NVL(A.ANCHO,0),0,0,(1000/A.ANCHO))),0),0,--Prevalece el precio de costes
		 DECODE(NVL((
         SELECT DECODE(C.ALUNST,P_Utilidad.F_ValoDeva('TIPOUNM2'),DECODE(NVL(C.ALUPRE,0),0,DECODE(NVL(C.ALCANT,0), 0, 0,((C.ALPREU * D.CAMBIO) * C.ALCAEQ) / C.ALCANT),
                                                                  DECODE(NVL(C.ALCANT,0), 0, 0,(((C.ALPREU * D.CAMBIO) * C.ALCAEQ) / C.ALCANT) / C.ALUPRE) 
                      ))ALPREU  
         FROM FV_ASCOAL02 C, GNR_DICOTIZA D, FV_ASCOAL01 CA
            WHERE CA.EMCODI = C.EMCODI
              AND CA.DICODI = C.DICODI
              AND CA.ACANYA = C.ACANYA
              AND CA.ACNROA = C.ACNROA
              AND CA.TIPDOC IS NULL
              AND C.DIVISA = D.DIVISA
              AND D.DIVISAMA = P_UTILIDAD.F_VALODEVA('DIVIEURO')
              AND TRUNC(C.ACFENT) BETWEEN TRUNC(DESDFECH) AND TRUNC(HASTFECH)
              AND (C.VATCOD != P_UTILIDAD.F_VALODEVA('TIARMPF4') OR (C.VATCOD = P_UTILIDAD.F_VALODEVA('TIARMPF4') AND C.VNACOD IN ('1','43','16','46')))
              AND C.EMCODI = M.EMPRESA_M
              AND C.VATCOD = M.TIP_ARTI_M
              AND C.ARCARF = M.COD_ARTI_M
              AND C.ASLOTE = P_UTILIDAD.F_VALOCAMPO(M.LOTE,'LOTE')
              AND ROWNUM = 1),0),0,
		            P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_PRECIO(M.EMPRESA,M.TIP_ARTI_M,M.COD_ARTI_M,O.FEC_MODI),'PRECIO'),
		            (
         SELECT DECODE(C.ALUNST,P_Utilidad.F_ValoDeva('TIPOUNM2'),DECODE(NVL(C.ALUPRE,0),0,DECODE(NVL(C.ALCANT,0), 0, 0,((C.ALPREU * D.CAMBIO) * C.ALCAEQ) / C.ALCANT),
                                                                  DECODE(NVL(C.ALCANT,0), 0, 0,(((C.ALPREU * D.CAMBIO) * C.ALCAEQ) / C.ALCANT) / C.ALUPRE) 
                      ))ALPREU  
         FROM FV_ASCOAL02 C, GNR_DICOTIZA D, FV_ASCOAL01 CA
            WHERE CA.EMCODI = C.EMCODI
              AND CA.DICODI = C.DICODI
              AND CA.ACANYA = C.ACANYA
              AND CA.ACNROA = C.ACNROA
              AND CA.TIPDOC IS NULL
              AND C.DIVISA = D.DIVISA
              AND D.DIVISAMA = P_UTILIDAD.F_VALODEVA('DIVIEURO')
              AND TRUNC(C.ACFENT) BETWEEN TRUNC(DESDFECH) AND TRUNC(HASTFECH)
              AND (C.VATCOD != P_UTILIDAD.F_VALODEVA('TIARMPF4') OR (C.VATCOD = P_UTILIDAD.F_VALODEVA('TIARMPF4') AND C.VNACOD IN ('1','43','16','46')))
              AND C.EMCODI = M.EMPRESA
              AND C.VATCOD = M.TIP_ARTI
              AND C.ARCARF = M.COD_ARTI
              AND C.ASLOTE = P_UTILIDAD.F_VALOCAMPO(M.LOTE,'LOTE')
              AND ROWNUM = 1)),PRECIO_ML * DECODE(NVL(A.ANCHO,0),0,0,(1000/A.ANCHO))) EUR_MERMPLAN,
		 NVL(M.CANTCONS_M_M,0)*(NVL(M.MM_MERMPLAN_EXESO_M,0)/1000) * 
		 DECODE(NVL((PRECIO_ML * DECODE(NVL(A.ANCHO,0),0,0,(1000/A.ANCHO))),0),0,--Prevalece el precio de costes
		 DECODE(NVL((
         SELECT DECODE(C.ALUNST,P_Utilidad.F_ValoDeva('TIPOUNM2'),DECODE(NVL(C.ALUPRE,0),0,DECODE(NVL(C.ALCANT,0), 0, 0,((C.ALPREU * D.CAMBIO) * C.ALCAEQ) / C.ALCANT),
                                                                  DECODE(NVL(C.ALCANT,0), 0, 0,(((C.ALPREU * D.CAMBIO) * C.ALCAEQ) / C.ALCANT) / C.ALUPRE) 
                      ))ALPREU  
         FROM FV_ASCOAL02 C, GNR_DICOTIZA D, FV_ASCOAL01 CA
            WHERE CA.EMCODI = C.EMCODI
              AND CA.DICODI = C.DICODI
              AND CA.ACANYA = C.ACANYA
              AND CA.ACNROA = C.ACNROA
              AND CA.TIPDOC IS NULL
              AND C.DIVISA = D.DIVISA
              AND D.DIVISAMA = P_UTILIDAD.F_VALODEVA('DIVIEURO')
              AND TRUNC(C.ACFENT) BETWEEN TRUNC(DESDFECH) AND TRUNC(HASTFECH)
              AND (C.VATCOD != P_UTILIDAD.F_VALODEVA('TIARMPF4') OR (C.VATCOD = P_UTILIDAD.F_VALODEVA('TIARMPF4') AND C.VNACOD IN ('1','43','16','46')))
              AND C.EMCODI = M.EMPRESA_M
              AND C.VATCOD = M.TIP_ARTI_M
              AND C.ARCARF = M.COD_ARTI_M
              AND C.ASLOTE = P_UTILIDAD.F_VALOCAMPO(M.LOTE,'LOTE')
              AND ROWNUM = 1),0),0,
				  P_UTILIDAD.F_VALOCAMPO(ANALESTA.P_ANE_MERMLAMI_PRAG.F_PRECIO(M.EMPRESA,M.TIP_ARTI_M,M.COD_ARTI_M,O.FEC_MODI),'PRECIO'),
				  (
         SELECT DECODE(C.ALUNST,P_Utilidad.F_ValoDeva('TIPOUNM2'),DECODE(NVL(C.ALUPRE,0),0,DECODE(NVL(C.ALCANT,0), 0, 0,((C.ALPREU * D.CAMBIO) * C.ALCAEQ) / C.ALCANT),
                                                                  DECODE(NVL(C.ALCANT,0), 0, 0,(((C.ALPREU * D.CAMBIO) * C.ALCAEQ) / C.ALCANT) / C.ALUPRE) 
                      ))ALPREU  
         FROM FV_ASCOAL02 C, GNR_DICOTIZA D, FV_ASCOAL01 CA
            WHERE CA.EMCODI = C.EMCODI
              AND CA.DICODI = C.DICODI
              AND CA.ACANYA = C.ACANYA
              AND CA.ACNROA = C.ACNROA
              AND CA.TIPDOC IS NULL
              AND C.DIVISA = D.DIVISA
              AND D.DIVISAMA = P_UTILIDAD.F_VALODEVA('DIVIEURO')
              AND TRUNC(C.ACFENT) BETWEEN TRUNC(DESDFECH) AND TRUNC(HASTFECH)
              AND (C.VATCOD != P_UTILIDAD.F_VALODEVA('TIARMPF4') OR (C.VATCOD = P_UTILIDAD.F_VALODEVA('TIARMPF4') AND C.VNACOD IN ('1','43','16','46')))
              AND C.EMCODI = M.EMPRESA_M
              AND C.VATCOD = M.TIP_ARTI_M
              AND C.ARCARF = M.COD_ARTI_M
              AND C.ASLOTE = P_UTILIDAD.F_VALOCAMPO(M.LOTE,'LOTE')
              AND ROWNUM = 1)),PRECIO_ML * DECODE(NVL(A.ANCHO,0),0,0,(1000/A.ANCHO))) EUR_MERMPLAN_EXESO
		 --
FROM ANALESTA.ANE_MER_MATERIAL_OT_CONTADOR M, ARTICULO A, FIC_CABEOTRE O,
     ARTICULO AO, CLIENTES C,
	 (SELECT MA.EMPRESA, MA.NUMEOTRE, MA.CONTADOR, DECODE(INSTR(MA.MAQUCODI,'CORTADORA'),0,NULL,L.FASE) FASE, L.FASE FASEBUMP, MA.MAQUCODI--, MIN(MP.IZQUIERD) IZQUIERD, MIN(MP.DERECHA) DERECHA 
		FROM --PRD_MAQUMPLA MP, 
			  (SELECT MR.EMPRESA, MR.NUMEOTRE, MR.CONTADOR, MR.FASESEQU, MR.MAQUTIPO, MR.MAQUCODI, MR.ESTADO FROM PRD_MAQURUTA MR
				WHERE NOT EXISTS (SELECT 'X' FROM PRD_HCABEOTR OTC WHERE OTC.EMPRESA = MR.EMPRESA AND OTC.NUMEOTRE = MR.NUMEOTRE)
				UNION
				SELECT MR.EMPRESA, MR.NUMEOTRE, MR.CONTADOR, MR.FASESEQU, MR.MAQUTIPO, MR.MAQUCODI, MR.ESTADO FROM PRD_HMAQURUT MR) MA, 
			  FIC_LINEOTRE L
			WHERE /*MP.EMPRESA = MA.EMPRESA
			  AND MP.MAQUTIPO = MA.MAQUTIPO
			  AND MP.MAQUCODI = MA.MAQUCODI
			  AND */L.EMPRESA = MA.EMPRESA
			  AND L.NUMERO = MA.NUMEOTRE
			  AND L.TIP_ARES = P_UTILIDAD.F_VALODEVA('TIPORECU')
			  AND (L.COD_ARES NOT LIKE 'CORTADORA%' OR --Si es diferente de Cortadora 
					 (                                   --o
					  L.COD_ARES LIKE 'CORTADORA%' AND NOT EXISTS (SELECT 'X'
																				  FROM VALORES_LISTA V
																				  WHERE V.CODIGO = 'FIC_TIPIRECU'
																					 AND INSTR(L.COD_ARES,P_UTILIDAD.F_VALOCAMPO(V.VALOR,'RECURSO')) != 0
																					 AND P_UTILIDAD.F_VALOCAMPO(V.VALOR,'CODIGO') = L.TIPIRECU
																					 AND P_UTILIDAD.F_VALOCAMPO(V.VALOR,'PRE-CORTE') = 'S')--L.FASE = L.FASESIGU --Si es cortadora pero no es pre-corte
					 )
					)
			  AND MA.FASESEQU = (L.FASE * 100) + L.SECUENCI
			  --AND TIPO = 'E'
		--GROUP BY MA.EMPRESA, MA.NUMEOTRE, MA.CONTADOR, DECODE(INSTR(MA.MAQUCODI,'CORTADORA'),0,NULL,L.FASE)
		) MA,
     (SELECT LO.EMCODI, LO.ASLOTE, LO.CFNDEF, FA.CFFALT
      FROM FV_ASVELO01 LO, FV_ASVEFA01 FA
      WHERE LO.EMCODI = FA.EMCODI
        AND LO.CFNDEF = FA.CFNDEF) FA,
     (SELECT O.EMPRESA, O.NUMERO, A.VUCVEN, SUM(A.LACANT) LPCANT --Unidad y Cantidad de Expedición de Albaranes
            FROM FV_ASVEALH02 A, 
                 FIC_CABEOTRE O,
                 (SELECT DISTINCT EMCODI, CPNROP, ASLOTE, ALNROP, VATCOD, ARCARF, CFNROF FROM FV_ASVELO01 WHERE PROCED = 'F') L
            WHERE A.EMCODI = O.EMPRESA
              AND A.VATCOD = O.TIP_ARTI
              AND A.ARCARF = O.COD_ARTI
              AND A.DICODI = '01'
              AND A.ASCANA = 1
              AND A.CPNROP = O.NUMEPEDI
              AND L.EMCODI = A.EMCODI
              AND L.ALNROP = A.ALNROP
              AND L.VATCOD = A.VATCOD
              AND L.ARCARF = A.ARCARF
              AND L.CPNROP = A.CPNROP
              AND L.EMCODI = O.EMPRESA
              AND L.ASLOTE = TO_CHAR(O.NUMERO)
              AND L.CPNROP = O.NUMEPEDI
              AND NVL(L.CFNROF,0) != 0
              AND EXISTS (SELECT 'X' FROM FV_ASVEFA02 F
                         WHERE F.EMCODI = O.EMPRESA
                           AND F.DICODI = '01'
                           AND F.ASCANA = 1
                           AND F.CPNROP = O.NUMEPEDI
                           AND F.VATCOD = O.TIP_ARTI
                           AND F.ARCARF = O.COD_ARTI)--Este Facturada la OT
              /*AND NOT EXISTS (SELECT 'X' FROM FIC_LINEPEDI P
                              WHERE P.EMPRESA = O.EMPRESA
                                AND P.NUMEPEDI = O.NUMEPEDI
                                AND P.TIP_ARTI = O.TIP_ARTI
                                AND P.COD_ARTI = O.COD_ARTI)--No quede Pendiente nada por Generar Albaran*/
              AND O.TIP_ARTI = P_UTILIDAD.F_VALODEVA('TIARFIF4')
         GROUP BY O.EMPRESA, O.NUMERO, A.VUCVEN) ALB,
	(SELECT F.EMPRESA, F.TIP_ARTI, F.PRODUCTO, F.MODI, F.REVI, F.ANCHO, F.LARGO, LFS.FCKG FROM HFICTEC F, LFS
	 WHERE F.EMPRESA = LFS.EMPRESA
		AND F.MATBASE = LFS.COD_LFS) F
WHERE M.EMPRESA_M = A.EMPRESA
  AND M.TIP_ARTI_M = A.TIP_ARTI
  AND M.COD_ARTI_M = A.COD_ARTI
  --
  AND M.EMPRESA_M = O.EMPRESA
  AND M.NUMEOTRE_M = O.NUMERO
  --
  AND O.EMPRESA = AO.EMPRESA
  AND O.TIP_ARTI = AO.TIP_ARTI
  AND O.COD_ARTI = AO.COD_ARTI
  --
  AND AO.EMPRESA = C.EMPRESA(+)
  AND AO.CLIENASOC = C.CLIENTE_ID(+)
  --
  AND M.EMPRESA = MA.EMPRESA
  AND M.NUMEOTRE = MA.NUMEOTRE
  AND M.CONTADOR = MA.CONTADOR
  --
  AND O.EMPRESA = FA.EMCODI(+)
  AND O.NUMERO = FA.ASLOTE(+)
  --
  AND O.EMPRESA = ALB.EMPRESA(+)
  AND O.NUMERO = ALB.NUMERO(+)
  --
  AND O.EMPRESA = F.EMPRESA(+)
  AND O.TIP_ARTI = F.TIP_ARTI(+)
  AND O.COD_ARTI = F.PRODUCTO(+)
  AND O.MODI = F.MODI(+)
  AND O.REVI = F.REVI(+)
  --
  AND NVL(M.CANTCONS,0) != 0 --Filtra Materiales en 0
)  M
GROUP BY M.EMPRESA, 
       --1
		 M.N_CLIENTE,
       M.CLIENTE,
		 --
       M.NUMEOTRE, M.CONTADOR, 
		 --2
		 M.FECHA_DE_LA_OT,
		 M.FECHA_CIERRE_DE_LA_OT,
		 M.FECHA_FACTURA,
		 M.TIPO_PRD,
		 M.ESPECIALIDAD,
		 M.LINEA,
		 M.LFS,
		 --
		 M.TIPO_MP,
		 --
		 M.COD_LFS, M.MAQUCODI,	
		 --
		 UNIDAD_CIERRE, CANTIDAD_ML, CANTIDAD_M2, CANTIDAD_KG, CANTIDAD_UN, FUENTE_DEL_CIERRE
;

--235sj
