CREATE OR REPLACE VIEW ANALESTA.ANE_ESTRUCTURA_LAMINADORA AS
SELECT C.LINETIPR LINEA, LI.DESCRIPCION DESCRIPCION_LINEA, P.DEFIPASA PASADA, L.TIP_ARTI TIPO_ARTICULO, L.COD_ARTI ARTICULO, A.DESCRIPCION DESCRIPCION_ARTICULO, L.GRAMOSM2
FROM FIC_CAECLAMI C, GNR_LINEAS LI, FIC_PAECLAMI P, FIC_ESCOLAMI L, ARTICULO A
WHERE C.LINETIPR = LI.LINEA
  AND C.LINETIPR = P.LINETIPR
  AND L.DEFIPASA = P.DEFIPASA
  AND L.LINETIPR = P.LINETIPR
  AND A.EMPRESA IN (SELECT VALOR FROM VALORES_LISTA WHERE CODIGO = 'GNR_EMPRACGR')
  AND L.TIP_ARTI = A.TIP_ARTI
  AND L.COD_ARTI = A.COD_ARTI;
  