CREATE OR REPLACE VIEW ANALESTA.ANE_AUX_ACUMULADOS AS
SELECT ANNO,ULTIMO_MES_CARGADO,PRIMER_DIA,ULTIMO_DIA,
       APLICA_A_EMPRESA_GRUPO,EMPRESA,IDENTIFICADOR,
       SUM(EXISTENCIAS_TOTALES_FX) EXISTENCIAS_TOTALES_FX, SUM(COSTE_TOTAL_FX) COSTE_TOTAL_FX, SUM(ANCHO_TOTAL_FX) ANCHO_TOTAL_FX,
       DECODE(NVL(SUM(EXISTENCIAS_TOTALES_FX),0),0,NULL,SUM(COSTE_TOTAL_FX)/SUM(EXISTENCIAS_TOTALES_FX)) COSTE_PROMEDIO_FX,
       DECODE(NVL(SUM(EXISTENCIAS_TOTALES_FX),0),0,NULL,SUM(ANCHO_TOTAL_FX)/SUM(EXISTENCIAS_TOTALES_FX)) ANCHO_PROMEDIO_FX,
       MAX(ERROR_ENCONTRADO) ERROR_ENCONTRADO
FROM ANALESTA.ANE_ARTICULOS_AUX_ACUMULADOS
GROUP BY ANNO,ULTIMO_MES_CARGADO,PRIMER_DIA,ULTIMO_DIA,
         APLICA_A_EMPRESA_GRUPO,EMPRESA,IDENTIFICADOR;