CREATE OR REPLACE VIEW ANALESTA.ANE_TIPIFICACION_ABONOS AS
SELECT I.TIPIFICA TIPIFICACION, I.DESCRIPC DESCRIPCION_TIPIFICACION, I.PARAMETR PARAMETRO, P.DESCRIPC DESCRIPCION_PARAMETRO, I.OBSERVAC OBSERVACION, T.TIPOIMPU TIPO_DE_IMPUTACION
FROM RCL_TIPIABON I, RCL_INOCABON T, RCL_PARAABON P
WHERE T.TIPIFICA = I.TIPIFICA
  AND P.PARAMETR = I.PARAMETR;
  